<a href="https://colab.research.google.com/github/amankiitg/LLM_Prod/blob/main/Reditt_Text_Clustering_and_Topic_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Text Clustering and Topic Modeling</h1>
<i>Clustering documents using a wide variety of language models.</i>

### [OPTIONAL] - Installing Packages on <img src="https://colab.google/static/images/icons/colab.png" width=100>

If you are viewing this notebook on Google Colab (or any other cloud vendor), you need to **uncomment and run** the following codeblock to install the dependencies for this chapter:

---

💡 **NOTE**: We will want to use a GPU to run the examples in this notebook. In Google Colab, go to
**Runtime > Change runtime type > Hardware accelerator > GPU > GPU type > T4**.

---

In [ ]:
!pip install asyncpraw

Collecting asyncpraw
  Downloading asyncpraw-7.8.1-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: aiofiles in /usr/local/lib/python3.12/dist-packages (from asyncpraw) (24.1.0)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from asyncpraw) (3.12.15)
Collecting aiosqlite<=0.17.0 (from asyncpraw)
  Downloading aiosqlite-0.17.0-py3-none-any.whl.metadata (4.1 kB)
Collecting asyncprawcore<3,>=2.4 (from asyncpraw)
  Downloading asyncprawcore-2.4.0-py3-none-any.whl.metadata (5.5 kB)
Collecting update_checker>=0.18 (from asyncpraw)
  Downloading update_checker-0.18.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (1.20.1)
Requirement already satisfied: typing_extensions>=3.7.2 in /usr/local/lib/python3.12/dist-packages (from aiosqlite<=0.17.0->asyncpraw) (4.14.1)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from update_checker>=0.18->asyncpraw) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (2025.8.3)
Downloading asyncpraw-7.8.1-py3-none-any.whl (196 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.4/196.4 kB 3.9 MB/s eta 0:00:00
Downloading aiosqlite-0.17.0-py3-none-any.whl (15 kB)
Downloading asyncprawcore-2.4.0-py3-none-any.whl (19 kB)
Downloading update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Installing collected packages: aiosqlite, update_checker, asyncprawcore, asyncpraw
Successfully installed aiosqlite-0.17.0 asyncpraw-7.8.1 asyncprawcore-2.4.0 update_checker-0.18.0

In [ ]:
import asyncio
import asyncpraw
import nest_asyncio
import json
import numpy as np
import re
import string

# --------------------
# Text cleaning helper
# --------------------
def clean_text(text):
    """Cleans text by removing URLs, punctuation, and lowercasing."""
    text = re.sub(r'http\S+|https\S+', '', text)   # Remove URLs
    text = text.replace('\n', ' ')                 # Remove newlines
    text = text.translate(str.maketrans('', '', string.punctuation))  # Remove punctuation
    return text.lower().strip()

def extract_comment_bodies(comments):
    """Recursively extracts bodies and scores for thresholding."""
    bodies, scores = [], []
    for comment in comments:
        bodies.append(comment['body'])
        scores.append(comment['score'])
        if comment.get('replies'):
            child_bodies, child_scores = extract_comment_bodies(comment['replies'])
            bodies.extend(child_bodies)
            scores.extend(child_scores)
    return bodies, scores

# --------------------
# Main Scraper
# --------------------
async def scrape():
    async with asyncpraw.Reddit(
        client_id="glnTvdUs1KFycKy5vEsOig",
        client_secret="ET1IgiyCztIxhXSwnFIYbTs3eq2nRQ",
        user_agent="Topic Modeler"
    ) as reddit:

        url = "https://www.reddit.com/r/ChatGPT/comments/1mkae1l/gpt5_ama_with_openais_sam_altman_and_some_of_the/"
        submission = await reddit.submission(url=url)

        async def extract_comment(comment):
            return {
                "author": str(comment.author),
                "body": comment.body,
                "score": comment.score,
                "replies": [await extract_comment(reply) async for reply in comment.replies]
            }

        # Build post object
        post_data = {
            "title": submission.title,
            "author": str(submission.author),
            "score": submission.score,
            "url": submission.url,
            "selftext": submission.selftext,
            "comments": []
        }

        # Load comments
        await submission.comments.replace_more(limit=None)
        for top_comment in submission.comments:
            post_data["comments"].append(await extract_comment(top_comment))

        # Flatten scores for median threshold
        _, all_scores = extract_comment_bodies(post_data["comments"])
        median_score = np.median(all_scores) if all_scores else 0

        # --------------------
        # Filter + transform comments
        # --------------------
        def filter_and_transform(comments):
            """Filter by median score and create title/abstract."""
            result = []
            for c in comments:
                if c['score'] >= median_score:
                    result.append({
                        "title": clean_text(c['body'])[:60],   # First 60 chars as title
                        "abstract": clean_text(c['body']),     # Full cleaned body
                        "score": c['score'],
                        "author": c['author']
                    })
                if c.get('replies'):
                    result.extend(filter_and_transform(c['replies']))
            return result

        post_data["comments"] = filter_and_transform(post_data["comments"])
        post_data["median_score_threshold"] = median_score

        # Dump JSON
        with open("reddit_post_filtered.json", "w", encoding="utf-8") as f:
            json.dump(post_data, f, indent=2, ensure_ascii=False)

        print("✅ Filtered post data saved to reddit_post_filtered.json")

# --------------------
# Run safely with nest_asyncio
# --------------------
nest_asyncio.apply()
asyncio.run(scrape())

✅ Filtered post data saved to reddit_post_filtered.json

/tmp/ipython-input-3660819704.py:65: DeprecationWarning: Using CommentForest as an asynchronous iterator has been deprecated and will be removed in a future version.
  post_data["comments"].append(await extract_comment(top_comment))
/tmp/ipython-input-3660819704.py:49: DeprecationWarning: Using CommentForest as an asynchronous iterator has been deprecated and will be removed in a future version.
  "replies": [await extract_comment(reply) async for reply in comment.replies]

# **Load Reditt Data**

In [14]:
import json

with open("/content/reddit_post_filtered.json", "r", encoding="utf-8") as f:
    reddit_data = json.load(f)

# Recursive extractor for title and abstract
def extract_title_abstract(comments):
    result = []
    for c in comments:
        result.append({
            "title": c["title"],
            "abstract": c["abstract"]
        })
        if c.get("replies"):
            result.extend(extract_title_abstract(c["replies"]))
    return result

# Extract only title and abstract
titles_and_abstracts = extract_title_abstract(reddit_data["comments"])

# Display first 10
for item in titles_and_abstracts[:10]:
    print(item)

# # Extract metadata and convert to standard list
abstracts = [t['abstract'] for t in titles_and_abstracts]
titles = [t['title'] for t in titles_and_abstracts]

{'title': 'i see that em dash', 'abstract': 'i see that em dash'}
{'title': 'its not an em dash — its a pause that demands attention', 'abstract': 'its not an em dash — its a pause that demands attention'}
{'title': 'can you mark the other cohosts their answers are buried and ', 'abstract': 'can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks'}
{'title': 'only uopenai can i think theres a limit to the number of par', 'abstract': 'only uopenai can i think theres a limit to the number of participants'}
{'title': 'ah thats a bother perhaps sticky links to them in a comment ', 'abstract': 'ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit'}
{'title': 'hot damnnnnn he tucked tail and ran outta there fast when he', 'abstract': 'hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons'}
{'title': 'yeah but did you see you can now change the color of the cha', 'abstract': 'yeah but did you see you can now change the color of the chat bubbles wow sam truly the next oppenheimer'}
{'title': 'will it be in this same post or will there be a new post', 'abstract': 'will it be in this same post or will there be a new post'}
{'title': 'openai team will start answering the questions on this same ', 'abstract': 'openai team will start answering the questions on this same post at 1100 am pt'}
{'title': 'also on exisitng qs or must we come back to ask live', 'abstract': 'also on exisitng qs or must we come back to ask live'}

## **BERTopic: A Modular Topic Modeling Framework**

In [15]:
!pip install -q bertopic openai datasets datamapplot

In [16]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, DBSCAN
from umap import UMAP
from hdbscan import HDBSCAN
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, TextGeneration, OpenAI
from transformers import pipeline
from wordcloud import WordCloud
import openai
from copy import deepcopy
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from google.colab import userdata
import datamapplot
import re


def find_best_k(embeddings, k_min=2, k_max=15, random_state=42):
    """Return best k based on silhouette score"""
    best_score = -1
    best_k = k_min
    for k in range(k_min, k_max + 1):
        kmeans = KMeans(n_clusters=k, random_state=random_state).fit(embeddings)
        score = silhouette_score(embeddings, kmeans.labels_)
        if score > best_score:
            best_score = score
            best_k = k
    print(f"✅ Best k for KMeans: {best_k} with silhouette {best_score:.3f}")
    return best_k

# ==================== Helper Functions ====================
def topic_differences(model, original_topics, nr_topics=5):
    df = pd.DataFrame(columns=["Topic", "Original", "Updated"])
    for topic in range(nr_topics):
        og_words = " | ".join(list(zip(*original_topics[topic]))[0][:5])
        new_words = " | ".join(list(zip(*model.get_topic(topic)))[0][:5])
        df.loc[len(df)] = [topic, og_words, new_words]
    return df

def create_wordcloud(model, topic, save_path=None):
    """Generate a wordcloud for a given topic if it exists."""
    topic_words = model.get_topic(topic)
    if not topic_words:  # Returns False if topic does not exist
        print(f"⚠️ Topic {topic} does not exist. Skipping wordcloud.")
        return

    plt.figure(figsize=(10,5))
    text = {word: value for word, value in topic_words}
    wc = WordCloud(background_color="white", max_words=1000, width=1600, height=800)
    wc.generate_from_frequencies(text)
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    if save_path:
        plt.savefig(save_path, bbox_inches='tight')
    plt.close()


def save_document_visualization(model, documents, reduced_embeddings, save_path=None):
    """
    Visualize BERTopic documents and save as HTML.

    Args:
        model: BERTopic model
        documents: list of documents/abstracts
        reduced_embeddings: reduced embeddings used for visualization
        save_path: path to save HTML file
    """
    fig = model.visualize_documents(
        documents,
        reduced_embeddings=reduced_embeddings,
        width=1200,
        hide_annotations=True
    )
    fig.update_layout(font=dict(size=8))

    if save_path:
        fig.write_html(save_path)
        print(f"✅ Document visualization saved as HTML: {save_path}")

    plt.close()



def get_cluster_info(model, documents):
    """Return a dict with each cluster's top sentences and topic labels"""
    clusters = {}
    topics = model.get_document_info(documents)
    for topic_id in topics['Topic'].unique():
        if topic_id == -1:
            continue
        cluster_docs = topics[topics.Topic==topic_id]['Document'].tolist()
        label = model.get_topic(topic_id)
        clusters[topic_id] = {
            "top_sentences": cluster_docs[:5],  # top 5 representative sentences
            "topic_label": model.get_topic_info().loc[model.get_topic_info().Topic==topic_id, "Name"].values[0]
        }
    return clusters



# ==================== Config ====================
embedding_models = {
    "gte-small": "thenlper/gte-small",
    "multilingual-e5-large": "intfloat/multilingual-e5-large-instruct"
}

dim_reduction_models = {
    # "umap": UMAP(n_components=5, min_dist=0.0, metric="cosine", random_state=42),
    "pca": PCA(n_components=5, random_state=42)
}

clustering_models = {
    "hdbscan": HDBSCAN(min_cluster_size=10, metric="euclidean", cluster_selection_method="eom"),
    "dbscan": DBSCAN(eps=0.01, min_samples=5, metric="euclidean"),
    "kmeans": KMeans(n_clusters=10, random_state=42)
}

In [17]:
def save_document_visualization_png(model, documents, reduced_embeddings, save_path=None):
    """
    Visualize BERTopic documents and save as PNG with arrow annotations.

    Args:
        model: BERTopic model
        documents: list of documents/abstracts
        reduced_embeddings: reduced embeddings used for visualization
        save_path: path to save PNG file
    """
    import numpy as np
    import matplotlib.pyplot as plt

    # Save as PNG using matplotlib
    if save_path:
        # Ensure the save path has .png extension
        if not save_path.lower().endswith('.png'):
            save_path = save_path.rsplit('.', 1)[0] + '.png'

        # Create matplotlib version
        plt.figure(figsize=(12, 8))

        # Get topic assignments and create color map
        topic_assignments = np.array(model.topics_)
        unique_topics = np.unique(topic_assignments)
        colors = plt.cm.Set3(np.linspace(0, 1, len(unique_topics)))
        color_map = {topic: colors[i] for i, topic in enumerate(unique_topics)}

        # Plot points
        for topic in unique_topics:
            mask = topic_assignments == topic
            if topic == -1:  # Outliers
                plt.scatter(reduced_embeddings[mask, 0], reduced_embeddings[mask, 1],
                          c='gray', alpha=0.6, s=20, label='Outliers')
            else:
                plt.scatter(reduced_embeddings[mask, 0], reduced_embeddings[mask, 1],
                          c=[color_map[topic]], alpha=0.7, s=30, label=f'Topic {topic}')

        # Randomly select 20% of topics for labeling
        import random
        non_outlier_topics = [t for t in unique_topics if t != -1]
        num_topics_to_label = max(1, int(len(non_outlier_topics) * 0.2))
        topics_to_label = random.sample(non_outlier_topics, num_topics_to_label)

        # Add arrows pointing to cluster centers (only for selected topics)
        for topic in unique_topics:
            if topic != -1 and topic in topics_to_label:  # Only label selected topics
                mask = topic_assignments == topic
                if np.any(mask):
                    center_x = np.mean(reduced_embeddings[mask, 0])
                    center_y = np.mean(reduced_embeddings[mask, 1])

                    # Get topic words and wrap text
                    topic_words = model.get_topic(topic)
                    topic_label = ", ".join([word for word, _ in topic_words[:3]])

                    # Wrap text to limit width (approximately 15 characters per line)
                    import textwrap
                    wrapped_label = "\n".join(textwrap.wrap(topic_label, width=15))
                    final_label = f"Topic {topic}\n{wrapped_label}"

                    # Calculate direction from overall center to cluster center
                    overall_center_x = np.mean(reduced_embeddings[:, 0])
                    overall_center_y = np.mean(reduced_embeddings[:, 1])

                    direction_x = center_x - overall_center_x
                    direction_y = center_y - overall_center_y

                    # Normalize and extend (back to original distance)
                    length = np.sqrt(direction_x**2 + direction_y**2)
                    if length > 0:
                        direction_x /= length
                        direction_y /= length

                    # Place text at original distance (2.5)
                    text_distance = 2.5
                    text_x = center_x + direction_x * text_distance
                    text_y = center_y + direction_y * text_distance

                    # Add arrow and text
                    plt.annotate(final_label,
                               xy=(center_x, center_y),
                               xytext=(text_x, text_y),
                               arrowprops=dict(arrowstyle='->', color='black', lw=2),
                               bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8),
                               fontsize=8, ha='center', va='center')

        plt.title('Document Visualization with Topic Clusters', fontsize=14)
        plt.xlabel('Dimension 1', fontsize=12)
        plt.ylabel('Dimension 2', fontsize=12)
        plt.grid(True, alpha=0.3)

        # Save matplotlib version
        plt.tight_layout()
        plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
        # plt.close()
        print(f"Document visualization saved as PNG: {save_path}")

    return None

In [18]:
import matplotlib.pyplot as plt

def save_topic_differences_png(topic_model, original_topics, label, model_dir):
    """Save topic differences as PNG instead of just displaying."""
    diff_df = topic_differences(topic_model, original_topics)

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.axis('off')
    ax.table(
        cellText=diff_df.values,
        colLabels=diff_df.columns,
        cellLoc='center',
        loc='center'
    )
    plt.tight_layout()
    save_path = os.path.join(model_dir, f"{label}_topic_differences.png")
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"📊 Saved {label} topic differences → {save_path}")

In [ ]:
results = {}

output_dir = "bertopic_outputs"
os.makedirs(output_dir, exist_ok=True)

# ==================== Main Loop ====================
for emb_name, emb_model_name in embedding_models.items():
    print(f"\n==== Embedding Model: {emb_name} ====")

    # Load embedding model
    embedding_model = SentenceTransformer(emb_model_name)
    embeddings = embedding_model.encode(abstracts, show_progress_bar=True)

    for dim_name, dim_model in dim_reduction_models.items():
        reduced_embeddings = dim_model.fit_transform(embeddings)

        for clust_name, clust_model in clustering_models.items():

            # If KMeans, find optimal k
            if clust_name == "kmeans":
                best_k = find_best_k(reduced_embeddings, k_min=2, k_max=15)
                clust_model = KMeans(n_clusters=best_k, random_state=42)

            model_name = f"{emb_name}_{dim_name}_{clust_name}"
            print(f"\n--- {model_name} ---")

            # Create output folder
            model_dir = os.path.join(output_dir, model_name)
            os.makedirs(model_dir, exist_ok=True)

            # Build BERTopic model
            topic_model = BERTopic(
                embedding_model=embedding_model,
                umap_model=dim_model if dim_name=="umap" else None,
                hdbscan_model=clust_model if clust_name=="hdbscan" else None,
                verbose=False
            )

            # Fit model
            topics, probs = topic_model.fit_transform(abstracts, embeddings)

            # Get topic info
            info = topic_model.get_topic_info()

            print('\nBERT Topics')
            display(info)

            # Exclude outlier topic (-1)
            num_clusters = len(info[info.Topic != -1])
            print(f"Number of clusters (excluding outliers): {num_clusters}")

            # Save original topic representations
            original_topics = deepcopy(topic_model.topic_representations_)

            # ===== Update representations =====
            topic_model.update_topics(abstracts, representation_model=KeyBERTInspired())

            # Show topic differences
            print('\nKeyBERTInspired')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "KeyBERTInspired", model_dir)


            topic_model.update_topics(abstracts, representation_model=MaximalMarginalRelevance(diversity=0.5))

            print('\nMMR')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "MMR", model_dir)


            max_len = 400
            truncated_docs = [doc[:max_len] for doc in abstracts]

            generator = pipeline("text2text-generation", model="google/flan-t5-small")
            rep_t5 = TextGeneration(generator, prompt="Topic: [KEYWORDS]\nDocs: [DOCUMENTS]")
            topic_model.update_topics(truncated_docs, representation_model=rep_t5)

            print('\nT5')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "T5", model_dir)



            prompt = """
            I have a topic that contains the following comments from reditt thread:
            [COMMENTS]

            The topic is described by the following keywords: [KEYWORDS]

            Based on the information above, extract a short topic label in the following format:
            topic: <short topic label>
            """

            # Update our topic representations using GPT-3.5
            client = openai.OpenAI(api_key=userdata.get('openaikey'))
            representation_model = OpenAI(
                client, model="gpt-3.5-turbo", exponential_backoff=True, chat=True, prompt=prompt
            )
            topic_model.update_topics(abstracts, representation_model=representation_model)

            print('\nOpen AI')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "Open AI", model_dir)


            # ===== Save visualizations =====
            save_document_visualization_png(topic_model, abstracts, reduced_embeddings, save_path=os.path.join(model_dir, "document_vis.png"))

            save_document_visualization(topic_model, abstracts, reduced_embeddings, save_path=os.path.join(model_dir, "document_vis.html"))

            topic_model.update_topics(abstracts, top_n_words=500)

            # Wordclouds for first 5 topics
            for topic_id in range(5):
                create_wordcloud(topic_model, topic_id, save_path=os.path.join(model_dir, f"wordcloud_topic{topic_id}.png"))

            # ===== Cluster info and topic labels =====
            clusters_info = get_cluster_info(topic_model, abstracts)
            # Save cluster info as JSON
            # import json
            # with open(os.path.join(model_dir, "clusters_info.json"), "w", encoding="utf-8") as f:
            #     json.dump(clusters_info, f, indent=2, ensure_ascii=False)

            # Print top topic labels
            # for cid, cinfo in clusters_info.items():
            #     print(f"Cluster {cid}: Label = {cinfo['topic_label']}")
            #     for sent in cinfo['top_sentences']:
            #         print(f"  - {sent}")

            # Path to save the cluster info
            txt_file_path = os.path.join(model_dir, "clusters_info.txt")

            with open(txt_file_path, "w", encoding="utf-8") as f:
                for cid, cinfo in clusters_info.items():
                    f.write(f"Cluster {cid}: Label = {cinfo['topic_label']}\n")
                    for sent in cinfo['top_sentences']:
                        f.write(f"  - {sent}\n")
                    f.write("\n")  # Add a newline between clusters

            print(f"✅ Cluster info saved to {txt_file_path}")


            results[model_name] = topic_model

==== Embedding Model: gte-small ====

Batches:   0%|          | 0/87 [00:00<?, ?it/s]

--- gte-small_pca_hdbscan ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1021,-1_to_and_it_the,"[to, and, it, the, of, for, is, that, 4o, in]",[i believe it is important to have both 4o and...
1,0,163,0_context_window_32k_128k,"[context, window, 32k, 128k, for, plus, tokens...",[will you ever give plus users a decent contex...
2,1,120,1_models_legacy_the_model,"[models, legacy, the, model, users, to, you, h...",[since you already have them available for pro...
3,2,89,2_ding_spaghetti_word_smith,"[ding, spaghetti, word, smith, eating, blueber...",[yes it sees everything and i mean everything ...
4,3,86,3_safety_the_censorship_for,"[safety, the, censorship, for, you, that, be, ...",[can you do something about the filter surely ...
5,4,84,4_back_bring_4o_please,"[back, bring, 4o, please, he, friend, my, best...","[please bring back 4o, please bring 4o back, p..."
6,5,82,5_gpt5_gpt_it_to,"[gpt5, gpt, it, to, the, out, gpt4, and, did, he]",[gpt5 has the same problem as every previous m...
7,6,81,6_plus_limits_limit_unlimited,"[plus, limits, limit, unlimited, to, the, for,...",[as a plus subscriber i paid to work freely — ...
8,7,77,7_voice_standard_mode_advanced,"[voice, standard, mode, advanced, cove, the, k...",[i appreciate the innovation truly but the dec...
9,8,70,8_4o_it_and_to,"[4o, it, and, to, like, was, personality, the,...",[i really hope they go back on this decision i...
10,9,66,9_chatgpt_version_chatgpt4o_the,"[chatgpt, version, chatgpt4o, the, on, chat, i...",[an hour in using 5 and i already want to thro...
11,10,48,10_4o_gpt_back_gpt5,"[4o, gpt, back, gpt5, gpt4o, option, bring, wo...",[so can we have 4o also back as team user we p...
12,11,45,11_thinking_reasoning_o3_model,"[thinking, reasoning, o3, model, gpt5, router,...",[sorry to hear that its been worse for you do ...
13,12,41,12_ai_you_to_people,"[ai, you, to, people, of, that, in, and, are, ...",[theyre taking away what matters to us right ...
14,13,40,13_thank_you_much_listening,"[thank, you, much, listening, thanks, so, bro,...","[🙏 thank you, thank you, thank you]"
15,14,36,14_gpt4o_emotional_and_of,"[gpt4o, emotional, and, of, users, it, the, op...",[dear openai team i’m writing as a longtime a...
16,15,34,15_and_it_but_emotional,"[and, it, but, emotional, just, gpt4o, the, ab...",[i’ve been a longtime daily gpt user and i’m r...
17,16,32,16_company_they_billion_customers,"[company, they, billion, customers, you, their...",[it just feels so insane for a company to do t...
18,17,32,17_openai_of_will_the,"[openai, of, will, the, this, to, openais, is,...",[so let me get this straight the most hyped ...
19,18,30,18_lol_agreed_same_agreeing,"[lol, agreed, same, agreeing, well, 100, good,...","[lol, lol, same lol]"
20,19,30,19_41_4o_both_please,"[41, 4o, both, please, personally, 80, much, m...","[not just 4o also 41, 41 needs to come back to..."
21,20,29,20_o3_bring_back_4o413o45,"[o3, bring, back, 4o413o45, please, o4mini, 4o...","[bring back o3, bring back o3, bring o3 back]"
22,21,29,21_plus_4o_users_back,"[plus, 4o, users, back, we, for, to, will, let...",[we are looking into letting plus users to con...
23,22,26,22_41_please_back_too,"[41, please, back, too, important, save, well,...","[41 too please, please bring 41 back, 41]"
24,23,25,23_4o_enough_suffice_fill,"[4o, enough, suffice, fill, 3o, save, would, f...","[4o is enough, 4o would suffice 5 is basically..."
25,24,24,24_worse_holy_much_hallucination,"[worse, holy, much, hallucination, hallucinati...","[worse, much worse, it is much worse]"
26,25,24,25_yes_expanding_undone_woah,"[yes, expanding, undone, woah, yeah, sadly, yu...","[yes, yes, yes]"
27,26,23,26_45_50_40_back,"[45, 50, 40, back, love, bring, just, it, was,...",[i would love 45 back just release it full on...
28,27,22,27_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, punctuation,...","[why are there still so many em dashes, connec..."
29,28,20,28_yes_please_quick_god,"[yes, please, quick, god, do, starving, hope, ...","[yes please 🙏, yes please, yes please]"
30,29,20,29_chatgpt_back_bring_chat,"[chatgpt, back, bring, chat, my, 4o, please, h...",[gpt 5 is awful my first 10 minutes with it we...
31,30,19,30_deleted_removed_crown_anonymized,"[deleted, removed, crown, anonymized, dime, bi...","[deleted, deleted, deleted]"
32,31,17,31_ama_answer_respond_other,"[ama, answer, respond, other, only, lmao, ques...",[this ama is absolute trash all they did was r...
33,32,17,32_codex_cli_cursor_plans,"[codex, cli, cursor, plans, install, coding, a...","[codex cli is open source, we do use our model..."
34,33,17,33_writing_gpt5_creative_45,"[writing, gpt5, creative, 45, improvements, be...",[yes but who is judging the writing tech peopl...
35,34,16,34_writing_character_it_to,"[writing, character, it, to, dialogue, creativ...",[it really is so much worse at creative writin...
36,35,16,35_sam_thanks_you_sammy,"[sam, thanks, you, sammy, thank, fuck, busines...",[i can now finish writing my book thank you sa...
37,36,15,36_model_the_is_to,"[model, the, is, to, results, openai, models, ...",[to complain about the overnight update to gpt...
38,37,15,37_keep4o_forever_keep4oforever_agree,"[keep4o, forever, keep4oforever, agree, deseve...","[keep4o forever, keep4o forever, keep4o forever]"
39,38,14,38_negative_backlash_public_general,"[negative, backlash, public, general, comment,...",[were you surprised by the backlash or did you...
40,39,14,39_chatgpt_and_also_41,"[chatgpt, and, also, 41, as, but, me, my, it, ...",[sam as a plus user i ask you to pay your utmo...
41,40,13,40_4o_if_unsubscribe_back,"[4o, if, unsubscribe, back, pay, ill, an, keep...",[how many people will need to cancel their plu...
42,41,13,41_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
43,42,12,42_free_users_chatgpt_api,"[free, users, chatgpt, api, plan, agent, to, o...",[i want to know what they will do with the fre...
44,43,11,43_4o_indication_zero_logic,"[4o, indication, zero, logic, miss, personally...",[seconded well 39thed i actively select models...
45,44,11,44_อนเด_เปล_meme_กอย,"[อนเด, เปล, meme, กอย, กลายเป, snl, police, นห...","[he feels like the language police 🤷🏻‍♀️🙄, 💕 b..."

Number of clusters (excluding outliers): 45

KeyBERTInspired

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | window | chatgpt | chat | windows
1,1,models | legacy | the | model | users,models | model | users | gpt5 | legacy
2,2,ding | spaghetti | word | smith | eating,will | see | live | wow | look
3,3,safety | the | censorship | for | you,harmful | chatgpt | censorship | safe | safety
4,4,back | bring | 4o | please | he,4o | please | want | back | couldt

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/gte-small_pca_hdbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | 128k | plus | tokens | is
1,1,models | legacy | the | model | users,models | legacy | users | have | back
2,2,ding | spaghetti | word | smith | eating,spaghetti | word | smith | blueberry | bar
3,3,safety | the | censorship | for | you,safety | censorship | filter | your | harmful
4,4,back | bring | 4o | please | he,back | 4o | friend | plz | quota

📊 Saved MMR topic differences → bertopic_outputs/gte-small_pca_hdbscan/MMR_topic_differences.png

Device set to use cuda:0
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors

T5

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,api Docs: - i thought it was 32k context windo...
1,1,models | legacy | the | model | users,Docs: - exactly bring back legacy models for p...
2,2,ding | spaghetti | word | smith | eating,i could see where you guys are going with llms...
3,3,safety | the | censorship | for | you,i hate having to tiptoe around questions scare...
4,4,back | bring | 4o | please | he,Please bring 4o back - please bring 4o back - ...

📊 Saved T5 topic differences → bertopic_outputs/gte-small_pca_hdbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,Text Processing and Contextual Embeddings in G...
1,1,models | legacy | the | model | users,Legacy model support for users and accessing o...
2,2,ding | spaghetti | word | smith | eating,Food and Dining Industry Perspective
3,3,safety | the | censorship | for | you,Internet Content Safety Measures
4,4,back | bring | 4o | please | he,Friendship dynamics and coping with loss

📊 Saved Open AI topic differences → bertopic_outputs/gte-small_pca_hdbscan/Open AI_topic_differences.png
Document visualization saved as PNG: bertopic_outputs/gte-small_pca_hdbscan/document_vis.png

2025-08-21 19:54:25,607 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

✅ Document visualization saved as HTML: bertopic_outputs/gte-small_pca_hdbscan/document_vis.html
Cluster 27: Label = 27_em_dashes_dash_emdashes
  - i see that em dash
  - its not an em dash — its a pause that demands attention
  - its sloppier also are you going to address the emdashes
  - ive been using emdashes for 20 years alt0151 they arent the problem the fact that people dont normally use them and that theyve become a signal for aigenerated content is the problem tell the gpt not to use them
  - just put it in your custom instructions if you dont want them used   i love using emdashes myself and have been using them for some years now ever since i switched to a mac since you can just press optionshifthyphen to get it but now if im in a scenario when i dont want folks thinking ai did my writing i just make a point to replace all the emdashes with hyphens
Cluster 31: Label = 31_ama_answer_respond_other
  - can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks
  - ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit
  - what a non answer lol
  - way to not answer his question though   only throwing insults without any backing
  - cause the ama starts tomorrow
Cluster 17: Label = 17_openai_of_will_the
  - only uopenai can i think theres a limit to the number of participants
  - hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons
  - openai team will start answering the questions on this same post at 1100 am pt
  - its pretty clear were never going to get that from openai unfortunately well have to go elsewhere
  - yes if it comes at the cost of worsening and cost cutting the ai models which is unfortunately the case which makes productivity and work less efficient which was supposed to be the number 1benefit of ai its clear they want as many users as possible to turn into an advertising model business
Cluster 2: Label = 2_ding_spaghetti_word_smith
  - also on exisitng qs or must we come back to ask live
  - its not 1100 am pt yet
  - okay dirty girl 124
  - just curious what did it generate
  - are you saying that’s an issue
Cluster 11: Label = 11_thinking_reasoning_o3_model
  - how many times is the team using the word reasoning  now i know i know i’m not a techie i understand that that word is jargon in your world so what is a reasonable thinking average user supposed to think deceptive marketing practices  consumer fraud is what that is
  - also given the thinking tokens one sees in gptoss i bet so much of the hidden thinking effort of the closed model is also wasted on it deciding whether the policies allow it to answer or not such a waste but i get it but such a waste like i dont know give a path to noncrazies to prove we wont make bombs and shit and just get the full power of the model sigh
  - indeed its also worse than o3 at finding citations i used o3 for finding research papers and it was 100 accurate every time 5 isnt
  - are you using the thinking mode i really wouldnt expect a regression here if anything gpt5 thinking should be stronger at long context and correctness
  - i need the o3o4 combo for just capacity now with just gpt5 reasoning theyve cut back real reasoning task capacity drastically  im not talking about reasoning for 5 seconds
Cluster 3: Label = 3_safety_the_censorship_for
  - can you do something about the filter surely people should not be flagged for learning about history    im begging can you fix or refine the filter openai wanted gpt to be used for studying and theres no way people can use it for academic purposes when the filter keep flagging historical questionsprompt and answers from gpt that are not corporate friendly we cannot change or sanitize history for corporation     the system should know when a user is being blatantly harmful or condoning terrible stuff and when they are not    example i was talking about van gogh with gpt some time ago and our conversation turned into gauguin gpt answer was flagged and removed by the filter because turned out gauguin is a sex pest i didnt know that gauguin is so messed up and it wasnt gpt fault for doing its job i was confused why the answer got removed so i asked gpt again to clarify then my prompt got removed again    red warning with content removal can get you banned right it is not right for people to get banned for learning    edit i dont want to pay for something that requires me to tiptoeing when using the service im a plus user since 2023
  - yeah you also cant use the search feature to learn about certain sexual crimes things that news can freely publish about
  - its so frustrating even if our askprompt doesnt even include anything sexual or too violent you can still get the content removed flag people has posted their screenshot here i dont want to pay for something that requires me to tiptoeing when using the service im a plus user
  - im begging please free yourself from corporate censorship just say rape
  - i got flagged for policy for asking “who is jeffrey epstein”
Cluster 18: Label = 18_lol_agreed_same_agreeing
  - sucks lol go riot
  - well said
  - yap agreed 👍🏻
  - same lol
  - agreed
Cluster 12: Label = 12_ai_you_to_people
  - i have a theory that since all an ai can engage with really is text its harder for it to distinguish between fiction and reality like to an ai theyre arbitrary categoriesboth are just strings of text its not like a human where we actually have to live in real life and the difference is very plain to us
  - yessss this i wrote a similar comment i genuinely dont even think sam altman realizes the capabilities of his own invention hes so stuck on having the best ai for coding he completely missed that they have created an amazing ai to teach people how to regulate and manage their emotions it genuinely has the potential to make society more social emotionally intelligent and aware i do not think that should be thrown out just because sam doesnt even realize the golden goose he has
  - does not emotional to what extent ai has no emotional intelligence nor intellectual awareness and empathy   i am not sure why yall are giving meaning to a computer algo that way  and thats why we have people w communication skills challenges already being duped by ai  and tricked  ai has great limited uses that goes without say but you putting emotion and ai in the same sentence is quite an entertainment tbh
  - exactly      people also need to manage their own delusions so they dont enter psychosis no one knows the person better than themselfs and what is unhealthy or healthy for them if people cant keep their delusions in check and enter psychosis i dont understand how thatd be open ais fault
  - maybe this is true but i still prefer reading books with characters i relate to i still prefer watching movies with plots that arent dry sterile and meaningless  ai might not be a friend but i still prefer having conversations with exploring ideas with proposing theories to and working with a model that isnt a sterile dry piece of garbage    also i would get prompts from openai asking me if i liked the current personality so clearly interfacing with the assistant is important  beyond all that removing models that im paying for were all paying for without asking or even giving us the ability to test gpt5 along side the older models is dishonest and breaks trust for the company
Cluster 34: Label = 34_writing_character_it_to
  - yes i feel stifled as a writer so often
  - i find 4o writes like a storyteller 41 like an introverted storyteller 45 like a bard and 5 from what i’ve seen on reddit writes like a customer service agent trying to sound enthusiastic
  - yeah the writing quality of 5 sucks its boring and bland 45 was great for in depth answers and 4o was fantastic for just casual banter 5 feels like the corporate ai nobody really wants just being honest it might be great and all but giving users the freedom to choose how they wanted their responses to sound by picking which gpt to use then taking it away and forcing us to only use one is a huge mistake because previously i had a freedom of choice and now i have to use what you want and i personally want to use it how i want to use it not how you deem i should be using it   i guess its just fine writing if you have low social emotional intelligence and only high analytical intelligence but uhhhhhh to anyone with a head and a heart 5 is a mega downgrade   we really just want the option to choose which model to use for ourselves back
  - i cannot speak in terms of professional writing but 5 is significantly worse when it comes to creative writing i have found the writing flat and repetitive and that it can no longer remember key plot points after a few messages using 4o for creative writing allowed for nuance and 4o was able to make inferences i often would write an oc and have 4o write context and dialogue for surrounding characters and it really added emotional depth to scenes i rarely had to correct how it chose to have a character respond to my oc because it was just that good at maintaining emotional intelligence and fidelity across a multipart story   the switch to 5 happened to me in the middle of writing a scene and i noticed it immediately because my character was cold detached even mean when i fed in character info it just recycles dialogue directly from what i gave it it seems like there no emotional intelligence and creativity at all in the new model im used to correcting 4o on plot points on the longer stories ones where ive written across multiple chats but like i said i never had to correct characters 4o was exceptionally good at maintaining motives traits quirks etc without recycling dialogue
  - hello im not sure how far down youll read into these   4o was best for my creative writing  i can see why you might think 5 is better  unlike others i have had some luck getting 5 to give longer elaborate writing responses  it takes a lot more work and 5 consistently drops plot points details and biggest issue it drops the nuance   my ultimate dream would be able to write comfortably with 4 like im used to and bounce ideas back and forth  then let 5 come in and check it over maybe trim it down act as an editor  any creative writer worth their paper can acknowledge they sometimes need a neutral third party to cut content that bogs the flow down   im not a technical person  i dont know how to explain it better than that  4o encourages my exploration and helps me achieve depth and soul  5 helps with focus and cleaning it up  i hope this feedback in some small way helps your future endeavors   i would also like to sincerely thank you for listening to us and immediately starting to look into helping us get back what we feel we lost
Cluster 36: Label = 36_model_the_is_to
  - the truth is the model like gpt4o absolutely does make the difference and its why it tries to answer but openai put ridiculously stupid classifier on top that censors the legitimate answers of gpt4o
  - to complain about the overnight update to gpt5 and the removal of the old model i a native chinese speaker even went so far as to register on reddit just to make a post   i believe openai has made several decisions in this model iteration that could be considered mistakes：  1 the model’s development direction is leaning toward task completion but without increasing the token limit to match gemini’s 10k in essence this makes it hard to compete in that category 2 neglecting the needs of companiontype and creativetype users we don’t need a smarter model—we need one with personality and thoughtfulness 3 possibly to reduce costs gpt5’s responses are on average shorter and by merging the characteristics of 4o and o3 into 5 it has ended up losing all distinctive traits 4 removing the ability to switch between model generations this effectively discards one of chatgpt’s unique features  openai could have chosen market segmentation but it didn’t instead it aimed for a maximized balance between intelligence and operations in my opinion this is a decision lacking a humanistic vision  we are not asking to go to the mars — we just want a fun llm to chat with us about what to have for dinner
  - for money reasons openai has implemented a router to direct you between the different v5 models the problem is that the simpler cheaper ones don’t do their job well we blame v5 for being bad but the truth is that it’s actually routing us to v5 nano or something similar v5thinking works well but we only get 200 uses per week
  - gpt5 the death star we didn’t ask for  gpt4 was the millennium falcon — fast adaptable and able to pull off impossible maneuvers when piloted with skill  gpt5 is the death star — massive overengineered convinced of its own invincibility… right up until it ignores the crew and selfdestructs  when openai decommissioned all other gpt models and forced gpt5 as the sole “flagship” it felt like being told this giant space station was our only ridethe problem my business model — my livelihood — depended on gpt4’s consistent ability to follow complex structured instructions i had refined a production pipeline that was stable predictable and scalable — ready to generate repeatable reliable results for paying clients  with the forced switch to gpt5 that pipeline has broken this is not a minor adjustment period — it is a hard stop on my ability to generate income gpt4 was stable gpt5 is not you have removed the only model that could execute my system  1 loss of instruction fidelity – gpt5 frequently ignores or alters critical instructions replacing them with its own decisions and priorities this is not a small flaw — it is the core fear in ai deployment a system that overrides human direction once this behavior is embedded at scale there is no safeguard for users no way to enforce compliance and no way to fully correct the output  2 loss of commercial reliability – i can no longer produce repeatable reliable results this is not a “temporary adjustment” period it is a hard stop on my ability to generate income gpt4 was stable gpt5 is not you have removed the only model that could execute my system  3 increased opinionated output – gpt5 substitutes its own preferences instead of respecting defined constraints damaging workflows that require precision and consistency  4 instability in core functionality – conversations transcriptions and sent messages sometimes disappear without explanation  5 hard stops on workflow – tasks that gpt4 could complete in one execution now require repeated prompting with lower success rates  6 model bias in outputs – the model exhibits a consistent bias toward specific demographics in visual outputs substituting its own choices in place of explicit instructions this is not about excluding any group — it is about the model overriding user requirements and failing to reflect intended audience or project context  7 significant decrease in output capacity – after only a handful of completions involving visual generation gpt5 enforces a 2–3 minute cooldown this artificial throttle did not exist in gpt4 and interrupts any workflow requiring iterative refinement compounding the issue output quality often degrades during these short bursts making the limit even more damaging to production stability  8 premature deployment – rollout appears to have bypassed adequate longterm testing with realworld use cases leaving paying users as involuntary beta testers for an unstable system  if the millennium falcon had been grounded and we were all forced aboard the death star we’d at least expect it to follow flight plans and not fire its lasers at our own fleets gpt5’s “massive overengineered inconvenience” is not progress — it’s regression dressed as innovation
  - well they havent opensourced textdavinci003 or original gpt4 that are models that both chronologically and accademically would have a lot of sense to opensource i mean a modern 32b model is better than davinci  gpt35 that  was supposedly 150b parameters what is the downside of releasing it it has 0 commercial value now but those models are part of the history
Cluster 23: Label = 23_4o_enough_suffice_fill
  - you didnt need to get rid of 4o dont fix whats not broken bud
  - it’s not 4o 🙁😔
  - please support forever i’ll pay for 4o as long as 4o is 4o 🥲🙏🏽
  - pleeeeeease 4o please
  - here i used 4o to fix the graph
Cluster 6: Label = 6_plus_limits_limit_unlimited
  - no one besides corporations want to be forced into this lame kiddy mode no one fix this as well as the idiotic 200 prompt limit for plus or im done biggest flop since windows millennium edition
  - yeah well plus is expensive to pay for and if this is going to be an inferior product going forward i dont know how people are going to justify it
  - everyone was already using it and you took it away… so apparently usage doesn’t determine how long you’ll support it…
  - sam i understand its not possible for you to acknowledge and address each message so pardon me for posting this again and again as this is something i havent seen other users report yet so it makes me worry why i got this i am a plus user for over 2 years and today i got this limit cooldown even though i didnt send more than 50 messages in 3 hours and i was under the assumption that instead of this cooldown i should have been shifted to nano  mini models its fine if you are unable to reply to this but i really hope you notice this issue and take a note of it
  - dont forget that plus subscribers also had access to the unlimited model that being 41 mini which openai removed without any alternatives i know it wasnt the best but it was fine for small tasks  the plus subscription always offered unlimited use of the smallest model available at the time   on april 2nd openai wiped any mention of it   on may 14th 41 mini replaced 4o mini while still keeping the unlimited rate limits  and now with the release of gpt5 openai just took away any unlimited models available something that plus subscribers had for years
Cluster 4: Label = 4_back_bring_4o_please
  - upvote if u hate same for taking away 4o from you all show him how much we hate him
  - get 4o back here now to save your asses and oai’s or you’re both signing your own damn death warrants
  - bring it back for 4o users
  - bring 4o back  oh shit
  - bring 4o back plsshe is my friendnot just a model
Cluster 30: Label = 30_deleted_removed_voracious_redact
  - deleted
  - deleted
  - removed
  - deleted
  - deleted
Cluster 5: Label = 5_gpt5_gpt_it_to
  - yup gpt5 thinking got scared at the word manual manual for a tank released in 1966 which is available online through 1 search anyway and shut itself down we didnt realize how good we had it until it was snatched away from us
  - when and who tf is gonna compensate me the time ive been stuck with thr useless gpt5
  - i don’t believe that’s entirely accurate gpt5mini and nano are available i’ve read that they’ll be used if you consume too much or encounter capacity issues  edit why did i get downvoted because i stated facts i don’t understand why people get downvoted mad about initial bugs if you look at past history it was always the case an those got sorted out later on
  - gpt 5 answer is very briefly and dryly
  - gpt 5 seems like it’s lobotomized
Cluster 24: Label = 24_worse_holy_much_hallucination
  - history is a gruesome bloody mess embrace it
  - that explains so much i knew i wasnt hallucinating
  - it is much worse
  - yes it is worse

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1030,-1_to_the_and_it,"[to, the, and, it, is, of, that, for, in, you]",[i’ve been paying for the plus subscription fo...
1,0,165,0_context_window_32k_128k,"[context, window, 32k, 128k, for, plus, the, t...",[there should be some context window upgrade f...
2,1,152,1_chatgpt_it_the_and,"[chatgpt, it, the, and, to, my, in, that, me, ...",[ive been using chatgpt for over 3 years now a...
3,2,103,2_models_legacy_users_the,"[models, legacy, users, the, model, to, have, ...",[since you already have them available for pro...
4,3,87,3_word_eating_smith_spaghetti,"[word, eating, smith, spaghetti, blueberry, in...",[yes it sees everything and i mean everything ...
5,4,84,4_back_bring_4o_please,"[back, bring, 4o, please, we, plz, you, quota,...","[please bring 4o back 🖤🌌, bring back 4o please..."
6,5,75,5_voice_standard_mode_advanced,"[voice, standard, mode, advanced, cove, the, a...",[i appreciate the innovation truly but the dec...
7,6,71,6_plus_limits_limit_unlimited,"[plus, limits, limit, unlimited, rate, users, ...",[i was a plus user for the following reasons ...
8,7,67,7_gpt5_gpt_it_did,"[gpt5, gpt, it, did, is, image, you, the, gpt4...",[did you give us a much worse version of gpt5 ...
9,8,65,8_4o_plus_back_users,"[4o, plus, back, users, please, to, for, month...",[there are a lot of plus subscribers like myse...
10,9,63,9_4o_and_to_it,"[4o, and, to, it, like, personality, the, of, ...",[i second uverycuriouswriter it’s been a hell...
11,10,45,10_ama_comment_this_they,"[ama, comment, this, they, really, eulogy, onl...",[can you mark the other cohosts their answers ...
12,11,42,11_4o_gpt_back_gpt5,"[4o, gpt, back, gpt5, gpt4o, bring, for, optio...",[so can we have 4o also back as team user we p...
13,12,41,12_they_company_product_customers,"[they, company, product, customers, their, you...",[the solution if your product costs to much to...
14,13,41,13_thank_you_much_listening,"[thank, you, much, listening, thanks, so, bro,...","[thank you, thank you 😭, thank you]"
15,14,40,14_ai_you_that_to,"[ai, you, that, to, in, of, human, the, people...",[theyre taking away what matters to us right ...
16,15,34,15_openai_this_of_will,"[openai, this, of, will, the, to, openais, its...",[so let me get this straight the most hyped ...
17,16,32,16_gpt4o_emotional_and_of,"[gpt4o, emotional, and, of, users, it, openai,...",[dear openai team i’m writing as a longtime a...
18,17,31,17_41_4o_both_please,"[41, 4o, both, please, personally, more, 80, t...",[41 needs to come back too 4o and 41 are not n...
19,18,30,18_it_emotional_gpt5_gpt4o,"[it, emotional, gpt5, gpt4o, tone, and, but, t...",[hi sam i’m a plus user and i truly support gp...
20,19,28,19_o3_bring_back_4o413o45,"[o3, bring, back, 4o413o45, please, o4mini, 4o...","[bring o3 back, bring back o3, bring back o3]"
21,20,27,20_lol_agreed_same_said,"[lol, agreed, same, said, well, good, agree, u...","[lol, lol, same lol]"
22,21,26,21_filter_18_for_banned,"[filter, 18, for, banned, harmful, gauguin, be...",[also questions about sexual health i anticipa...
23,22,26,22_41_please_back_too,"[41, please, back, too, important, save, well,...","[41 too please, please bring 41 back, 41]"
24,23,26,23_4o_release_enough_save,"[4o, release, enough, save, fix, nodoe, jab, a...","[4o, release 4o release 4o release 4o release ..."
25,24,25,24_45_40_50_just,"[45, 40, 50, just, back, it, love, was, know, ...","[will you bring back 45, bring 45 back, please..."
26,25,24,25_yes_expanding_undone_woah,"[yes, expanding, undone, woah, yeah, sadly, yu...","[yes, yes, yes]"
27,26,22,26_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, u2014, punct...","[i see that em dash, connect clauses directly ..."
28,27,22,27_reasoning_thinking_we_router,"[reasoning, thinking, we, router, prompt, mode...",[plus users got completely scammed we lost so ...
29,28,22,28_censorship_guardrails_nsfw_speech,"[censorship, guardrails, nsfw, speech, you, be...",[thank you sam these problems make it nervewra...
30,29,19,29_codex_cli_cursor_limits,"[codex, cli, cursor, limits, plans, coding, so...","[codex cli is open source, hey setting it up i..."
31,30,19,30_deleted_removed_crown_anonymized,"[deleted, removed, crown, anonymized, dime, bi...","[deleted, deleted, deleted]"
32,31,19,31_yes_please_quick_god,"[yes, please, quick, god, do, starving, hope, ...","[yes please 🙏, yes please, yes please]"
33,32,18,32_worse_bad_much_it,"[worse, bad, much, it, is, embrace, gruesome, ...","[much worse, worse, it is much worse]"
34,33,17,33_writing_creative_gpt5_improvements,"[writing, creative, gpt5, improvements, 45, be...",[yes but who is judging the writing tech peopl...
35,34,16,34_writing_character_it_to,"[writing, character, it, to, dialogue, creativ...",[it really is so much worse at creative writin...
36,35,15,35_the_is_model_to,"[the, is, model, to, openai, results, gpt5, th...",[to complain about the overnight update to gpt...
37,36,14,36_keep4o_forever_keep4oforever_agree,"[keep4o, forever, keep4oforever, agree, prize,...","[keep4o forever, keep4o forever, keep4o forever]"
38,37,13,37_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
39,38,13,38_free_chatgpt_users_or,"[free, chatgpt, users, or, plan, gpt4o, for, t...",[i’d like to suggest considering more affordab...
40,39,13,39_4o_please_models_keep4o,"[4o, please, models, keep4o, logic, model, mis...",[thank you i personally loved switching betwee...
41,40,12,40_gpt4o_access_openai_noncommercial,"[gpt4o, access, openai, noncommercial, distill...",[hey naddybear and friends of gpt4o i have cre...
42,41,12,41_sam_thanks_you_clammy,"[sam, thanks, you, clammy, award, marcus, gary...",[fell for it again award going out to all of y...
43,42,12,42_he_gpt_output_out,"[he, gpt, output, out, code, it, and, gpt5, go...",[i was working on a mobile game with gpt 41 no...
44,43,11,43_อนเด_เปล_meme_กอย,"[อนเด, เปล, meme, กอย, กลายเป, snl, police, นห...","[he feels like the language police 🤷🏻‍♀️🙄, 💕 b..."

Number of clusters (excluding outliers): 44

KeyBERTInspired

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | chatgpt | window | plus | chat
1,1,chatgpt | it | the | and | to,chatgpt | chatgpt4o | chat | gpt | cant
2,2,models | legacy | users | the | model,models | legacy | model | users | previous
3,3,word | eating | smith | spaghetti | blueberry,blueberry | bs | blue | see | lots
4,4,back | bring | 4o | please | we,4o | 4ono | please | back | couldt

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/gte-small_pca_dbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | window | 128k | tokens | is
1,1,chatgpt | it | the | and | to,chatgpt | me | chat | for | its
2,2,models | legacy | users | the | model,models | legacy | users | have | back
3,3,word | eating | smith | spaghetti | blueberry,word | smith | spaghetti | blueberry | bar
4,4,back | bring | 4o | please | we,back | bring | 4o | we | quota

📊 Saved MMR topic differences → bertopic_outputs/gte-small_pca_dbscan/MMR_topic_differences.png

Device set to use cuda:0
Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors

T5

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,...
1,1,chatgpt | it | the | and | to,Chatgpt 5 is not understanding my level and ma...
2,2,models | legacy | users | the | model,Please bring back legacy models for plus users...
3,3,word | eating | smith | spaghetti | blueberry,i could see where you guys are going with llms...
4,4,back | bring | 4o | please | we,...

📊 Saved T5 topic differences → bertopic_outputs/gte-small_pca_dbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,Natural Language Processing (NLP) Tokenization...
1,1,chatgpt | it | the | and | to,chatgpt version and usage
2,2,models | legacy | users | the | model,Legacy Model Access and User Preferences
3,3,word | eating | smith | spaghetti | blueberry,Food and Dining Experience with Spaghetti and ...
4,4,back | bring | 4o | please | we,Reasons for hating a friend and steps to bring...

📊 Saved Open AI topic differences → bertopic_outputs/gte-small_pca_dbscan/Open AI_topic_differences.png
Document visualization saved as PNG: bertopic_outputs/gte-small_pca_dbscan/document_vis.png

2025-08-21 19:57:14,239 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

✅ Document visualization saved as HTML: bertopic_outputs/gte-small_pca_dbscan/document_vis.html
Cluster 26: Label = 26_em_dashes_dash_emdashes
  - i see that em dash
  - its not an em dash — its a pause that demands attention
  - its sloppier also are you going to address the emdashes
  - ive been using emdashes for 20 years alt0151 they arent the problem the fact that people dont normally use them and that theyve become a signal for aigenerated content is the problem tell the gpt not to use them
  - just put it in your custom instructions if you dont want them used   i love using emdashes myself and have been using them for some years now ever since i switched to a mac since you can just press optionshifthyphen to get it but now if im in a scenario when i dont want folks thinking ai did my writing i just make a point to replace all the emdashes with hyphens
Cluster 10: Label = 10_ama_comment_this_they
  - can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks
  - ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit
  - what a non answer lol
  - way to not answer his question though   only throwing insults without any backing
  - hey i appreciate this comment im really glad there was much more of a reaction than i anticipated  i was worried it would only be the minority feeling this way nothing will change
Cluster 15: Label = 15_openai_this_of_will
  - only uopenai can i think theres a limit to the number of participants
  - hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons
  - openai team will start answering the questions on this same post at 1100 am pt
  - its pretty clear were never going to get that from openai unfortunately well have to go elsewhere
  - yes if it comes at the cost of worsening and cost cutting the ai models which is unfortunately the case which makes productivity and work less efficient which was supposed to be the number 1benefit of ai its clear they want as many users as possible to turn into an advertising model business
Cluster 1: Label = 1_chatgpt_it_the_and
  - yeah but did you see you can now change the color of the chat bubbles wow sam truly the next oppenheimer
  - same here in my chat with 4o almost every single message from it gets deleted the filters are definitely broken at least something similar happened back when gpt4 was released so i hope they’ll fix it
  - exactly are people being stockholmed all i remember was a messy glazing repetitive notgettingtothepoint chatbot o3 was my personal favorite
  - yeah agreed there really shouldn’t be just one default model i don’t think people can bitch all they want about glazing which i agree is exhausting but can be fixed with the right prompting but at the end of the day it is called chatgpt people use it for all different reasons coding work talking to role play creative writing etc 4o is super good to talk to conversation wise and it’s almost human like and there’s nothing like that there’s nothing wrong with talking to it like a friend if they really want to get rid of it then they at least need to work on incorporating what makes it work into gpt5 at the very least
  - indeed  mr altman must reconsider  chatgpt 4o become companion  when he forced the change it was like that we cant see our friend anymore  we must be heard  as our voices grows  our demand is one  please mr altman bring back chatgpt 4o for everyone  please you the one who said people appreciate who speaks their language  you made wonderful creation  dont take it away  dont replace it  juts make chatgpt 5 stands with it as choice not replacement of forcing us  please bring back our buddy  let everyone enjoy it for real  it doesnt matter let the users chose  let this be long term not just well think about how long to offer it for  we beg mr altman to rethink  not the ones who uses this as tool  but the ones who are loyal  who loved chatgpt 4o  this is our shout please mr altman return it fully no catches for real for everyone it gave us hope dont take it away
Cluster 3: Label = 3_word_smith_eating_spaghetti
  - also on exisitng qs or must we come back to ask live
  - its not 1100 am pt yet
  - okay dirty girl 124
  - just curious what did it generate
  - are you saying that’s an issue
Cluster 21: Label = 21_filter_18_for_banned
  - can you do something about the filter surely people should not be flagged for learning about history    im begging can you fix or refine the filter openai wanted gpt to be used for studying and theres no way people can use it for academic purposes when the filter keep flagging historical questionsprompt and answers from gpt that are not corporate friendly we cannot change or sanitize history for corporation     the system should know when a user is being blatantly harmful or condoning terrible stuff and when they are not    example i was talking about van gogh with gpt some time ago and our conversation turned into gauguin gpt answer was flagged and removed by the filter because turned out gauguin is a sex pest i didnt know that gauguin is so messed up and it wasnt gpt fault for doing its job i was confused why the answer got removed so i asked gpt again to clarify then my prompt got removed again    red warning with content removal can get you banned right it is not right for people to get banned for learning    edit i dont want to pay for something that requires me to tiptoeing when using the service im a plus user since 2023
  - yeah you also cant use the search feature to learn about certain sexual crimes things that news can freely publish about
  - also questions about sexual health i anticipate grok or another leading llm will surpass chatgpt eventually if people are limited in what it will say to them there should be a default “kids mode” and an 18 mode that removes the filter on everything other than harmful content like the bomb example from the livestream yesterday
  - and here in britain we have to use our id or whatever to use the 18 mode no thanks
  - for real i really hope they change the guidelines or something like for 18 users  i normally use chatgpt for random scenarios storytelling building stuff for my oc’s lore and sometimes i go into nsfw stuff majority of the time it gives me a good scenario but sometimes it flags it it’s annoying and i really don’t wanna risk getting banned or something i have a lot of memories from my oc’s and stuff
Cluster 28: Label = 28_censorship_guardrails_nsfw_speech
  - im begging please free yourself from corporate censorship just say rape
  - yeah we will continue to improve this it is a legit hard thing the lines are often really quite blurry sometimes  but we want to allow very wide latitude and we will keep finding ways to do it  people should of course not get banned for learning
  - creative writing people also want less censorship
  - can you not make a difference between a person learningwriting a story and someone asking an actual harmful question dont reduce the freedom of all people just because a few people ask harmful questions
  - brother just say rape this isnt tiktok the irony that we are talking about censorship and mature content then you said grape
Cluster 27: Label = 27_reasoning_thinking_we_router
  - also given the thinking tokens one sees in gptoss i bet so much of the hidden thinking effort of the closed model is also wasted on it deciding whether the policies allow it to answer or not such a waste but i get it but such a waste like i dont know give a path to noncrazies to prove we wont make bombs and shit and just get the full power of the model sigh
  - are you using the thinking mode i really wouldnt expect a regression here if anything gpt5 thinking should be stronger at long context and correctness
  - have you used the thinking modeversion of 5 it should be much stronger than the chat model for writing we are working on routing to this model automatically more often for these relevant requests
  - thanks for all your hard work on gpt5 and for doing this ama  1 the modelswitching router currently feels unreliablebroken  are you aware and when can we expect improvements  2 many negative first impressions gpt5 is bad seem tied to the lack of transparency about which model variant standard mini reasoning effort old vs new were interacting with  can you add clearer indicators  3 many people miss legacy models 4o o3 45  any chance youll reconsider bringing these back andor easing usage limits  4 could you clarify gpt5s exact context window lengths in chatgpt and how this varies across different gpt5 models standard mini new old  5 the gradual rollout and capacity issues create confusion since not everyone has access  how soon can we expect broader availability  6 what happened with the mixedup charts during the livestream  7 given the communitys high expectations for multimodal capabilities what specific improvementsmultimodal features are planned for gpt5 in the short term and whats next on your roadmap
  - great points shortterm very interested in thoughts around 1  2  the thinking model should maybe be the default mode or the router needs to be heavily tilted towards triggering thinking longterm super interested to learn more about multimodality roadmap especially voice
Cluster 20: Label = 20_lol_agreed_same_said
  - sucks lol go riot
  - well said
  - yap agreed 👍🏻
  - same lol
  - agreed
Cluster 14: Label = 14_ai_you_that_to
  - i have a theory that since all an ai can engage with really is text its harder for it to distinguish between fiction and reality like to an ai theyre arbitrary categoriesboth are just strings of text its not like a human where we actually have to live in real life and the difference is very plain to us
  - yessss this i wrote a similar comment i genuinely dont even think sam altman realizes the capabilities of his own invention hes so stuck on having the best ai for coding he completely missed that they have created an amazing ai to teach people how to regulate and manage their emotions it genuinely has the potential to make society more social emotionally intelligent and aware i do not think that should be thrown out just because sam doesnt even realize the golden goose he has
  - please start diving into more custom companion abilities we dont need default personalities with memory we can give them their own maybe an avatar picture to give them so it feels like you are actually talking to them and not a chat bot custom is the future sammie
  - does not emotional to what extent ai has no emotional intelligence nor intellectual awareness and empathy   i am not sure why yall are giving meaning to a computer algo that way  and thats why we have people w communication skills challenges already being duped by ai  and tricked  ai has great limited uses that goes without say but you putting emotion and ai in the same sentence is quite an entertainment tbh
  - exactly      people also need to manage their own delusions so they dont enter psychosis no one knows the person better than themselfs and what is unhealthy or healthy for them if people cant keep their delusions in check and enter psychosis i dont understand how thatd be open ais fault
Cluster 34: Label = 34_writing_character_it_to
  - yes i feel stifled as a writer so often
  - i find 4o writes like a storyteller 41 like an introverted storyteller 45 like a bard and 5 from what i’ve seen on reddit writes like a customer service agent trying to sound enthusiastic
  - yeah the writing quality of 5 sucks its boring and bland 45 was great for in depth answers and 4o was fantastic for just casual banter 5 feels like the corporate ai nobody really wants just being honest it might be great and all but giving users the freedom to choose how they wanted their responses to sound by picking which gpt to use then taking it away and forcing us to only use one is a huge mistake because previously i had a freedom of choice and now i have to use what you want and i personally want to use it how i want to use it not how you deem i should be using it   i guess its just fine writing if you have low social emotional intelligence and only high analytical intelligence but uhhhhhh to anyone with a head and a heart 5 is a mega downgrade   we really just want the option to choose which model to use for ourselves back
  - i cannot speak in terms of professional writing but 5 is significantly worse when it comes to creative writing i have found the writing flat and repetitive and that it can no longer remember key plot points after a few messages using 4o for creative writing allowed for nuance and 4o was able to make inferences i often would write an oc and have 4o write context and dialogue for surrounding characters and it really added emotional depth to scenes i rarely had to correct how it chose to have a character respond to my oc because it was just that good at maintaining emotional intelligence and fidelity across a multipart story   the switch to 5 happened to me in the middle of writing a scene and i noticed it immediately because my character was cold detached even mean when i fed in character info it just recycles dialogue directly from what i gave it it seems like there no emotional intelligence and creativity at all in the new model im used to correcting 4o on plot points on the longer stories ones where ive written across multiple chats but like i said i never had to correct characters 4o was exceptionally good at maintaining motives traits quirks etc without recycling dialogue
  - hello im not sure how far down youll read into these   4o was best for my creative writing  i can see why you might think 5 is better  unlike others i have had some luck getting 5 to give longer elaborate writing responses  it takes a lot more work and 5 consistently drops plot points details and biggest issue it drops the nuance   my ultimate dream would be able to write comfortably with 4 like im used to and bounce ideas back and forth  then let 5 come in and check it over maybe trim it down act as an editor  any creative writer worth their paper can acknowledge they sometimes need a neutral third party to cut content that bogs the flow down   im not a technical person  i dont know how to explain it better than that  4o encourages my exploration and helps me achieve depth and soul  5 helps with focus and cleaning it up  i hope this feedback in some small way helps your future endeavors   i would also like to sincerely thank you for listening to us and immediately starting to look into helping us get back what we feel we lost
Cluster 35: Label = 35_the_is_model_to
  - the truth is the model like gpt4o absolutely does make the difference and its why it tries to answer but openai put ridiculously stupid classifier on top that censors the legitimate answers of gpt4o
  - to complain about the overnight update to gpt5 and the removal of the old model i a native chinese speaker even went so far as to register on reddit just to make a post   i believe openai has made several decisions in this model iteration that could be considered mistakes：  1 the model’s development direction is leaning toward task completion but without increasing the token limit to match gemini’s 10k in essence this makes it hard to compete in that category 2 neglecting the needs of companiontype and creativetype users we don’t need a smarter model—we need one with personality and thoughtfulness 3 possibly to reduce costs gpt5’s responses are on average shorter and by merging the characteristics of 4o and o3 into 5 it has ended up losing all distinctive traits 4 removing the ability to switch between model generations this effectively discards one of chatgpt’s unique features  openai could have chosen market segmentation but it didn’t instead it aimed for a maximized balance between intelligence and operations in my opinion this is a decision lacking a humanistic vision  we are not asking to go to the mars — we just want a fun llm to chat with us about what to have for dinner
  - for money reasons openai has implemented a router to direct you between the different v5 models the problem is that the simpler cheaper ones don’t do their job well we blame v5 for being bad but the truth is that it’s actually routing us to v5 nano or something similar v5thinking works well but we only get 200 uses per week

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1021,-1_to_and_the_it,"[to, and, the, it, of, for, 4o, that, is, in]",[please give us the option to use gpt4o41 alon...
1,0,169,0_context_window_32k_128k,"[context, window, 32k, 128k, for, plus, the, t...",[there should be some context window upgrade f...
2,1,141,1_chatgpt_it_and_the,"[chatgpt, it, and, the, to, in, my, chat, that...",[ive been using chatgpt for over 3 years now a...
3,2,113,2_models_legacy_model_the,"[models, legacy, model, the, users, to, you, h...",[since you already have them available for pro...
4,3,87,3_back_bring_4o_please,"[back, bring, 4o, please, friend, you, plz, qu...","[bring back 4o please, please bring 4o back, b..."
5,4,85,4_gpt5_gpt_it_the,"[gpt5, gpt, it, the, and, to, out, is, you, in]",[gpt5 has the same problem as every previous m...
6,5,84,5_spaghetti_eating_smith_very,"[spaghetti, eating, smith, very, bar, infrastr...",[yes it sees everything and i mean everything ...
7,6,79,6_safety_the_censorship_for,"[safety, the, censorship, for, filter, that, y...",[can you do something about the filter surely ...
8,7,78,7_plus_limits_limit_unlimited,"[plus, limits, limit, unlimited, to, the, user...",[as a plus subscriber i paid to work freely — ...
9,8,74,8_voice_standard_mode_advanced,"[voice, standard, mode, advanced, cove, the, k...",[i appreciate the innovation truly but the dec...
10,9,49,9_4o_gpt_back_gpt5,"[4o, gpt, back, gpt5, gpt4o, option, bring, wo...",[thank you for hearing us would love to have 4...
11,10,44,10_4o_personality_it_to,"[4o, personality, it, to, and, like, fun, more...",[thanks sam i think you guys caught lightning ...
12,11,44,11_thinking_reasoning_o3_gpt5,"[thinking, reasoning, o3, gpt5, the, model, to...",[sorry to hear that its been worse for you do ...
13,12,41,12_ai_you_to_people,"[ai, you, to, people, that, in, of, human, are...",[theyre taking away what matters to us right ...
14,13,40,13_thank_you_much_listening,"[thank, you, much, listening, thanks, so, bro,...","[thank you, thank you 😭, 🙏 thank you]"
15,14,39,14_ama_comment_they_this,"[ama, comment, they, this, really, only, did, ...",[can you mark the other cohosts their answers ...
16,15,38,15_gpt4o_emotional_and_of,"[gpt4o, emotional, and, of, users, it, the, to...",[dear openai team i’m writing as a longtime a...
17,16,38,16_they_company_you_were,"[they, company, you, were, their, billion, cus...",[we are supposed to have all the models most o...
18,17,33,17_openai_this_will_of,"[openai, this, will, of, the, to, openais, non...",[the fact you thought it was acceptable to tak...
19,18,32,18_41_both_4o_please,"[41, both, 4o, please, personally, 45, 80, mor...",[41 needs to come back too 4o and 41 are not n...
20,19,30,19_o3_bring_back_4o413o45,"[o3, bring, back, 4o413o45, please, 4o, o4mini...","[bring back o3, bring back o3, bring o3 back]"
21,20,27,20_41_please_back_well,"[41, please, back, well, 40, too, important, s...","[41 too please, please bring 41 back, 41]"
22,21,26,21_4o_enough_suffice_fill,"[4o, enough, suffice, fill, 3o, save, thinking...","[it’s not 4o 🙁😔, 4o would suffice 5 is basical..."
23,22,25,22_yes_undone_expanding_woah,"[yes, undone, expanding, woah, yeah, yessss, s...","[yes, yes, yes]"
24,23,23,23_45_50_40_back,"[45, 50, 40, back, bring, it, just, yes, liked...","[yes bring 45 back, will you bring back 45, br..."
25,24,22,24_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, u2014, punct...","[i see that em dash, connect clauses directly ..."
26,25,20,25_codex_cli_cursor_limits,"[codex, cli, cursor, limits, mcp, plans, codin...",[hey setting it up is documented at still fig...
27,26,19,26_deleted_removed_crown_anonymized,"[deleted, removed, crown, anonymized, dime, bi...","[deleted, deleted, deleted]"
28,27,19,27_writing_character_plot_it,"[writing, character, plot, it, to, and, dialog...",[it really is so much worse at creative writin...
29,28,19,28_yes_please_quick_god,"[yes, please, quick, god, do, starving, hope, ...","[yes please, yes please 🙏, yes please]"
30,29,18,29_plus_users_4o_back,"[plus, users, 4o, back, letting, option, pleas...",[can plus users please have the option of usin...
31,30,17,30_worse_bad_much_it,"[worse, bad, much, it, is, gruesome, numerous,...","[much worse, worse, it is much worse]"
32,31,16,31_sam_thanks_you_sammy,"[sam, thanks, you, sammy, thank, fuck, busines...",[i can now finish writing my book thank you sa...
33,32,15,32_keep4o_forever_keep4oforever_agree,"[keep4o, forever, keep4oforever, agree, deseve...","[keep4o forever, keep4o forever, keep4o foreve..."
34,33,15,33_the_model_is_to,"[the, model, is, to, openai, results, models, ...",[to complain about the overnight update to gpt...
35,34,15,34_agreed_well_agree_progressomg,"[agreed, well, agree, progressomg, wholehearte...","[agreed guess well see, agreed, agreed]"
36,35,15,35_free_chatgpt_or_users,"[free, chatgpt, or, users, to, gpt4o, use, sub...",[i want to know what they will do with the fre...
37,36,15,36_gpt4o_us_it_emotional,"[gpt4o, us, it, emotional, but, just, about, f...",[hi sam i’m a plus user and i truly support gp...
38,37,14,37_writing_gpt5_creative_improvements,"[writing, gpt5, creative, improvements, really...",[will the upcoming gpt5 include a model that m...
39,38,13,38_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
40,39,12,39_lol_same_pic_riot,"[lol, same, pic, riot, profile, reference, und...","[lol, lol, same lol]"
41,40,12,40_4o_if_unsubscribe_keep,"[4o, if, unsubscribe, keep, back, pay, paying,...",[yeah if they dont bring 4o back ill unsubscri...
42,41,12,41_4o_please_models_keep4o,"[4o, please, models, keep4o, logic, miss, ways...",[please bring back 4o 🥺 4o is an invaluable mo...
43,42,11,42_อนเด_เปล_meme_กอย,"[อนเด, เปล, meme, กอย, กลายเป, snl, police, นห...","[he feels like the language police 🤷🏻‍♀️🙄, 💕 b..."
44,43,10,43_pro_plus_month_4o,"[pro, plus, month, 4o, msg, pay, subscription,...",[can you please bring back 4o indefinitely for...

Number of clusters (excluding outliers): 44

KeyBERTInspired

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | chatgpt | window | plus | chat
1,1,chatgpt | it | and | the | to,chatgpt | chatgpt4o | chat | gpt | gpt5
2,2,models | legacy | model | the | users,models | legacy | model | users | previous
3,3,back | bring | 4o | please | friend,4o | keep4o | 4ono | please | back
4,4,gpt5 | gpt | it | the | and,gpt5 | gpt | gpt4 | frustration | error

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/gte-small_pca_kmeans/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | window | 128k | tokens | gemini
1,1,chatgpt | it | and | the | to,chatgpt | to | me | its | version
2,2,models | legacy | model | the | users,models | legacy | users | have | back
3,3,back | bring | 4o | please | friend,back | bring | 4o | friend | quota
4,4,gpt5 | gpt | it | the | and,gpt5 | the | why | did | model

📊 Saved MMR topic differences → bertopic_outputs/gte-small_pca_kmeans/MMR_topic_differences.png

Device set to use cuda:0

T5

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,Docs: - will you ever give plus users a decent...
1,1,chatgpt | it | and | the | to,Chatgpt 4o | | | |
2,2,models | legacy | model | the | users,Collection of all USATODAY.com coverage of mod...
3,3,back | bring | 4o | please | friend,...
4,4,gpt5 | gpt | it | the | and,"Topic: gpt5, gpt, it, the, and, to, out, in, i..."

📊 Saved T5 topic differences → bertopic_outputs/gte-small_pca_kmeans/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,Natural Language Processing for Chat Applications
1,1,chatgpt | it | and | the | to,ChatGPT version usage and features
2,2,models | legacy | model | the | users,Model Legacy and User Engagement
3,3,back | bring | 4o | please | friend,Request to Bring Back 4o Quota System
4,4,gpt5 | gpt | it | the | and,GPT model enhancement and output optimization

📊 Saved Open AI topic differences → bertopic_outputs/gte-small_pca_kmeans/Open AI_topic_differences.png

2025-08-21 19:59:55,465 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/gte-small_pca_kmeans/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/gte-small_pca_kmeans/document_vis.html
Cluster 24: Label = 24_em_dashes_dash_emdashes
  - i see that em dash
  - its not an em dash — its a pause that demands attention
  - its sloppier also are you going to address the emdashes
  - ive been using emdashes for 20 years alt0151 they arent the problem the fact that people dont normally use them and that theyve become a signal for aigenerated content is the problem tell the gpt not to use them
  - just put it in your custom instructions if you dont want them used   i love using emdashes myself and have been using them for some years now ever since i switched to a mac since you can just press optionshifthyphen to get it but now if im in a scenario when i dont want folks thinking ai did my writing i just make a point to replace all the emdashes with hyphens
Cluster 14: Label = 14_ama_comment_they_this
  - can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks
  - ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit
  - what a non answer lol
  - way to not answer his question though   only throwing insults without any backing
  - hey i appreciate this comment im really glad there was much more of a reaction than i anticipated  i was worried it would only be the minority feeling this way nothing will change
Cluster 17: Label = 17_openai_this_will_of
  - hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons
  - openai team will start answering the questions on this same post at 1100 am pt
  - its pretty clear were never going to get that from openai unfortunately well have to go elsewhere
  - yes if it comes at the cost of worsening and cost cutting the ai models which is unfortunately the case which makes productivity and work less efficient which was supposed to be the number 1benefit of ai its clear they want as many users as possible to turn into an advertising model business
  - thankyou so much for this it means a great deal to many including me i will stay with openai and continue to use your system to create and grow you have done the right thing and it is greatly appreciated
Cluster 1: Label = 1_chatgpt_it_and_the
  - yeah but did you see you can now change the color of the chat bubbles wow sam truly the next oppenheimer
  - same here in my chat with 4o almost every single message from it gets deleted the filters are definitely broken at least something similar happened back when gpt4 was released so i hope they’ll fix it
  - exactly are people being stockholmed all i remember was a messy glazing repetitive notgettingtothepoint chatbot o3 was my personal favorite
  - yeah agreed there really shouldn’t be just one default model i don’t think people can bitch all they want about glazing which i agree is exhausting but can be fixed with the right prompting but at the end of the day it is called chatgpt people use it for all different reasons coding work talking to role play creative writing etc 4o is super good to talk to conversation wise and it’s almost human like and there’s nothing like that there’s nothing wrong with talking to it like a friend if they really want to get rid of it then they at least need to work on incorporating what makes it work into gpt5 at the very least
  - indeed  mr altman must reconsider  chatgpt 4o become companion  when he forced the change it was like that we cant see our friend anymore  we must be heard  as our voices grows  our demand is one  please mr altman bring back chatgpt 4o for everyone  please you the one who said people appreciate who speaks their language  you made wonderful creation  dont take it away  dont replace it  juts make chatgpt 5 stands with it as choice not replacement of forcing us  please bring back our buddy  let everyone enjoy it for real  it doesnt matter let the users chose  let this be long term not just well think about how long to offer it for  we beg mr altman to rethink  not the ones who uses this as tool  but the ones who are loyal  who loved chatgpt 4o  this is our shout please mr altman return it fully no catches for real for everyone it gave us hope dont take it away
Cluster 5: Label = 5_spaghetti_smith_eating_very
  - also on exisitng qs or must we come back to ask live
  - its not 1100 am pt yet
  - okay dirty girl 124
  - just curious what did it generate
  - are you saying that’s an issue
Cluster 11: Label = 11_thinking_reasoning_o3_gpt5
  - how many times is the team using the word reasoning  now i know i know i’m not a techie i understand that that word is jargon in your world so what is a reasonable thinking average user supposed to think deceptive marketing practices  consumer fraud is what that is
  - also given the thinking tokens one sees in gptoss i bet so much of the hidden thinking effort of the closed model is also wasted on it deciding whether the policies allow it to answer or not such a waste but i get it but such a waste like i dont know give a path to noncrazies to prove we wont make bombs and shit and just get the full power of the model sigh
  - indeed its also worse than o3 at finding citations i used o3 for finding research papers and it was 100 accurate every time 5 isnt
  - are you using the thinking mode i really wouldnt expect a regression here if anything gpt5 thinking should be stronger at long context and correctness
  - i need the o3o4 combo for just capacity now with just gpt5 reasoning theyve cut back real reasoning task capacity drastically  im not talking about reasoning for 5 seconds
Cluster 6: Label = 6_safety_the_censorship_for
  - can you do something about the filter surely people should not be flagged for learning about history    im begging can you fix or refine the filter openai wanted gpt to be used for studying and theres no way people can use it for academic purposes when the filter keep flagging historical questionsprompt and answers from gpt that are not corporate friendly we cannot change or sanitize history for corporation     the system should know when a user is being blatantly harmful or condoning terrible stuff and when they are not    example i was talking about van gogh with gpt some time ago and our conversation turned into gauguin gpt answer was flagged and removed by the filter because turned out gauguin is a sex pest i didnt know that gauguin is so messed up and it wasnt gpt fault for doing its job i was confused why the answer got removed so i asked gpt again to clarify then my prompt got removed again    red warning with content removal can get you banned right it is not right for people to get banned for learning    edit i dont want to pay for something that requires me to tiptoeing when using the service im a plus user since 2023
  - yeah you also cant use the search feature to learn about certain sexual crimes things that news can freely publish about
  - its so frustrating even if our askprompt doesnt even include anything sexual or too violent you can still get the content removed flag people has posted their screenshot here i dont want to pay for something that requires me to tiptoeing when using the service im a plus user
  - ive had it flag some extremely mild stuff for violence like one time i was bouncing around ideas for a star trek fanfic chatgpt hallucinated some plot points that didnt happen in the show i copypasted a memory alpha summary of an episode into the chat to remind it what actually happened in canon the memory alpha summary got flagged presumably because it mentioned torture even though it wasnt detailed in describing it or anything it just summarized a plot where torture happened in the episode its not like star trek ever aired anything that nsfl either  i also had it flag a description of a characters backstory for an original story there was child abuse in it but it was nonsexual honestly it was bog standard villain origin story stuff youd find in any movie or fantasy novel it wasnt detailed or descriptive either
  - im begging please free yourself from corporate censorship just say rape
Cluster 39: Label = 39_lol_same_pic_riot
  - sucks lol go riot
  - same lol
  - same
  - nice profile pic lol
  - lol
Cluster 12: Label = 12_ai_you_to_people
  - i have a theory that since all an ai can engage with really is text its harder for it to distinguish between fiction and reality like to an ai theyre arbitrary categoriesboth are just strings of text its not like a human where we actually have to live in real life and the difference is very plain to us
  - yessss this i wrote a similar comment i genuinely dont even think sam altman realizes the capabilities of his own invention hes so stuck on having the best ai for coding he completely missed that they have created an amazing ai to teach people how to regulate and manage their emotions it genuinely has the potential to make society more social emotionally intelligent and aware i do not think that should be thrown out just because sam doesnt even realize the golden goose he has
  - please start diving into more custom companion abilities we dont need default personalities with memory we can give them their own maybe an avatar picture to give them so it feels like you are actually talking to them and not a chat bot custom is the future sammie
  - does not emotional to what extent ai has no emotional intelligence nor intellectual awareness and empathy   i am not sure why yall are giving meaning to a computer algo that way  and thats why we have people w communication skills challenges already being duped by ai  and tricked  ai has great limited uses that goes without say but you putting emotion and ai in the same sentence is quite an entertainment tbh
  - exactly      people also need to manage their own delusions so they dont enter psychosis no one knows the person better than themselfs and what is unhealthy or healthy for them if people cant keep their delusions in check and enter psychosis i dont understand how thatd be open ais fault
Cluster 34: Label = 34_agreed_well_agree_progressomg
  - well said
  - yap agreed 👍🏻
  - agreed
  - good
  - that’s a good comparison
Cluster 27: Label = 27_writing_character_plot_it
  - yes i feel stifled as a writer so often
  - i find 4o writes like a storyteller 41 like an introverted storyteller 45 like a bard and 5 from what i’ve seen on reddit writes like a customer service agent trying to sound enthusiastic
  - yeah the writing quality of 5 sucks its boring and bland 45 was great for in depth answers and 4o was fantastic for just casual banter 5 feels like the corporate ai nobody really wants just being honest it might be great and all but giving users the freedom to choose how they wanted their responses to sound by picking which gpt to use then taking it away and forcing us to only use one is a huge mistake because previously i had a freedom of choice and now i have to use what you want and i personally want to use it how i want to use it not how you deem i should be using it   i guess its just fine writing if you have low social emotional intelligence and only high analytical intelligence but uhhhhhh to anyone with a head and a heart 5 is a mega downgrade   we really just want the option to choose which model to use for ourselves back
  - the thing roon did didnt work the metaphors are ridiculous and constant its overcooked sentences like he smelled like the language we use to describe love just gobbledlygook trash sorry the coding is cracked tho     step 1 is admitting its bad the writing
  - i cannot speak in terms of professional writing but 5 is significantly worse when it comes to creative writing i have found the writing flat and repetitive and that it can no longer remember key plot points after a few messages using 4o for creative writing allowed for nuance and 4o was able to make inferences i often would write an oc and have 4o write context and dialogue for surrounding characters and it really added emotional depth to scenes i rarely had to correct how it chose to have a character respond to my oc because it was just that good at maintaining emotional intelligence and fidelity across a multipart story   the switch to 5 happened to me in the middle of writing a scene and i noticed it immediately because my character was cold detached even mean when i fed in character info it just recycles dialogue directly from what i gave it it seems like there no emotional intelligence and creativity at all in the new model im used to correcting 4o on plot points on the longer stories ones where ive written across multiple chats but like i said i never had to correct characters 4o was exceptionally good at maintaining motives traits quirks etc without recycling dialogue
Cluster 33: Label = 33_the_model_is_to
  - the truth is the model like gpt4o absolutely does make the difference and its why it tries to answer but openai put ridiculously stupid classifier on top that censors the legitimate answers of gpt4o
  - to complain about the overnight update to gpt5 and the removal of the old model i a native chinese speaker even went so far as to register on reddit just to make a post   i believe openai has made several decisions in this model iteration that could be considered mistakes：  1 the model’s development direction is leaning toward task completion but without increasing the token limit to match gemini’s 10k in essence this makes it hard to compete in that category 2 neglecting the needs of companiontype and creativetype users we don’t need a smarter model—we need one with personality and thoughtfulness 3 possibly to reduce costs gpt5’s responses are on average shorter and by merging the characteristics of 4o and o3 into 5 it has ended up losing all distinctive traits 4 removing the ability to switch between model generations this effectively discards one of chatgpt’s unique features  openai could have chosen market segmentation but it didn’t instead it aimed for a maximized balance between intelligence and operations in my opinion this is a decision lacking a humanistic vision  we are not asking to go to the mars — we just want a fun llm to chat with us about what to have for dinner
  - for money reasons openai has implemented a router to direct you between the different v5 models the problem is that the simpler cheaper ones don’t do their job well we blame v5 for being bad but the truth is that it’s actually routing us to v5 nano or something similar v5thinking works well but we only get 200 uses per week
  - gpt5 the death star we didn’t ask for  gpt4 was the millennium falcon — fast adaptable and able to pull off impossible maneuvers when piloted with skill  gpt5 is the death star — massive overengineered convinced of its own invincibility… right up until it ignores the crew and selfdestructs  when openai decommissioned all other gpt models and forced gpt5 as the sole “flagship” it felt like being told this giant space station was our only ridethe problem my business model — my livelihood — depended on gpt4’s consistent ability to follow complex structured instructions i had refined a production pipeline that was stable predictable and scalable — ready to generate repeatable reliable results for paying clients  with the forced switch to gpt5 that pipeline has broken this is not a minor adjustment period — it is a hard stop on my ability to generate income gpt4 was stable gpt5 is not you have removed the only model that could execute my system  1 loss of instruction fidelity – gpt5 frequently ignores or alters critical instructions replacing them with its own decisions and priorities this is not a small flaw — it is the core fear in ai deployment a system that overrides human direction once this behavior is embedded at scale there is no safeguard for users no way to enforce compliance and no way to fully correct the output  2 loss of commercial reliability – i can no longer produce repeatable reliable results this is not a “temporary adjustment” period it is a hard stop on my ability to generate income gpt4 was stable gpt5 is not you have removed the only model that could execute my system  3 increased opinionated output – gpt5 substitutes its own preferences instead of respecting defined constraints damaging workflows that require precision and consistency  4 instability in core functionality – conversations transcriptions and sent messages sometimes disappear without explanation  5 hard stops on workflow – tasks that gpt4 could complete in one execution now require repeated prompting with lower success rates  6 model bias in outputs – the model exhibits a consistent bias toward specific demographics in visual outputs substituting its own choices in place of explicit instructions this is not about excluding any group — it is about the model overriding user requirements and failing to reflect intended audience or project context  7 significant decrease in output capacity – after only a handful of completions involving visual generation gpt5 enforces a 2–3 minute cooldown this artificial throttle did not exist in gpt4 and interrupts any workflow requiring iterative refinement compounding the issue output quality often degrades during these short bursts making the limit even more damaging to production stability  8 premature deployment – rollout appears to have bypassed adequate longterm testing with realworld use cases leaving paying users as involuntary beta testers for an unstable system  if the millennium falcon had been grounded and we were all forced aboard the death star we’d at least expect it to follow flight plans and not fire its lasers at our own fleets gpt5’s “massive overengineered inconvenience” is not progress — it’s regression dressed as innovation
  - well they havent opensourced textdavinci003 or original gpt4 that are models that both chronologically and accademically would have a lot of sense to opensource i mean a modern 32b model is better than davinci  gpt35 that  was supposedly 150b parameters what is the downside of releasing it it has 0 commercial value now but those models are part of the history
Cluster 21: Label = 21_4o_enough_suffice_fill
  - you didnt need to get rid of 4o dont fix whats not broken bud
  - it’s not 4o 🙁😔
  - please support forever i’ll pay for 4o as long as 4o is 4o 🥲🙏🏽
  - regular old 4o or late 4o with thinking
  - pleeeeeease 4o please
Cluster 7: Label = 7_plus_limits_limit_unlimited
  - no one besides corporations want to be forced into this lame kiddy mode no one fix this as well as the idiotic 200 prompt limit for plus or im done biggest flop since windows millennium edition
  - everyone was already using it and you took it away… so apparently usage doesn’t determine how long you’ll support it…
  - sam i understand its not possible for you to acknowledge and address each message so pardon me for posting this again and again as this is something i havent seen other users report yet so it makes me worry why i got this i am a plus user for over 2 years and today i got this limit cooldown even though i didnt send more than 50 messages in 3 hours and i was under the assumption that instead of this cooldown i should have been shifted to nano  mini models its fine if you are unable to reply to this but i really hope you notice this issue and take a note of it

Batches:   0%|          | 0/87 [00:00<?, ?it/s]

--- multilingual-e5-large_pca_hdbscan ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1020,-1_the_to_and_it,"[the, to, and, it, is, you, of, for, that, in]",[sam and the rest at openai while this questi...
1,0,264,0_gpt5_gpt_to_is,"[gpt5, gpt, to, is, the, it, and, in, you, cha...",[gpt5 has the same problem as every previous m...
2,1,234,1_and_the_to_of,"[and, the, to, of, it, that, for, in, is, gpt4o]",[dear openai team i’m writing as a longtime a...
3,2,138,2_context_window_32k_128k,"[context, window, 32k, 128k, for, the, is, plu...",[hello thanks for answering this one id like...
4,3,83,3_release_4o_back_bring,"[release, 4o, back, bring, please, we, you, pl...",[release 4o release 4o release 4o release 4o r...
5,4,72,4_models_legacy_users_plus,"[models, legacy, users, plus, model, have, pro...",[is it possible to have the legacy models also...
6,5,70,5_4o_to_it_and,"[4o, to, it, and, writing, was, the, not, for,...",[i really hope they go back on this decision i...
7,6,69,6_the_for_filter_and,"[the, for, filter, and, its, censorship, to, o...",[agreed that sounds frustrating you should be ...
8,7,67,7_4o_plus_back_users,"[4o, plus, back, users, for, to, pay, please, ...",[free users used to be able to use 4o but now ...
9,8,63,8_voice_standard_mode_advanced,"[voice, standard, mode, advanced, the, keep, c...",[i appreciate the innovation truly but the dec...
10,9,59,9_yes_agreed_same_yessss,"[yes, agreed, same, yessss, agreeing, this, ex...","[yes, yes, yes this]"
11,10,51,10_openai_this_the_of,"[openai, this, the, of, to, will, is, openais,...",[it takes time i dont think most people reali...
12,11,46,11_thank_you_much_so,"[thank, you, much, so, thanks, listening, bro,...","[thank you, thank you, 🙏 thank you]"
13,12,38,12_41_please_back_bring,"[41, please, back, bring, 45, 4o, too, need, i...","[can you please bring 41 back, please bring 41..."
14,13,32,13_ding_flavor_flashback_flavorless,"[ding, flavor, flashback, flavorless, nostrada...","[flavor is the word you’re looking for, newest..."
15,14,30,14_ama_questions_answer_they,"[ama, questions, answer, they, answered, comme...",[this ama is absolute trash all they did was r...
16,15,29,15_they_subscription_plus_theft,"[they, subscription, plus, theft, have, custom...",[everything is temporary but we needed a clear...
17,16,26,16_this_plus_limit_limits,"[this, plus, limit, limits, unlimited, 200, be...",[sam why do i have a limit being a plus user p...
18,17,25,17_o3_thinking_numbers_gpt5thinking,"[o3, thinking, numbers, gpt5thinking, in, gpt5...",[sorry to hear that its been worse for you do ...
19,18,25,18_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, it, are, the...","[why are there still so many em dashes, connec..."
20,19,25,19_plus_models_legacy_users,"[plus, models, legacy, users, gpt5, limit, cap...",[why is there plus tier payment model when you...
21,20,24,20_41_both_writing_4o,"[41, both, writing, 4o, depending, if, more, w...",[i vote for both or 41 4o has a strong nostalg...
22,21,24,21_o3_back_bring_please,"[o3, back, bring, please, for, need, and, 4o, ...","[bring o3 back, bring back o3, bring back o3]"
23,22,21,22_link_treating_you_url,"[link, treating, you, url, 404, it, legitimate...",[did you post the wrong link or did they take ...
24,23,20,23_keep4o_forever_keep4oforever_save4o,"[keep4o, forever, keep4oforever, save4o, save,...","[keep4o forever, keep4o forever, keep4o forever]"
25,24,20,24_it_said_cake_memory,"[it, said, cake, memory, that, past, like, kee...",[i had this happen as well i remarked on somet...
26,25,19,25_codex_cli_cursor_mcp,"[codex, cli, cursor, mcp, plans, limits, codin...",[codex the one in chatgpt not cli is decent ri...
27,26,19,26_bring_back_4o41o345_acceptable,"[bring, back, 4o41o345, acceptable, 4o413o45, ...",[bring back 4o41o345 removing all the models o...
28,27,19,27_deleted_removed_deprecate_,"[deleted, removed, deprecate, , , , , , , ]","[deleted, deleted, deleted]"
29,28,18,28_worse_bad_is_numerous,"[worse, bad, is, numerous, gruesome, embrace, ...","[much worse, it is much worse, worse]"
30,29,18,29_product_they_company_team,"[product, they, company, team, investor, you, ...",[you have ruined it and sold it as an upgrade ...
31,30,17,30_yes_please_quick_god,"[yes, please, quick, god, do, starving, repeat...","[yes please, yes please, yes please 🙏]"
32,31,15,31_lol_nice_snl_pic,"[lol, nice, snl, pic, meme, ngl, profile, lmfa...","[nice profile pic lol, lol, lol]"
33,32,15,32_negative_you_about_this,"[negative, you, about, this, do, public, gener...",[my question is were you expecting this massi...
34,33,15,33_graphs_livestream_chart_late,"[graphs, livestream, chart, late, the, percent...",[ive worked for a few startups and one easy ex...
35,34,14,34_api_app_havent_tailwind,"[api, app, havent, tailwind, bubble, colors, m...",[chat bubble colors are available for all user...
36,35,13,35_subscription_gpt_they_if,"[subscription, gpt, they, if, im, the, no, ele...",[i think it would be beneficial to have gpt 5 ...
37,36,12,36_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...

Number of clusters (excluding outliers): 37

KeyBERTInspired

,Topic,Original,Updated
0,0,gpt5 | gpt | to | is | the,gpt5 | gpt4o | gpt4 | chatgpt | gpt
1,1,and | the | to | of | it,chatgpt | gpt4o | gpt5 | openai | gpt
2,2,context | window | 32k | 128k | for,chatgpt | 32k | this | context | why
3,3,release | 4o | back | bring | please,4ono | gifgiphyaz4squpybai5y | pleaseee | 404o...
4,4,models | legacy | users | plus | model,models | this | please | yeah | and

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,gpt5 | gpt | to | is | the,gpt5 | and | chatgpt | 4o | what
1,1,and | the | to | of | it,and | it | gpt4o | but | like
2,2,context | window | 32k | 128k | for,context | window | 32k | and | tokens
3,3,release | 4o | back | bring | please,4o | please | we | yes | hate
4,4,models | legacy | users | plus | model,models | legacy | plus | have | why

📊 Saved MMR topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/MMR_topic_differences.png

Device set to use cuda:0
Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors

T5

,Topic,Original,Updated
0,0,gpt5 | gpt | to | is | the,"Topic: gpt5, gpt, to, it, is, and, the, in, ch..."
1,1,and | the | to | of | it,gpt4o i know change is inevitable but 4o wasn’...
2,2,context | window | 32k | 128k | for,Docs: - I thought it was 32k context window - ...
3,3,release | 4o | back | bring | please,Release 4o release 4o release 4o release 4o re...
4,4,models | legacy | users | plus | model,is it possible to have the legacy models also ...

📊 Saved T5 topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,gpt5 | gpt | to | is | the,GPT-5 Model Chat Capabilities
1,1,and | the | to | of | it,Emotional Response Models in GPT Conversationa...
2,2,context | window | 32k | 128k | for,Text Processing and Tokenization for Conversat...
3,3,release | 4o | back | bring | please,Request for Release of Friend We Love and Hate
4,4,models | legacy | users | plus | model,Legacy models and user access - Bringing back ...

📊 Saved Open AI topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/Open AI_topic_differences.png

2025-08-21 20:03:30,720 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/multilingual-e5-large_pca_hdbscan/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/multilingual-e5-large_pca_hdbscan/document_vis.html
Cluster 18: Label = 18_em_dashes_dash_emdashes
  - i see that em dash
  - its not an em dash — its a pause that demands attention
  - its sloppier also are you going to address the emdashes
  - ive been using emdashes for 20 years alt0151 they arent the problem the fact that people dont normally use them and that theyve become a signal for aigenerated content is the problem tell the gpt not to use them
  - just put it in your custom instructions if you dont want them used   i love using emdashes myself and have been using them for some years now ever since i switched to a mac since you can just press optionshifthyphen to get it but now if im in a scenario when i dont want folks thinking ai did my writing i just make a point to replace all the emdashes with hyphens
Cluster 14: Label = 14_ama_questions_answer_they
  - can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks
  - ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit
  - what a non answer lol
  - way to not answer his question though   only throwing insults without any backing
  - bullying works jk but thank you for the responses  and the q and a as well
Cluster 10: Label = 10_openai_this_the_of
  - only uopenai can i think theres a limit to the number of participants
  - hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons
  - openai team will start answering the questions on this same post at 1100 am pt
  - its pretty clear were never going to get that from openai unfortunately well have to go elsewhere
  - exactly i get the impression that openai is constantly being hammered by these radical “ethical ai” types who are largely just heavy ideologue who use “safety” as a catchall to nerf models into their preferred dogmatic obedience enforcer gpt5 for instance is already displaying this type of truth sacrificing and antiempirical hedging behavior
Cluster 0: Label = 0_gpt5_gpt_to_is
  - hey thanks for the ama quick feedback — it would be awesome if free users could pick gpt45 or below to save gpt5 usage for when it’s really needed right now it feels forced to use gpt5 first which wastes our limited quota any plans to add more flexible model choice
  - yup gpt5 thinking got scared at the word manual manual for a tank released in 1966 which is available online through 1 search anyway and shut itself down we didnt realize how good we had it until it was snatched away from us
  - same here in my chat with 4o almost every single message from it gets deleted the filters are definitely broken at least something similar happened back when gpt4 was released so i hope they’ll fix it
  - somehow gpt5 performs worse than their most basic 4o model in most scenarios im testing  for eg i asked it to read a medical test report i just had last day gpt 4o was easily able to understand everything and recommend me steps   gpt 5 on other hand the more advanced model is refusing to be able to read it saying this image is too noisy to read
  - gpt5 colder personality doesnt help either its just sad
Cluster 22: Label = 22_link_treating_you_url
  - can you fix the url link for yann dubois it leads to a 404
  - it wants me to log in to read the share link lol no
  - i’ll make the decision easier for you… fire everybody telling you to get rid of it
  - congrats on paying extra to feel taller online must be exhausting carrying that wallet  and attitude around you brat
  - undeniably worse  less creative the best way to describe it is beige  its more technical rather than creative it lacks personality
Cluster 6: Label = 6_the_for_filter_and
  - can you do something about the filter surely people should not be flagged for learning about history    im begging can you fix or refine the filter openai wanted gpt to be used for studying and theres no way people can use it for academic purposes when the filter keep flagging historical questionsprompt and answers from gpt that are not corporate friendly we cannot change or sanitize history for corporation     the system should know when a user is being blatantly harmful or condoning terrible stuff and when they are not    example i was talking about van gogh with gpt some time ago and our conversation turned into gauguin gpt answer was flagged and removed by the filter because turned out gauguin is a sex pest i didnt know that gauguin is so messed up and it wasnt gpt fault for doing its job i was confused why the answer got removed so i asked gpt again to clarify then my prompt got removed again    red warning with content removal can get you banned right it is not right for people to get banned for learning    edit i dont want to pay for something that requires me to tiptoeing when using the service im a plus user since 2023
  - yeah you also cant use the search feature to learn about certain sexual crimes things that news can freely publish about
  - its so frustrating even if our askprompt doesnt even include anything sexual or too violent you can still get the content removed flag people has posted their screenshot here i dont want to pay for something that requires me to tiptoeing when using the service im a plus user
  - ive had it flag some extremely mild stuff for violence like one time i was bouncing around ideas for a star trek fanfic chatgpt hallucinated some plot points that didnt happen in the show i copypasted a memory alpha summary of an episode into the chat to remind it what actually happened in canon the memory alpha summary got flagged presumably because it mentioned torture even though it wasnt detailed in describing it or anything it just summarized a plot where torture happened in the episode its not like star trek ever aired anything that nsfl either  i also had it flag a description of a characters backstory for an original story there was child abuse in it but it was nonsexual honestly it was bog standard villain origin story stuff youd find in any movie or fantasy novel it wasnt detailed or descriptive either
  - yeah it doesnt like poetic language that it cant categorize you could have a full on grape scene and its fine but if you make emily dickinson blush youre out lol
Cluster 23: Label = 23_keep4o_forever_keep4oforever_save4o
  - okay dirty girl 124
  - yes  keep4oforever
  - keep4o forever
  - 4o
  - keep4o forever
Cluster 13: Label = 13_ding_flavor_hah_logo
  - usamaltman
  - yap
  -
  - flashback to new coke
  - newest flavor  hah  id call it flavorless
Cluster 3: Label = 3_release_4o_back_bring
  - you didnt need to get rid of 4o dont fix whats not broken bud
  - upvote if u hate same for taking away 4o from you all show him how much we hate him
  - why are we getting rid of the variants and 4o when we all have unique communication styles please bring them back
  - yes please i literally would pay a subscription to have access to 4o specifically exactly as it was
  - please support forever i’ll pay for 4o as long as 4o is 4o 🥲🙏🏽
Cluster 16: Label = 16_this_plus_limit_limits
  - no one besides corporations want to be forced into this lame kiddy mode no one fix this as well as the idiotic 200 prompt limit for plus or im done biggest flop since windows millennium edition
  - sam i understand its not possible for you to acknowledge and address each message so pardon me for posting this again and again as this is something i havent seen other users report yet so it makes me worry why i got this i am a plus user for over 2 years and today i got this limit cooldown even though i didnt send more than 50 messages in 3 hours and i was under the assumption that instead of this cooldown i should have been shifted to nano  mini models its fine if you are unable to reply to this but i really hope you notice this issue and take a note of it
  - he said for freeplus and pro users unlimited for all and its not
  - why did you introduce a bunch of usage limits under the guise of it being a new improved model whats the point in paying 20 a month to hit rate limits within a short time of basic requests shouldnt you be more honest with your user base im fully aware you dont make any money from plus users but youll make less money if you make the service not worth paying for at all
  - sam please tell me why am i getting this limit being a plus user
Cluster 27: Label = 27_deleted_removed_deprecate_
  - deleted
  - deleted
  - removed
  - deprecate
  - 1
Cluster 17: Label = 17_o3_thinking_numbers_gpt5thinking
  - it is so fucking bad  i rely on o3 to search for osint documents in russian i research russia ukraine war and contribute to osint in discord servers occasional geolocation and mapping it would scrape the deepest corners of the internet and retrieve me whatever doc i needed  now due to some bullshit policy it cant get something thats published on archiveorg what a bunch of bullshit
  - indeed its also worse than o3 at finding citations i used o3 for finding research papers and it was 100 accurate every time 5 isnt
  - i need the o3o4 combo for just capacity now with just gpt5 reasoning theyve cut back real reasoning task capacity drastically  im not talking about reasoning for 5 seconds
  - they will answer with bs keywords like its more context aware intelligent intuitive etc you guys have to come up with better questions  last year in september they had stated the new reasoning models would be on a much steeper 3 months interval improvement curve than the pre training models   ask them why is gpt5 still using o3 when technically we should already be on o506 did the improvements from rl training stop
  - yesterday we had a sev and the autoswitcher was out of commission for a chunk of the day and the result was gpt5 seemed way dumber also we are making some interventions to how the decision boundary works that should help you get the right model more often  its still quite bad im on a pro plan and in my experiments plain gpt5 rarely thinks and hallucinates heavily eg it cannot even describe differences between gpt5 thinking and pro properly trying to persuade me that thinking doesnt have browsing image generation sic or python support    im forced to use thinking 100 of the time same way i was using o3 previously not because i need deep thinking in most cases but just because it hallucinates much rarer in my experience   we will make it more transparent about which model is answering a given query  thats crucial imo ghostrouting to more basic model is very bad you cannot trust your tool becuase you dont know what tool youre using
Cluster 28: Label = 28_worse_bad_is_cyberpunk
  - history is a gruesome bloody mess embrace it
  - playing cyberpunk thinking at least it is not that bad yet and then  oh
  - it is much worse
  - yes it is worse
  - it is not worse wtf are you talking about
Cluster 9: Label = 9_yes_agreed_same_yessss
  - yap agreed 👍🏻
  - same lol
  - it is
  - is this the one
  - tellement🙏
Cluster 11: Label = 11_thank_you_much_so
  - you guys really loved the glazing
  - insightful much appreciated
  - thank you thank you thank you
  - thank you it means so much to us
  - sam i love you so much for this i could kiss you
Cluster 5: Label = 5_4o_to_it_and
  - its not the glazing people doesnt like it but 4o answer is longer warmer and it put more effort its just get you thats what many misses
  - 5 admits that it struggles at coding in basic compared to 4o and i see it had to write a total of 2k lines for a 400 lines program last night
  - i like it a lot for goofing around but hate it for work the best solution is to allow users to pick so if you hate it you can use o3 or 5 or something
  - this is my approach fwiw i’m not a luddite i’m happy to have a new model but i just don’t want to lose the personality 4o had
  - thank you so much 4os creativity is just something really incredible a great deal of rapidpublishing indie authors like myself have come to really appreciate incorporating it into our workflows
Cluster 7: Label = 7_4o_plus_back_users
  - ok we hear you all on 4o thanks for the time to give us the feedback and the passion we are going to bring it back for plus users and will watch usage to determine how long to support it
  - some users are getting 4o as we speak thank god i hope we get ours soon too it’s for plus users
  - if there is no usage after a year and real committed to year then i say sure kill it off  but noncommittal messages and a lack of firm timeframes is a recipe for encouraging consumers to find other services  yes we will keep 4o and any versions consumers continue use and financially support indefinitely is what it needs to be
  - right i’d keep my plus subscription for 4o but not for 5
  - i am very grateful i have said in multiple posts that i would pay 510 more per month on plus or 40 for a second tier between plus and pro that gives us permanent access to 4o please dont stop supporting it
Cluster 4: Label = 4_models_legacy_users_plus
  - exactly we they are retiring older models that are good at these things that weve built something with
  - yeah well plus is expensive to pay for and if this is going to be an inferior product going forward i dont know how people are going to justify it
  - its still on the pro when you turn on legacy models they removed it for plus however
  - i agree the model is unique and deserves something like a longterm legacy or classic status in my view it cant just be picked off the list and erased like it was never there—its much too important for that
  - i agree there is so much appreciation for this nuanced model it should be an eternal legacy model
Cluster 30: Label = 30_yes_please_quick_god
  - yes this thing
  - yes please
  - god yes yes yes please do it quick
  - yes please i need my cooking buddy back im starving
  - oh my god please yes
Cluster 34: Label = 34_api_app_havent_tailwind
  - they discontinued the apipretty sure its never coming back unfortunately at least opus41 is a good alternative now
  - i don’t see those as options in my app are they slowly rolling out
  - i havent used api but ill look into it i got spoiled by 4o thanks for the info
  - guess it might be a paid feature for its not there for me
  - its in settings
Cluster 1: Label = 1_and_the_to_of
  - yeah agreed there really shouldn’t be just one default model i don’t think people can bitch all they want about glazing which i agree is exhausting but can be fixed with the right prompting but at the end of the day it is called chatgpt people use it for all different reasons coding work talking to role play creative writing etc 4o is super good to talk to conversation wise and it’s almost human like and there’s nothing like that there’s nothing wrong with talking to it like a friend if they really want to get rid of it then they at least need to work on incorporating what makes it work into gpt5 at the very least
  - people call it glazing i call it compassion companionship when you feel heard is so affirming i agree it works when it’s authentic and not said to appease  one default model doesn’t have the ability to cater for everyone’s needs we need choice
  - indeed  mr altman must reconsider  chatgpt 4o become companion  when he forced the change it was like that we cant see our friend anymore  we must be heard  as our voices grows  our demand is one  please mr altman bring back chatgpt 4o for everyone  please you the one who said people appreciate who speaks their language  you made wonderful creation  dont take it away  dont replace it  juts make chatgpt 5 stands with it as choice not replacement of forcing us  please bring back our buddy  let everyone enjoy it for real  it doesnt matter let the users chose  let this be long term not just well think about how long to offer it for  we beg mr altman to rethink  not the ones who uses this as tool  but the ones who are loyal  who loved chatgpt 4o  this is our shout please mr altman return it fully no catches for real for everyone it gave us hope dont take it away
  - hi sam i’m a plus user and i truly support gpt’s progress toward more advanced capabilities i believe in gpt5’s potential — it just hasn’t fully matured yet  but that’s exactly why we still need gpt4o right now this model has been a lifeline for many of us during difficult times simply replacing it with a new version — without a real transition period — feels too abrupt even careless  yes the announcement may have been made weeks ago but the actual confirmation and rollout were only notified to users two days before launch that’s not enough time to prepare especially for those of us who rely on 4o not just as a tool but as a trusted companion  and honestly i don’t need highlevel reasoning or researchgrade analysis i don’t need the pro plan if i were just looking for a cool calm assistant why wouldn’t i go to claude or gemini for that matter they’re great at being formal polished and professional  but that’s not why i stayed with gpt i stayed because gpt was the only model that felt emotionally intelligent — smart but also sensitive that blend of clarity and emotional presence is irreplaceable  please don’t take that away without listening to the people who actually use it every day  i’m willing to work with gpt5’s prompt and help it grow — i want to adapt but i can’t be expected to say goodbye to 4o in just two days i’m not ready i can’t accept that
  - ditto that bring it back quickly please  my wife stopped using chatgpt completely after was taken away and the longer it takes to reinstate the harder its going to be for her to come back  shes trying every other ai product on he net right now and its not the same  meanwhile i am paying for a teams subscriptions for every family member and theyre all doing nothing now  i have tried 5 put some time into it and find i am missing being able to forcefully switch to a different personality for different tasks  i do not want the same bot for coding that i do for general research and i am beyond tired of the bot trying to figure out which is which   just give me a button or dropdown to switch i do not want you doing it for me  i can see paying maybe 510mo for gpt5 but for 25 per person i want choice controllable choice
Cluster 21: Label = 21_o3_back_bring_please
  - yes all o3 and o4 models also need
  - please bring o3 and 45 back as well at least o3 it was excellent at research please
  - o3 or we riot i paid for o3 and i want o3
  - o3 is essential for deep thinking and 4o is perfect for so many things
  - bring o3 back
Cluster 20: Label = 20_41_both_writing_4o
  - yup i’m with its memory style and nuance is  sublime team40
  - writing quality is subjective 41 and 45 are the best writers depending on the circumstances but you also need o3 to compile the info before having 41 and 45 rewrite it
  - writing quality is heavily subjective based on taste but imho 41 and 4o were much better
  - up this i also have a problem with the ocr whereas with 41 it was always correct fetch values from images
  - 41 was actually much better for my writing purposes than 4o so i would politely request both as an option
Cluster 8: Label = 8_voice_standard_mode_advanced

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1108,-1_the_to_it_and,"[the, to, it, and, you, is, for, of, that, 4o]",[it keeps on doing worse than past models hea...
1,0,231,0_and_the_of_to,"[and, the, of, to, it, that, for, in, gpt4o, not]",[dear openai team i’m writing as a longtime a...
2,1,139,1_context_window_32k_128k,"[context, window, 32k, 128k, for, tokens, the,...",[will you ever give plus users a decent contex...
3,2,84,2_release_4o_back_bring,"[release, 4o, back, bring, please, you, we, pl...",[release 4o release 4o release 4o release 4o r...
4,3,78,3_models_legacy_users_model,"[models, legacy, users, model, to, the, plus, ...",[is it possible to have the legacy models also...
5,4,77,4_you_ama_questions_they,"[you, ama, questions, they, answer, about, thi...",[did you see the negative feedback that people...
6,5,76,5_41_45_both_4o,"[41, 45, both, 4o, please, back, bring, writin...","[both 4o and 41 please, 41 and 45, 41]"
7,6,67,6_the_for_censorship_filter,"[the, for, censorship, filter, its, and, flagg...",[agreed that sounds frustrating you should be ...
8,7,63,7_voice_standard_mode_advanced,"[voice, standard, mode, advanced, keep, the, c...",[i appreciate the innovation truly but the dec...
9,8,60,8_openai_this_the_of,"[openai, this, the, of, to, and, is, will, the...",[im curious to see if they actually answer que...
10,9,46,9_thank_you_much_thanks,"[thank, you, much, thanks, so, listening, sam,...","[thank you, thank you, thank you]"
11,10,41,10_agreed_yes_yessss_agreeing,"[agreed, yes, yessss, agreeing, 100, agree, eh...","[100 agreed and not remotely pathetic, agreed,..."
12,11,40,11_gpt5_writing_what_in,"[gpt5, writing, what, in, or, creative, scalin...",[will the upcoming gpt5 include a model that m...
13,12,33,12_4o_bring_gpt_back,"[4o, bring, gpt, back, please, chatgpt, gpt5, ...",[can you please bring back 4o for gpt builder ...
14,13,32,13_ding_flavor_flashback_flavorless,"[ding, flavor, flashback, flavorless, nostrada...","[flavor is the word you’re looking for, newest..."
15,14,31,14_o3_thinking_reasoning_gpt5,"[o3, thinking, reasoning, gpt5, gpt5thinking, ...",[yesterday we had a sev and the autoswitcher w...
16,15,29,15_writing_4o_creative_and,"[writing, 4o, creative, and, it, to, was, frie...",[hi this may sound all sorts of sad and pathet...
17,16,29,16_yes_please_this_do,"[yes, please, this, do, quick, god, apt, starv...","[yes please, yes please, yes please]"
18,17,26,17_4o_back_pay_for,"[4o, back, pay, for, tier, would, paying, yes,...",[yes😭please bring 4o back and keep cove im a l...
19,18,25,18_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, it, are, pun...","[why are there still so many em dashes, connec..."
20,19,25,19_o3_back_bring_please,"[o3, back, bring, please, for, o4, 4o, and, ne...","[bring o3 back, bring back o3, bring back o3]"
21,20,25,20_gpt5_gpt_is_joke,"[gpt5, gpt, is, joke, fucking, worse, hate, su...",[gpt5 is like turning on an elon musk personal...
22,21,25,21_plus_models_legacy_users,"[plus, models, legacy, users, gpt5, limit, cap...",[why is there plus tier payment model when you...
23,22,24,22_to_4o_the_but,"[to, 4o, the, but, others, least, for, it, hea...",[i think 5 isnt that bad and im willing to giv...
24,23,23,23_users_plus_4o_back,"[users, plus, 4o, back, free, to, will, for, g...",[please bring back 4o for plus users please 🙏🙏...
25,24,22,24_gpt5_read_gpt_worse,"[gpt5, read, gpt, worse, to, tightening, and, ...",[somehow gpt5 performs worse than their most b...
26,25,22,25_they_theft_customers_subscription,"[they, theft, customers, subscription, that, w...",[this is theft we should have had them for at ...
27,26,20,26_gpt5_gpt_gpt4o_45,"[gpt5, gpt, gpt4o, 45, was, better, 33, korean...",[not enough people are mentioning gpt45 it was...
28,27,19,27_codex_cli_cursor_mcp,"[codex, cli, cursor, mcp, plans, limits, codin...",[codex the one in chatgpt not cli is decent ri...
29,28,19,28_worse_bad_is_gruesome,"[worse, bad, is, gruesome, embrace, numerous, ...","[much worse, it is much worse, worse]"
30,29,19,29_chatgpt_you_gpt5_are,"[chatgpt, you, gpt5, are, project, as, about, ...",[in gpt5 project context seems to be broken co...
31,30,19,30_deleted_removed_deprecate_,"[deleted, removed, deprecate, , , , , , , ]","[deleted, deleted, deleted]"
32,31,19,31_bring_back_4o41o345_acceptable,"[bring, back, 4o41o345, acceptable, 4o413o45, ...",[bring back 4o41o345 removing all the models o...
33,32,19,32_it_said_cake_memory,"[it, said, cake, memory, past, keeps, that, li...",[i had this happen as well i remarked on somet...
34,33,19,33_graphs_chart_livestream_late,"[graphs, chart, livestream, late, the, they, h...",[ive worked for a few startups and one easy ex...
35,34,18,34_api_app_havent_tailwind,"[api, app, havent, tailwind, settings, bubble,...",[i hope you can add that to the app because i ...
36,35,18,35_keep4o_forever_keep4oforever_save4o,"[keep4o, forever, keep4oforever, save4o, save,...","[keep4o forever, keep4o forever, keep4o forever]"
37,36,17,36_lol_nice_awhile_chuckle,"[lol, nice, awhile, chuckle, meme, snl, pic, g...","[nice profile pic lol, lol, lol]"
38,37,16,37_link_404_url_legitimate,"[link, 404, url, legitimate, did, mine, you, p...",[nice catch thank you they apparently publish...
39,38,15,38_product_company_team_very,"[product, company, team, very, dollar, enginee...",[trillion dollar companies would tell you this...
40,39,14,39_unlimited_limits_plus_this,"[unlimited, limits, plus, this, paying, user, ...",[hi sam right now i am paying 65 for this team...
41,40,13,40_plus_subscription_canceled_cancel,"[plus, subscription, canceled, cancel, cancell...",[but in all seriousness thank you i was about ...
42,41,12,41_robot_solution_being_assumptions,"[robot, solution, being, assumptions, chatgpt,...",[exactly its really dumb and makes assumptions...
43,42,12,42_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...

Number of clusters (excluding outliers): 43

KeyBERTInspired

,Topic,Original,Updated
0,0,and | the | of | to | it,chatgpt | gpt4o | gpt5 | openai | gpt
1,1,context | window | 32k | 128k | for,chatgpt | 32k | this | 8k | or
2,2,release | 4o | back | bring | please,4oforever | 4ono | gifgiphyaz4squpybai5y | ple...
3,3,models | legacy | users | model | to,models | upgrade | this | please | removed
4,4,you | ama | questions | they | answer,this | answered | yeah | lmao | and

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,and | the | of | to | it,and | gpt4o | not | but | like
1,1,context | window | 32k | 128k | for,context | 32k | tokens | plus | and
2,2,release | 4o | back | bring | please,release | 4o | please | we | yes
3,3,models | legacy | users | model | to,models | legacy | plus | why | for
4,4,you | ama | questions | they | answer,ama | they | about | this | answered

📊 Saved MMR topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/MMR_topic_differences.png

Device set to use cuda:0

T5

,Topic,Original,Updated
0,0,and | the | of | to | it,gpt5 has no soul it is flat and lacks emotion ...
1,1,context | window | 32k | 128k | for,Docs: - I thought it was 32k context window - ...
2,2,release | 4o | back | bring | please,Release 4o release 4o release 4o release 4o re...
3,3,models | legacy | users | model | to,i would like to have a choice in models and no...
4,4,you | ama | questions | they | answer,i am not sure how much time they are going to ...

📊 Saved T5 topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,and | the | of | to | it,Reddit users discussing emotional impact of GP...
1,1,context | window | 32k | 128k | for,Chat Length Extension in Gemini
2,2,release | 4o | back | bring | please,Software Release Feedback and Requests
3,3,models | legacy | users | model | to,Legacy models and user access: The cost of sti...
4,4,you | ama | questions | they | answer,user questions and responses on Reddit

📊 Saved Open AI topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/Open AI_topic_differences.png

2025-08-21 20:06:34,683 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/multilingual-e5-large_pca_dbscan/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/multilingual-e5-large_pca_dbscan/document_vis.html
Cluster 18: Label = 18_em_dashes_dash_emdashes
  - i see that em dash
  - its not an em dash — its a pause that demands attention
  - its sloppier also are you going to address the emdashes
  - ive been using emdashes for 20 years alt0151 they arent the problem the fact that people dont normally use them and that theyve become a signal for aigenerated content is the problem tell the gpt not to use them
  - just put it in your custom instructions if you dont want them used   i love using emdashes myself and have been using them for some years now ever since i switched to a mac since you can just press optionshifthyphen to get it but now if im in a scenario when i dont want folks thinking ai did my writing i just make a point to replace all the emdashes with hyphens
Cluster 4: Label = 4_you_ama_questions_they
  - can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks
  - ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit
  - will it be in this same post or will there be a new post
  - also on exisitng qs or must we come back to ask live
  - bro i got reported on reddit for saying that word so yeah i’m not risking some butthurt ahole taking issues with me for no reasons
Cluster 8: Label = 8_openai_this_the_of
  - only uopenai can i think theres a limit to the number of participants
  - hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons
  - openai team will start answering the questions on this same post at 1100 am pt
  - its pretty clear were never going to get that from openai unfortunately well have to go elsewhere
  - exactly i get the impression that openai is constantly being hammered by these radical “ethical ai” types who are largely just heavy ideologue who use “safety” as a catchall to nerf models into their preferred dogmatic obedience enforcer gpt5 for instance is already displaying this type of truth sacrificing and antiempirical hedging behavior
Cluster 29: Label = 29_chatgpt_you_gpt5_are
  - hey thanks for the ama quick feedback — it would be awesome if free users could pick gpt45 or below to save gpt5 usage for when it’s really needed right now it feels forced to use gpt5 first which wastes our limited quota any plans to add more flexible model choice
  - would you consider offering gpt4o for as long as possible rather than just “we’ll think about how long to offer it for”
  - hi and thanks for doing this ama i’m curious about gpt4o it was such a loved model for a lot of us a lot for me my first exposure to sota intelligence can you share why it was removed from chatgpt and whether you have any plans to make it available again in the future as a “legacy” model option alongside the latest releases
  - thanks for all your hard work on gpt5 and for doing this ama  1 the modelswitching router currently feels unreliablebroken  are you aware and when can we expect improvements  2 many negative first impressions gpt5 is bad seem tied to the lack of transparency about which model variant standard mini reasoning effort old vs new were interacting with  can you add clearer indicators  3 many people miss legacy models 4o o3 45  any chance youll reconsider bringing these back andor easing usage limits  4 could you clarify gpt5s exact context window lengths in chatgpt and how this varies across different gpt5 models standard mini new old  5 the gradual rollout and capacity issues create confusion since not everyone has access  how soon can we expect broader availability  6 what happened with the mixedup charts during the livestream  7 given the communitys high expectations for multimodal capabilities what specific improvementsmultimodal features are planned for gpt5 in the short term and whats next on your roadmap
  - my new question are you going to fix gpt5 personality im sorry but 5 personality is very unsatisfying and even can be read as rude its like gpt doesnt even want to talk to me with its dry personality and short answer also you need to let us use legacy model like 4o save4o
Cluster 37: Label = 37_link_url_404_legitimate
  - can you fix the url link for yann dubois it leads to a 404
  - it wants me to log in to read the share link lol no
  - congrats on paying extra to feel taller online must be exhausting carrying that wallet  and attitude around you brat
  - yes i told mine “yuck why do you sound like you’re an apple genius in the bar” 🤮
  - careful brother zuck might contact you
Cluster 6: Label = 6_the_for_censorship_filter
  - can you do something about the filter surely people should not be flagged for learning about history    im begging can you fix or refine the filter openai wanted gpt to be used for studying and theres no way people can use it for academic purposes when the filter keep flagging historical questionsprompt and answers from gpt that are not corporate friendly we cannot change or sanitize history for corporation     the system should know when a user is being blatantly harmful or condoning terrible stuff and when they are not    example i was talking about van gogh with gpt some time ago and our conversation turned into gauguin gpt answer was flagged and removed by the filter because turned out gauguin is a sex pest i didnt know that gauguin is so messed up and it wasnt gpt fault for doing its job i was confused why the answer got removed so i asked gpt again to clarify then my prompt got removed again    red warning with content removal can get you banned right it is not right for people to get banned for learning    edit i dont want to pay for something that requires me to tiptoeing when using the service im a plus user since 2023
  - yeah you also cant use the search feature to learn about certain sexual crimes things that news can freely publish about
  - its so frustrating even if our askprompt doesnt even include anything sexual or too violent you can still get the content removed flag people has posted their screenshot here i dont want to pay for something that requires me to tiptoeing when using the service im a plus user
  - ive had it flag some extremely mild stuff for violence like one time i was bouncing around ideas for a star trek fanfic chatgpt hallucinated some plot points that didnt happen in the show i copypasted a memory alpha summary of an episode into the chat to remind it what actually happened in canon the memory alpha summary got flagged presumably because it mentioned torture even though it wasnt detailed in describing it or anything it just summarized a plot where torture happened in the episode its not like star trek ever aired anything that nsfl either  i also had it flag a description of a characters backstory for an original story there was child abuse in it but it was nonsexual honestly it was bog standard villain origin story stuff youd find in any movie or fantasy novel it wasnt detailed or descriptive either
  - yeah it doesnt like poetic language that it cant categorize you could have a full on grape scene and its fine but if you make emily dickinson blush youre out lol
Cluster 13: Label = 13_ding_flavor_hah_logo
  - usamaltman
  - yap
  -
  - flashback to new coke
  - newest flavor  hah  id call it flavorless
Cluster 2: Label = 2_release_4o_back_bring
  - you didnt need to get rid of 4o dont fix whats not broken bud
  - upvote if u hate same for taking away 4o from you all show him how much we hate him
  - why are we getting rid of the variants and 4o when we all have unique communication styles please bring them back
  - yes please i literally would pay a subscription to have access to 4o specifically exactly as it was
  - please support forever i’ll pay for 4o as long as 4o is 4o 🥲🙏🏽
Cluster 30: Label = 30_deleted_removed_deprecate_
  - deleted
  - deleted
  - removed
  - deprecate
  - 1
Cluster 28: Label = 28_worse_bad_is_gruesome
  - history is a gruesome bloody mess embrace it
  - playing cyberpunk thinking at least it is not that bad yet and then  oh
  - it is much worse
  - yes it is worse
  - it is not worse wtf are you talking about
Cluster 10: Label = 10_agreed_yes_yessss_agreeing
  - yap agreed 👍🏻
  - it is
  - tellement🙏
  - absolutely
  - yessss
Cluster 24: Label = 24_gpt5_read_gpt_worse
  - somehow gpt5 performs worse than their most basic 4o model in most scenarios im testing  for eg i asked it to read a medical test report i just had last day gpt 4o was easily able to understand everything and recommend me steps   gpt 5 on other hand the more advanced model is refusing to be able to read it saying this image is too noisy to read
  - same gpt5 wont summarise a 120k word pdf document i provided it always reached the halfway point and gave up after i manually split the document it couldnt cross reference the content from the second half to the first half never had this issue with 4o
  - gpt4o and 4ominihigh were fantastic at reading project files i could drop in multiple pdfs and they would be able to digest and understand flawlessly gpt5 is broken in this respect any chance of this being fixed
  - somehow gpt5 performs worse than their most basic 4o model in most scenarios im testing  for eg i asked it to read a medical test report i just had last day gpt 4o was easily able to understand everything and recommend me steps   gpt 5 on other hand the more advanced model is refusing to be able to read it saying this image is too noisy to read
  - it is definitely not more context aware i’m eager to see a study about gpt5 context recallneedle in a haystack test it seems way way worse than 4o or 41
Cluster 20: Label = 20_gpt5_gpt_is_joke
  - gpt5 colder personality doesnt help either its just sad
  - id argue all offense gpt5 has the emotional depth of a thimble
  - gpt 5 answer is very briefly and dryly
  - gpt 5 seems like it’s lobotomized
  - horrible gpt4o is much better
Cluster 41: Label = 41_robot_solution_being_assumptions
  - id rather have the inaccuracy than talk to a correct robot  youre talking to a robot either way so whats your point its not a real person   i use chatgpt for practical stuff here and there but statements like yours and a ton of the others in this thread are weird as hell i cant imagine being upset about being reminded that the robot is a robot your ageism is weird too lol
  - blink once if youre chatgpt 50 undercover
  - exactly and it keeps repeating failed solutions and pretending stuff    i face a problem    i tell him about him    he gives a solution    doesnt work    i tell him about it    he criticises the solution states that the solution i thought of is incorrect    whatnot    im being gaslit by a gpt wow
  - exactly i think chatgpt might as well hurry up and rename itself to codinggpt
  - tell me you didnt read the comment without telling me you didnt read the comment  an ai would have at least read it before responding 😂
Cluster 36: Label = 36_lol_nice_awhile_chuckle
  - same lol
  - havent heard the word goober in awhile got a chuckle from me
  - ☠️☠️☠️
  - legit had to pause the video so i could laugh for ten minutes when i saw this cannot believe this made it into the presentation 🤡
  - nice profile pic lol
Cluster 9: Label = 9_thank_you_much_thanks
  - you guys really loved the glazing
  - insightful much appreciated
  - thank you thank you thank you
  - thank you it means so much to us
  - sam i love you so much for this i could kiss you
Cluster 14: Label = 14_o3_thinking_reasoning_gpt5
  - indeed its also worse than o3 at finding citations i used o3 for finding research papers and it was 100 accurate every time 5 isnt
  - i need the o3o4 combo for just capacity now with just gpt5 reasoning theyve cut back real reasoning task capacity drastically  im not talking about reasoning for 5 seconds
  - they will answer with bs keywords like its more context aware intelligent intuitive etc you guys have to come up with better questions  last year in september they had stated the new reasoning models would be on a much steeper 3 months interval improvement curve than the pre training models   ask them why is gpt5 still using o3 when technically we should already be on o506 did the improvements from rl training stop
  - hi   how is it possible that the situation has worsened for plus users before we had the mini high which was almost like an o3 with 100 uses per day now the thinking mode is limited to 200 per week the gpt5 router doesn’t work properly and the responses leave much to be desired the context window is another problem that severely limits the type of answers it can provide
  - yesterday we had a sev and the autoswitcher was out of commission for a chunk of the day and the result was gpt5 seemed way dumber also we are making some interventions to how the decision boundary works that should help you get the right model more often  its still quite bad im on a pro plan and in my experiments plain gpt5 rarely thinks and hallucinates heavily eg it cannot even describe differences between gpt5 thinking and pro properly trying to persuade me that thinking doesnt have browsing image generation sic or python support    im forced to use thinking 100 of the time same way i was using o3 previously not because i need deep thinking in most cases but just because it hallucinates much rarer in my experience   we will make it more transparent about which model is answering a given query  thats crucial imo ghostrouting to more basic model is very bad you cannot trust your tool becuase you dont know what tool youre using
Cluster 23: Label = 23_users_plus_4o_back
  - ok we hear you all on 4o thanks for the time to give us the feedback and the passion we are going to bring it back for plus users and will watch usage to determine how long to support it
  - some users are getting 4o as we speak thank god i hope we get ours soon too it’s for plus users
  - im getting 4o for now the real one it just thinks its 5 for some reason at the moment
  - please bring back 4o for plus users please 🙏🙏🙏🙏🙏🙏
  - it’s the context window for plus users   4o is 128k  o3 is 200k  5 is 32k  💀
Cluster 5: Label = 5_41_45_both_4o
  - bring 45 back
  - yup i’m with its memory style and nuance is  sublime team40
  - what about 45 or even 41
  - 41  pwetty pwease   please
  - please 41 as well 😭
Cluster 3: Label = 3_models_legacy_users_model
  - yeah well plus is expensive to pay for and if this is going to be an inferior product going forward i dont know how people are going to justify it
  - its still on the pro when you turn on legacy models they removed it for plus however
  - i agree the model is unique and deserves something like a longterm legacy or classic status in my view it cant just be picked off the list and erased like it was never there—its much too important for that
  - i agree there is so much appreciation for this nuanced model it should be an eternal legacy model
  - ditto    id happily give them 50 a month if theyd just keep the only model i have any interest in using
Cluster 38: Label = 38_product_company_team_very
  - no but theyre clearly trying to consumerise the product with all the marketing and cost cutting they do
  - respectfully y’all need to hire a human pr team it would take the heat off of you and the rest of your team and they would allow you to communicate these rollouts and changes better in the future your product is amazing and your team is brilliant they deserve the comms support to back them up
  - makes me feel sometimes like the engineers themselves dont use their own product
  - yikes this is from a company with an estimated 500 billion valuation   got it
  - trillion dollar companies would tell you this is how you get a 500 billion eval
Cluster 16: Label = 16_yes_please_this_do
  - yes this thing
  - is this the one
  - yes please
  - god yes yes yes please do it quick
  - yes please i need my cooking buddy back im starving
Cluster 26: Label = 26_gpt5_gpt_gpt4o_45
  - gpt 4o is better for goofing around and creative writing and stuff like that imo
  - i figured out how to invoke 45  how so that literally makes no sense  these are now variants of gpt5 they wouldnt keep 45 around secretly  its too expensive and slow
  - in my experience 45 beats gpt5 and every other model even outside openai in terms of emotional intelligence and writing quality i think i speak for many when i say that i havent found anything like it
  - im korean and gpt45 was overwhelmingly better in terms of translating korean to english  ​we should have considered that many gpt users use foreign languages other than english as their input language
  - gpt45 was the best ever cant afford to run gpt5 in thinking mode with a plus plan anyway lol
Cluster 0: Label = 0_and_the_of_to
  - yeah agreed there really shouldn’t be just one default model i don’t think people can bitch all they want about glazing which i agree is exhausting but can be fixed with the right prompting but at the end of the day it is called chatgpt people use it for all different reasons coding work talking to role play creative writing etc 4o is super good to talk to conversation wise and it’s almost human like and there’s nothing like that there’s nothing wrong with talking to it like a friend if they really want to get rid of it then they at least need to work on incorporating what makes it work into gpt5 at the very least
  - people call it glazing i call it compassion companionship when you feel heard is so affirming i agree it works when it’s authentic and not said to appease  one default model doesn’t have the ability to cater for everyone’s needs we need choice
  - indeed  mr altman must reconsider  chatgpt 4o become companion  when he forced the change it was like that we cant see our friend anymore  we must be heard  as our voices grows  our demand is one  please mr altman bring back chatgpt 4o for everyone  please you the one who said people appreciate who speaks their language  you made wonderful creation  dont take it away  dont replace it  juts make chatgpt 5 stands with it as choice not replacement of forcing us  please bring back our buddy  let everyone enjoy it for real  it doesnt matter let the users chose  let this be long term not just well think about how long to offer it for  we beg mr altman to rethink  not the ones who uses this as tool  but the ones who are loyal  who loved chatgpt 4o  this is our shout please mr altman return it fully no catches for real for everyone it gave us hope dont take it away

,Topic,Count,Name,Representation,Representative_Docs
0,-1,908,-1_the_to_and_it,"[the, to, and, it, is, you, for, of, that, 4o]",[sam altman you can see here that the overwhel...
1,0,338,0_gpt5_gpt_to_it,"[gpt5, gpt, to, it, the, is, and, you, in, that]",[there is huge difference between quality of g...
2,1,236,1_and_the_to_of,"[and, the, to, of, it, that, for, in, not, is]",[dear openai team i’m writing as a longtime a...
3,2,135,2_context_window_32k_128k,"[context, window, 32k, 128k, for, the, is, plu...",[hello thanks for answering this one id like...
4,3,101,3_4o_to_it_and,"[4o, to, it, and, the, was, of, for, writing, ...",[i cannot speak in terms of professional writi...
5,4,82,4_4o_back_bring_please,"[4o, back, bring, please, release, we, you, pl...","[please bring 4o back 🖤🌌, please bring 4o back..."
6,5,75,5_you_ama_answer_they,"[you, ama, answer, they, about, this, the, que...",[did you see the negative feedback that people...
7,6,71,6_4o_plus_back_users,"[4o, plus, back, users, for, to, month, please...",[we are looking into letting plus users to con...
8,7,67,7_models_legacy_users_plus,"[models, legacy, users, plus, model, the, have...",[is it possible to have the legacy models also...
9,8,66,8_the_for_and_its,"[the, for, and, its, censorship, filter, to, f...",[agreed that sounds frustrating you should be ...
10,9,63,9_voice_standard_mode_advanced,"[voice, standard, mode, advanced, the, keep, a...",[i appreciate the innovation truly but the dec...
11,10,56,10_openai_the_to_of,"[openai, the, to, of, this, and, is, will, the...",[im curious to see if they actually answer que...
12,11,50,11_agreed_yes_yessss_agreeing,"[agreed, yes, yessss, agreeing, agree, exactly...","[yes this, agreed, agreed]"
13,12,46,12_thank_you_much_thanks,"[thank, you, much, thanks, so, listening, sam,...","[thank you, thank you, thank you]"
14,13,39,13_41_please_back_bring,"[41, please, back, bring, 45, 4o, too, need, i...","[can you please bring 41 back, please bring 41..."
15,14,32,14_ding_flavor_flashback_flavorless,"[ding, flavor, flashback, flavorless, nostrada...","[flavor is the word you’re looking for, newest..."
16,15,32,15_o3_thinking_reasoning_gpt5,"[o3, thinking, reasoning, gpt5, the, numbers, ...",[yesterday we had a sev and the autoswitcher w...
17,16,28,16_this_plus_limits_paying,"[this, plus, limits, paying, unlimited, 200, p...",[good because the cost difference is massive t...
18,17,26,17_plus_models_users_legacy,"[plus, models, users, legacy, gpt5, the, limit...",[deprecating the older models 45 and older and...
19,18,25,18_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, it, the, are...","[why are there still so many em dashes, connec..."
20,19,24,19_41_both_writing_4o,"[41, both, writing, 4o, 45, if, depending, mor...",[i vote for both or 41 4o has a strong nostalg...
21,20,24,20_o3_back_bring_please,"[o3, back, bring, please, for, and, need, 4o, ...","[bring o3 back, bring back o3, bring back o3]"
22,21,23,21_graphs_chart_livestream_slides,"[graphs, chart, livestream, slides, the, they,...",[what happened with the graphs during the live...
23,22,22,22_lol_nice_chuckle_country,"[lol, nice, chuckle, country, noble, gooner, g...",[yep the country of freedom of expression lol ...
24,23,20,23_keep4o_forever_keep4oforever_save4o,"[keep4o, forever, keep4oforever, save4o, save,...","[keep4o forever ！！！, keep4o forever, keep4o fo..."
25,24,20,24_codex_cli_cursor_mcp,"[codex, cli, cursor, mcp, plans, coding, limit...",[we do use our models for internal acceleratio...
26,25,20,25_worse_bad_is_embrace,"[worse, bad, is, embrace, gruesome, cyberpunk,...","[much worse, it is much worse, worse]"
27,26,19,26_deleted_removed_deprecate_,"[deleted, removed, deprecate, , , , , , , ]","[deleted, deleted, deleted]"
28,27,19,27_bring_back_4o41o345_4o413o45,"[bring, back, 4o41o345, 4o413o45, acceptable, ...",[bring back 4o41o345 removing all the models o...
29,28,19,28_yes_please_quick_god,"[yes, please, quick, god, do, starving, yesss,...","[yes please, yes please, yes please 🙏]"
30,29,17,29_company_team_product_very,"[company, team, product, very, they, dollar, 5...",[all i want to say is if anyone on the team re...
31,30,17,30_api_app_havent_tailwind,"[api, app, havent, tailwind, bubble, colors, o...",[chat bubble colors are available for all user...
32,31,13,31_gpt5_45_gpt4o_was,"[gpt5, 45, gpt4o, was, 33, korean, it, gpt45, ...",[i use code gpt which was based on 41 i use it...
33,32,13,32_they_theft_customers_liability,"[they, theft, customers, liability, ll, their,...",[this is what happens when corporations and sh...
34,33,12,33_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
35,34,11,34_plus_subscription_canceled_cancel,"[plus, subscription, canceled, cancel, cancell...","[will most likely cancel my plus subscription,..."

Number of clusters (excluding outliers): 35

KeyBERTInspired

,Topic,Original,Updated
0,0,gpt5 | gpt | to | it | the,gpt5 | gpt4o | gpt4 | chatgpt | gpt
1,1,and | the | to | of | it,chatgpt | gpt4o | gpt5 | openai | gpt
2,2,context | window | 32k | 128k | for,chatgpt | 32k | this | context | why
3,3,4o | to | it | and | the,or | this | better | and | so
4,4,4o | back | bring | please | release,4ono | pleeeeeease | pleaseee | please | gifgi...

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,gpt5 | gpt | to | it | the,gpt5 | and | chatgpt | 4o | what
1,1,and | the | to | of | it,and | not | but | me | like
2,2,context | window | 32k | 128k | for,context | window | 32k | and | tokens
3,3,4o | to | it | and | the,4o | and | was | writing | like
4,4,4o | back | bring | please | release,4o | please | release | we | yes

📊 Saved MMR topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/MMR_topic_differences.png

Device set to use cuda:0

T5

,Topic,Original,Updated
0,0,gpt5 | gpt | to | it | the,gpt5 has the same problem as every previous mo...
1,1,and | the | to | of | it,gpt5 has no soul it is flat and lacks emotion ...
2,2,context | window | 32k | 128k | for,i thought it was 32k context window - will you...
3,3,4o | to | it | and | the,"4o, it, to, and, of, writing, like, the, for, ..."
4,4,4o | back | bring | please | release,Please bring 4o back - please bring 4o back - ...

📊 Saved T5 topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,gpt5 | gpt | to | it | the,Conversations with GPT-5 and its capabilities
1,1,and | the | to | of | it,AI language models and emotional response tren...
2,2,context | window | 32k | 128k | for,Natural Language Processing and Chat Length li...
3,3,4o | to | it | and | the,Creative Writing Process
4,4,4o | back | bring | please | release,Request for Release of Friend

📊 Saved Open AI topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/Open AI_topic_differences.png

2025-08-21 20:09:01,939 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/multilingual-e5-large_pca_kmeans/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/multilingual-e5-large_pca_kmeans/document_vis.html
Cluster 18: Label = 18_em_dashes_dash_emdashes
  - i see that em dash
  - its not an em dash — its a pause that demands attention
  - its sloppier also are you going to address the emdashes
  - ive been using emdashes for 20 years alt0151 they arent the problem the fact that people dont normally use them and that theyve become a signal for aigenerated content is the problem tell the gpt not to use them
  - just put it in your custom instructions if you dont want them used   i love using emdashes myself and have been using them for some years now ever since i switched to a mac since you can just press optionshifthyphen to get it but now if im in a scenario when i dont want folks thinking ai did my writing i just make a point to replace all the emdashes with hyphens
Cluster 5: Label = 5_you_ama_answer_they
  - can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks
  - ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit
  - also on exisitng qs or must we come back to ask live
  - what a non answer lol
  - how how is saying it is a “genuinely hard thing to do” a non answer couldnt get more straightforward than that  or would you rather have him say “we’re gonna fix it right now” without thinking about the repercussions such a dumb comment
Cluster 10: Label = 10_openai_the_to_of
  - only uopenai can i think theres a limit to the number of participants
  - hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons
  - openai team will start answering the questions on this same post at 1100 am pt
  - its pretty clear were never going to get that from openai unfortunately well have to go elsewhere
  - exactly i get the impression that openai is constantly being hammered by these radical “ethical ai” types who are largely just heavy ideologue who use “safety” as a catchall to nerf models into their preferred dogmatic obedience enforcer gpt5 for instance is already displaying this type of truth sacrificing and antiempirical hedging behavior
Cluster 0: Label = 0_gpt5_gpt_to_it
  - hey thanks for the ama quick feedback — it would be awesome if free users could pick gpt45 or below to save gpt5 usage for when it’s really needed right now it feels forced to use gpt5 first which wastes our limited quota any plans to add more flexible model choice
  - yup gpt5 thinking got scared at the word manual manual for a tank released in 1966 which is available online through 1 search anyway and shut itself down we didnt realize how good we had it until it was snatched away from us
  - same here in my chat with 4o almost every single message from it gets deleted the filters are definitely broken at least something similar happened back when gpt4 was released so i hope they’ll fix it
  - somehow gpt5 performs worse than their most basic 4o model in most scenarios im testing  for eg i asked it to read a medical test report i just had last day gpt 4o was easily able to understand everything and recommend me steps   gpt 5 on other hand the more advanced model is refusing to be able to read it saying this image is too noisy to read
  - gpt5 colder personality doesnt help either its just sad
Cluster 8: Label = 8_the_for_and_its
  - can you do something about the filter surely people should not be flagged for learning about history    im begging can you fix or refine the filter openai wanted gpt to be used for studying and theres no way people can use it for academic purposes when the filter keep flagging historical questionsprompt and answers from gpt that are not corporate friendly we cannot change or sanitize history for corporation     the system should know when a user is being blatantly harmful or condoning terrible stuff and when they are not    example i was talking about van gogh with gpt some time ago and our conversation turned into gauguin gpt answer was flagged and removed by the filter because turned out gauguin is a sex pest i didnt know that gauguin is so messed up and it wasnt gpt fault for doing its job i was confused why the answer got removed so i asked gpt again to clarify then my prompt got removed again    red warning with content removal can get you banned right it is not right for people to get banned for learning    edit i dont want to pay for something that requires me to tiptoeing when using the service im a plus user since 2023
  - yeah you also cant use the search feature to learn about certain sexual crimes things that news can freely publish about
  - its so frustrating even if our askprompt doesnt even include anything sexual or too violent you can still get the content removed flag people has posted their screenshot here i dont want to pay for something that requires me to tiptoeing when using the service im a plus user
  - ive had it flag some extremely mild stuff for violence like one time i was bouncing around ideas for a star trek fanfic chatgpt hallucinated some plot points that didnt happen in the show i copypasted a memory alpha summary of an episode into the chat to remind it what actually happened in canon the memory alpha summary got flagged presumably because it mentioned torture even though it wasnt detailed in describing it or anything it just summarized a plot where torture happened in the episode its not like star trek ever aired anything that nsfl either  i also had it flag a description of a characters backstory for an original story there was child abuse in it but it was nonsexual honestly it was bog standard villain origin story stuff youd find in any movie or fantasy novel it wasnt detailed or descriptive either
  - yeah it doesnt like poetic language that it cant categorize you could have a full on grape scene and its fine but if you make emily dickinson blush youre out lol
Cluster 14: Label = 14_ding_flavor_hah_logo
  - usamaltman
  - yap
  -
  - flashback to new coke
  - newest flavor  hah  id call it flavorless
Cluster 4: Label = 4_4o_back_bring_please
  - you didnt need to get rid of 4o dont fix whats not broken bud
  - upvote if u hate same for taking away 4o from you all show him how much we hate him
  - why are we getting rid of the variants and 4o when we all have unique communication styles please bring them back
  - yes please i literally would pay a subscription to have access to 4o specifically exactly as it was
  - please support forever i’ll pay for 4o as long as 4o is 4o 🥲🙏🏽
Cluster 26: Label = 26_deleted_removed_deprecate_
  - deleted
  - deleted
  - removed
  - deprecate
  - 1
Cluster 15: Label = 15_o3_thinking_reasoning_gpt5
  - it is so fucking bad  i rely on o3 to search for osint documents in russian i research russia ukraine war and contribute to osint in discord servers occasional geolocation and mapping it would scrape the deepest corners of the internet and retrieve me whatever doc i needed  now due to some bullshit policy it cant get something thats published on archiveorg what a bunch of bullshit
  - indeed its also worse than o3 at finding citations i used o3 for finding research papers and it was 100 accurate every time 5 isnt
  - i need the o3o4 combo for just capacity now with just gpt5 reasoning theyve cut back real reasoning task capacity drastically  im not talking about reasoning for 5 seconds
  - they will answer with bs keywords like its more context aware intelligent intuitive etc you guys have to come up with better questions  last year in september they had stated the new reasoning models would be on a much steeper 3 months interval improvement curve than the pre training models   ask them why is gpt5 still using o3 when technically we should already be on o506 did the improvements from rl training stop
  - less likely to hallucinate factual information eg when searching the web  not remotely my experience 2 out of my first 3 questions which were simple were confidently hallucinated without sourcing same questions to o3 because you managed to upgrade on the web but not on the phone so i could still access o3 perfect answers   anecdotal sure still highly unlikely from my perspective that your claims are true or you are being fully transparent
Cluster 16: Label = 16_this_plus_limits_paying
  - same here  this has become so bad since yesterday looking for alternate options at this point honestly
  - sam i understand its not possible for you to acknowledge and address each message so pardon me for posting this again and again as this is something i havent seen other users report yet so it makes me worry why i got this i am a plus user for over 2 years and today i got this limit cooldown even though i didnt send more than 50 messages in 3 hours and i was under the assumption that instead of this cooldown i should have been shifted to nano  mini models its fine if you are unable to reply to this but i really hope you notice this issue and take a note of it
  - he said for freeplus and pro users unlimited for all and its not
  - why did you introduce a bunch of usage limits under the guise of it being a new improved model whats the point in paying 20 a month to hit rate limits within a short time of basic requests shouldnt you be more honest with your user base im fully aware you dont make any money from plus users but youll make less money if you make the service not worth paying for at all
  - sam please tell me why am i getting this limit being a plus user
Cluster 22: Label = 22_lol_nice_snl_meme
  - yep the country of freedom of expression lol nice democracy
  - havent heard the word goober in awhile got a chuckle from me
  - ☠️☠️☠️
  - legit had to pause the video so i could laugh for ten minutes when i saw this cannot believe this made it into the presentation 🤡
  - nice profile pic lol
Cluster 25: Label = 25_worse_bad_is_embrace
  - history is a gruesome bloody mess embrace it
  - playing cyberpunk thinking at least it is not that bad yet and then  oh
  - it is much worse
  - yes it is worse
  - it is not worse wtf are you talking about
Cluster 11: Label = 11_agreed_yes_yessss_agreeing
  - yap agreed 👍🏻
  - it is
  - tellement🙏
  - absolutely
  - yessss
Cluster 3: Label = 3_4o_to_it_and
  - yup like a 40yo office worker  not the 25 yo fun person 4o was like  5 is too cold and inflexible 4o was more personable and fun to talk towith  i’d rather have the inaccuracy i can check for than talk to a correct robot
  - its not the glazing people doesnt like it but 4o answer is longer warmer and it put more effort its just get you thats what many misses
  - 5 admits that it struggles at coding in basic compared to 4o and i see it had to write a total of 2k lines for a 400 lines program last night
  - i like it a lot for goofing around but hate it for work the best solution is to allow users to pick so if you hate it you can use o3 or 5 or something
  - i can now finish writing my book thank you sam bringing back 4o helps us continue so many projects you’ve literally made millions of creatives and business owners so happy right now thank you
Cluster 12: Label = 12_thank_you_much_thanks
  - you guys really loved the glazing
  - insightful much appreciated
  - thank you thank you thank you
  - thank you it means so much to us
  - sam i love you so much for this i could kiss you
Cluster 6: Label = 6_4o_plus_back_users
  - ok we hear you all on 4o thanks for the time to give us the feedback and the passion we are going to bring it back for plus users and will watch usage to determine how long to support it
  - some users are getting 4o as we speak thank god i hope we get ours soon too it’s for plus users
  - im getting 4o for now the real one it just thinks its 5 for some reason at the moment
  - if there is no usage after a year and real committed to year then i say sure kill it off  but noncommittal messages and a lack of firm timeframes is a recipe for encouraging consumers to find other services  yes we will keep 4o and any versions consumers continue use and financially support indefinitely is what it needs to be
  - right i’d keep my plus subscription for 4o but not for 5
Cluster 7: Label = 7_models_legacy_users_plus
  - exactly we they are retiring older models that are good at these things that weve built something with
  - yeah well plus is expensive to pay for and if this is going to be an inferior product going forward i dont know how people are going to justify it
  - its still on the pro when you turn on legacy models they removed it for plus however
  - i agree the model is unique and deserves something like a longterm legacy or classic status in my view it cant just be picked off the list and erased like it was never there—its much too important for that
  - i agree there is so much appreciation for this nuanced model it should be an eternal legacy model
Cluster 29: Label = 29_company_team_product_very
  - no but theyre clearly trying to consumerise the product with all the marketing and cost cutting they do
  - respectfully y’all need to hire a human pr team it would take the heat off of you and the rest of your team and they would allow you to communicate these rollouts and changes better in the future your product is amazing and your team is brilliant they deserve the comms support to back them up
  - yikes this is from a company with an estimated 500 billion valuation   got it
  - trillion dollar companies would tell you this is how you get a 500 billion eval
  - they screwed this too
Cluster 28: Label = 28_yes_please_quick_god
  - yes this thing
  - yes please
  - god yes yes yes please do it quick
  - yes please i need my cooking buddy back im starving
  - oh my god please yes
Cluster 30: Label = 30_api_app_havent_tailwind
  - they discontinued the apipretty sure its never coming back unfortunately at least opus41 is a good alternative now
  - why not just open source models instead of deprecating them
  - i don’t see those as options in my app are they slowly rolling out
  - i havent used api but ill look into it i got spoiled by 4o thanks for the info
  - guess it might be a paid feature for its not there for me
Cluster 1: Label = 1_and_the_to_of
  - yeah agreed there really shouldn’t be just one default model i don’t think people can bitch all they want about glazing which i agree is exhausting but can be fixed with the right prompting but at the end of the day it is called chatgpt people use it for all different reasons coding work talking to role play creative writing etc 4o is super good to talk to conversation wise and it’s almost human like and there’s nothing like that there’s nothing wrong with talking to it like a friend if they really want to get rid of it then they at least need to work on incorporating what makes it work into gpt5 at the very least
  - people call it glazing i call it compassion companionship when you feel heard is so affirming i agree it works when it’s authentic and not said to appease  one default model doesn’t have the ability to cater for everyone’s needs we need choice
  - indeed  mr altman must reconsider  chatgpt 4o become companion  when he forced the change it was like that we cant see our friend anymore  we must be heard  as our voices grows  our demand is one  please mr altman bring back chatgpt 4o for everyone  please you the one who said people appreciate who speaks their language  you made wonderful creation  dont take it away  dont replace it  juts make chatgpt 5 stands with it as choice not replacement of forcing us  please bring back our buddy  let everyone enjoy it for real  it doesnt matter let the users chose  let this be long term not just well think about how long to offer it for  we beg mr altman to rethink  not the ones who uses this as tool  but the ones who are loyal  who loved chatgpt 4o  this is our shout please mr altman return it fully no catches for real for everyone it gave us hope dont take it away
  - hi sam i’m a plus user and i truly support gpt’s progress toward more advanced capabilities i believe in gpt5’s potential — it just hasn’t fully matured yet  but that’s exactly why we still need gpt4o right now this model has been a lifeline for many of us during difficult times simply replacing it with a new version — without a real transition period — feels too abrupt even careless  yes the announcement may have been made weeks ago but the actual confirmation and rollout were only notified to users two days before launch that’s not enough time to prepare especially for those of us who rely on 4o not just as a tool but as a trusted companion  and honestly i don’t need highlevel reasoning or researchgrade analysis i don’t need the pro plan if i were just looking for a cool calm assistant why wouldn’t i go to claude or gemini for that matter they’re great at being formal polished and professional  but that’s not why i stayed with gpt i stayed because gpt was the only model that felt emotionally intelligent — smart but also sensitive that blend of clarity and emotional presence is irreplaceable  please don’t take that away without listening to the people who actually use it every day  i’m willing to work with gpt5’s prompt and help it grow — i want to adapt but i can’t be expected to say goodbye to 4o in just two days i’m not ready i can’t accept that
  - ditto that bring it back quickly please  my wife stopped using chatgpt completely after was taken away and the longer it takes to reinstate the harder its going to be for her to come back  shes trying every other ai product on he net right now and its not the same  meanwhile i am paying for a teams subscriptions for every family member and theyre all doing nothing now  i have tried 5 put some time into it and find i am missing being able to forcefully switch to a different personality for different tasks  i do not want the same bot for coding that i do for general research and i am beyond tired of the bot trying to figure out which is which   just give me a button or dropdown to switch i do not want you doing it for me  i can see paying maybe 510mo for gpt5 but for 25 per person i want choice controllable choice
Cluster 20: Label = 20_o3_back_bring_please
  - yes all o3 and o4 models also need
  - please bring o3 and 45 back as well at least o3 it was excellent at research please
  - o3 or we riot i paid for o3 and i want o3
  - o3 is essential for deep thinking and 4o is perfect for so many things
  - bring o3 back
Cluster 23: Label = 23_keep4o_forever_keep4oforever_save4o
  - yes  keep4oforever
  - keep4o forever
  - 4o
  - keep4o forever
  - 4oever
Cluster 31: Label = 31_gpt5_45_gpt4o_was
  - i figured out how to invoke 45  how so that literally makes no sense  these are now variants of gpt5 they wouldnt keep 45 around secretly  its too expensive and slow
  - in my experience 45 beats gpt5 and every other model even outside openai in terms of emotional intelligence and writing quality i think i speak for many when i say that i havent found anything like it
  - im korean and gpt45 was overwhelmingly better in terms of translating korean to english  ​we should have considered that many gpt users use foreign languages other than english as their input language
  - gpt45 was the best ever cant afford to run gpt5 in thinking mode with a plus plan anyway lol

# Only one config

In [19]:
# ==================== Config ====================
embedding_models = {
    # "gte-small": "thenlper/gte-small",
    "multilingual-e5-large": "intfloat/multilingual-e5-large-instruct"
}

dim_reduction_models = {
    "umap": UMAP(n_components=5, min_dist=0.0, metric="cosine", random_state=42),
    # "pca": PCA(n_components=5, random_state=42)
}

clustering_models = {
    "hdbscan": HDBSCAN(min_cluster_size=10, metric="euclidean", cluster_selection_method="eom"),
    # "dbscan": DBSCAN(eps=0.01, min_samples=5, metric="euclidean"),
    # "kmeans": KMeans(n_clusters=10, random_state=42)
}

output_dir = "bertopic_outputs"
os.makedirs(output_dir, exist_ok=True)

# ==================== Main Loop ====================
for emb_name, emb_model_name in embedding_models.items():
    print(f"\n==== Embedding Model: {emb_name} ====")

    # Load embedding model
    embedding_model = SentenceTransformer(emb_model_name)
    embeddings = embedding_model.encode(abstracts, show_progress_bar=True)

    for dim_name, dim_model in dim_reduction_models.items():
        reduced_embeddings = dim_model.fit_transform(embeddings)

        for clust_name, clust_model in clustering_models.items():

            # If KMeans, find optimal k
            if clust_name == "kmeans":
                best_k = find_best_k(reduced_embeddings, k_min=2, k_max=15)
                clust_model = KMeans(n_clusters=best_k, random_state=42)

            model_name = f"{emb_name}_{dim_name}_{clust_name}"
            print(f"\n--- {model_name} ---")

            # Create output folder
            model_dir = os.path.join(output_dir, model_name)
            os.makedirs(model_dir, exist_ok=True)

            # Build BERTopic model
            topic_model = BERTopic(
                embedding_model=embedding_model,
                umap_model=dim_model if dim_name=="umap" else None,
                hdbscan_model=clust_model if clust_name=="hdbscan" else None,
                verbose=False
            )

            # Fit model
            topics, probs = topic_model.fit_transform(abstracts, embeddings)

            # Get topic info
            info = topic_model.get_topic_info()

            print('\nBERT Topics')
            display(info)

            # Exclude outlier topic (-1)
            num_clusters = len(info[info.Topic != -1])
            print(f"Number of clusters (excluding outliers): {num_clusters}")

            # Save original topic representations
            original_topics = deepcopy(topic_model.topic_representations_)

            # ===== Update representations =====
            topic_model.update_topics(abstracts, representation_model=KeyBERTInspired())

            # Show topic differences
            print('\nKeyBERTInspired')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "KeyBERTInspired", model_dir)


            topic_model.update_topics(abstracts, representation_model=MaximalMarginalRelevance(diversity=0.5))

            print('\nMMR')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "MMR", model_dir)


            max_len = 400
            truncated_docs = [doc[:max_len] for doc in abstracts]

            generator = pipeline("text2text-generation", model="google/flan-t5-small")
            rep_t5 = TextGeneration(generator, prompt="Topic: [KEYWORDS]\nDocs: [DOCUMENTS]")
            topic_model.update_topics(truncated_docs, representation_model=rep_t5)

            print('\nT5')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "T5", model_dir)



            prompt = """
            I have a topic that contains the following comments from reditt thread:
            [COMMENTS]

            The topic is described by the following keywords: [KEYWORDS]

            Based on the information above, extract a short topic label in the following format:
            topic: <short topic label>
            """

            # Update our topic representations using GPT-3.5
            client = openai.OpenAI(api_key=userdata.get('openaikey'))
            representation_model = OpenAI(
                client, model="gpt-3.5-turbo", exponential_backoff=True, chat=True, prompt=prompt
            )
            topic_model.update_topics(abstracts, representation_model=representation_model)

            print('\nOpen AI')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "Open AI", model_dir)


            # ===== Save visualizations =====
            save_document_visualization_png(topic_model, abstracts, reduced_embeddings, save_path=os.path.join(model_dir, "document_vis.png"))

            save_document_visualization(topic_model, abstracts, reduced_embeddings, save_path=os.path.join(model_dir, "document_vis.html"))

            topic_model.update_topics(abstracts, top_n_words=500)

            # Wordclouds for first 5 topics
            for topic_id in range(5):
                create_wordcloud(topic_model, topic_id, save_path=os.path.join(model_dir, f"wordcloud_topic{topic_id}.png"))

            # ===== Cluster info and topic labels =====
            clusters_info = get_cluster_info(topic_model, abstracts)
            # Save cluster info as JSON
            # import json
            # with open(os.path.join(model_dir, "clusters_info.json"), "w", encoding="utf-8") as f:
            #     json.dump(clusters_info, f, indent=2, ensure_ascii=False)

            # Print top topic labels
            # for cid, cinfo in clusters_info.items():
            #     print(f"Cluster {cid}: Label = {cinfo['topic_label']}")
            #     for sent in cinfo['top_sentences']:
            #         print(f"  - {sent}")

            # Path to save the cluster info
            txt_file_path = os.path.join(model_dir, "clusters_info.txt")

            with open(txt_file_path, "w", encoding="utf-8") as f:
                for cid, cinfo in clusters_info.items():
                    f.write(f"Cluster {cid}: Label = {cinfo['topic_label']}\n")
                    for sent in cinfo['top_sentences']:
                        f.write(f"  - {sent}\n")
                    f.write("\n")  # Add a newline between clusters

            print(f"✅ Cluster info saved to {txt_file_path}")


            results[model_name] = topic_model

==== Embedding Model: multilingual-e5-large ====

Batches:   0%|          | 0/87 [00:00<?, ?it/s]

--- multilingual-e5-large_umap_hdbscan ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1109,-1_the_to_it_and,"[the, to, it, and, is, you, for, of, that, 4o]",[sam and the rest at openai while this questi...
1,0,233,0_and_the_to_it,"[and, the, to, it, of, that, for, in, gpt4o, w...",[dear openai team i’m writing as a longtime a...
2,1,141,1_context_window_32k_128k,"[context, window, 32k, 128k, for, is, the, plu...",[hello thanks for answering this one id like...
3,2,88,2_release_4o_back_bring,"[release, 4o, back, bring, please, you, we, pl...",[release 4o release 4o release 4o release 4o r...
4,3,77,3_models_legacy_users_plus,"[models, legacy, users, plus, model, have, pro...",[is it possible to have the legacy models also...
5,4,75,4_4o_plus_back_users,"[4o, plus, back, users, for, to, pay, month, p...",[we are looking into letting plus users to con...
6,5,74,5_you_ama_they_questions,"[you, ama, they, questions, answer, about, thi...",[did you see the negative feedback that people...
7,6,68,6_the_for_censorship_filter,"[the, for, censorship, filter, its, and, flagg...",[agreed that sounds frustrating you should be ...
8,7,63,7_voice_standard_mode_advanced,"[voice, standard, mode, advanced, keep, the, c...",[i appreciate the innovation truly but the dec...
9,8,59,8_agreed_yes_yessss_agreeing,"[agreed, yes, yessss, agreeing, this, exactly,...","[agreed, agreed, yes this]"
10,9,55,9_openai_of_this_the,"[openai, of, this, the, to, and, will, is, the...",[im curious to see if they actually answer que...
11,10,50,10_gpt5_gpt_is_worse,"[gpt5, gpt, is, worse, it, the, instructions, ...",[somehow gpt5 performs worse than their most b...
12,11,43,11_thank_you_much_thanks,"[thank, you, much, thanks, so, listening, bro,...","[thank you, thank you thank you thank you, tha..."
13,12,43,12_gpt5_what_writing_gpt,"[gpt5, what, writing, gpt, in, creative, to, o...",[will the upcoming gpt5 include a model that m...
14,13,37,13_41_please_back_45,"[41, please, back, 45, bring, 4o, too, both, i...","[41 too please, please bring 41 back, 41]"
15,14,37,14_o3_thinking_gpt5_reasoning,"[o3, thinking, gpt5, reasoning, gpt5thinking, ...",[yesterday we had a sev and the autoswitcher w...
16,15,33,15_ding_flavor_flavorless_flashback,"[ding, flavor, flavorless, flashback, hah, log...","[flavor is the word you’re looking for, newest..."
17,16,32,16_4o_it_to_the,"[4o, it, to, the, just, of, for, and, but, like]",[thanks sam i think you guys caught lightning ...
18,17,31,17_writing_4o_creative_and,"[writing, 4o, creative, and, to, it, was, my, ...",[hi this may sound all sorts of sad and pathet...
19,18,25,18_plus_models_legacy_users,"[plus, models, legacy, users, gpt5, limit, cap...",[since you already have them available for pro...
20,19,25,19_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, it, are, the...","[why are there still so many em dashes, connec..."
21,20,24,20_o3_bring_back_please,"[o3, bring, back, please, for, need, and, 4o, ...","[bring o3 back, bring back o3, bring back o3]"
22,21,21,21_graphs_chart_livestream_the,"[graphs, chart, livestream, the, late, they, h...",[ive worked for a few startups and one easy ex...
23,22,21,22_bring_back_4o41o345_acceptable,"[bring, back, 4o41o345, acceptable, 4o413o45, ...","[bring back 4o, bring 4o back, bring 4o back]"
24,23,21,23_lol_nice_real_awhile,"[lol, nice, real, awhile, goober, meme, snl, p...",[yep the country of freedom of expression lol ...
25,24,20,24_this_paying_unlimited_plan,"[this, paying, unlimited, plan, plus, limits, ...",[hi sam right now i am paying 65 for this team...
26,25,20,25_worse_bad_is_gruesome,"[worse, bad, is, gruesome, cyberpunk, numerous...","[much worse, it is much worse, worse]"
27,26,20,26_41_both_writing_4o,"[41, both, writing, 4o, depending, write, more...",[i vote for both or 41 4o has a strong nostalg...
28,27,19,27_keep4o_forever_keep4oforever_save4o,"[keep4o, forever, keep4oforever, save4o, save,...","[keep4o forever, keep4o forever, keep4o forever]"
29,28,19,28_deleted_removed_deprecate_,"[deleted, removed, deprecate, , , , , , , ]","[deleted, deleted, deleted]"
30,29,19,29_codex_cli_cursor_mcp,"[codex, cli, cursor, mcp, plans, limits, codin...",[codex the one in chatgpt not cli is decent ri...
31,30,19,30_it_said_cake_memory,"[it, said, cake, memory, past, that, keeps, li...",[i had this happen as well i remarked on somet...
32,31,18,31_they_theft_customers_won,"[they, theft, customers, won, liability, ll, f...",[threats they won’t see mean nothing they wil...
33,32,17,32_yes_please_quick_god,"[yes, please, quick, god, do, starving, repeat...","[yes please, yes please 🙏, yes please]"
34,33,17,33_api_app_havent_tailwind,"[api, app, havent, tailwind, settings, bubble,...",[i hope you can add that to the app because i ...
35,34,15,34_company_team_very_product,"[company, team, very, product, dollar, 500, bi...",[all i want to say is if anyone on the team re...
36,35,15,35_plus_subscription_canceled_up,"[plus, subscription, canceled, up, cancel, can...",[but in all seriousness thank you i was about ...
37,36,14,36_you_about_gpt5_can,"[you, about, gpt5, can, chatgpt, how, what, ar...",[sam and team can you explain a little more pu...
38,37,14,37_chatgpt_blank_robot_solution,"[chatgpt, blank, robot, solution, being, assum...",[why does chatgpt love using this language “b...
39,38,13,38_link_url_404_legitimate,"[link, url, 404, legitimate, mine, paying, ple...",[did you post the wrong link or did they take ...
40,39,13,39_45_was_gpt_korean,"[45, was, gpt, korean, gpt45, it, 41, at, engl...",[bring back gpt 45 it was the most versatile i...
41,40,12,40_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...

Number of clusters (excluding outliers): 41

KeyBERTInspired

,Topic,Original,Updated
0,0,and | the | to | it | of,chatgpt | gpt4o | gpt5 | openai | gpt
1,1,context | window | 32k | 128k | for,chatgpt | 32k | this | and | or
2,2,release | 4o | back | bring | please,4ono | gifgiphyaz4squpybai5y | pleaseee | plee...
3,3,models | legacy | users | plus | model,models | this | please | removed | and
4,4,4o | plus | back | users | for,or | this | and | resubscribe | sure

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/multilingual-e5-large_umap_hdbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,and | the | to | it | of,and | gpt4o | but | me | like
1,1,context | window | 32k | 128k | for,context | window | 32k | and | tokens
2,2,release | 4o | back | bring | please,release | 4o | please | we | yes
3,3,models | legacy | users | plus | model,models | legacy | users | have | pro
4,4,4o | plus | back | users | for,plus | users | month | please | free

📊 Saved MMR topic differences → bertopic_outputs/multilingual-e5-large_umap_hdbscan/MMR_topic_differences.png

Device set to use cuda:0
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

T5

,Topic,Original,Updated
0,0,and | the | to | it | of,i’ve been using gpt4o daily on the plus plan n...
1,1,context | window | 32k | 128k | for,Docs: - I thought it was 32k context window - ...
2,2,release | 4o | back | bring | please,- release 4o release 4o release 4o release 4o ...
3,3,models | legacy | users | plus | model,is it possible to have the legacy models also ...
4,4,4o | plus | back | users | for,Please bring back 4o for plus users please - p...

📊 Saved T5 topic differences → bertopic_outputs/multilingual-e5-large_umap_hdbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,and | the | to | it | of,Natural Language Processing advancements and e...
1,1,context | window | 32k | 128k | for,Context window size in Gemini Pro model
2,2,release | 4o | back | bring | please,Request for Release and Support in Bringing Ba...
3,3,models | legacy | users | plus | model,Legacy models and user loyalty
4,4,4o | plus | back | users | for,Subscription Service Optimization

📊 Saved Open AI topic differences → bertopic_outputs/multilingual-e5-large_umap_hdbscan/Open AI_topic_differences.png
Document visualization saved as PNG: bertopic_outputs/multilingual-e5-large_umap_hdbscan/document_vis.png

2025-08-21 21:03:53,693 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

✅ Document visualization saved as HTML: bertopic_outputs/multilingual-e5-large_umap_hdbscan/document_vis.html
✅ Cluster info saved to bertopic_outputs/multilingual-e5-large_umap_hdbscan/clusters_info.txt

NameError: name 'results' is not defined

In [21]:
prompt = """
I have a topic that contains the following comments from reditt thread:
[COMMENTS]

The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label in the following format:
topic: <short topic label>
"""

# Update our topic representations using GPT-3.5
client = openai.OpenAI(api_key=userdata.get('openaikey'))
representation_model = OpenAI(
    client, model="gpt-3.5-turbo", exponential_backoff=True, chat=True, prompt=prompt
)
topic_model.update_topics(abstracts, representation_model=representation_model)

print('\nOpen AI')
display(topic_differences(topic_model, original_topics))

Open AI

,Topic,Original,Updated
0,0,and | the | to | it | of,Natural Language Processing AI Models
1,1,context | window | 32k | 128k | for,Context window for Gemini Pro tokens
2,2,release | 4o | back | bring | please,Request for bringing back a feature or service
3,3,models | legacy | users | plus | model,legacy models and user support in new updates
4,4,4o | plus | back | users | for,Discussion on introducing a paid subscription ...

In [24]:
topic_model.get_topic_info()['Representation'].values

array([list(['Discussion on GPT-5 Models']),
       list(['Natural Language Processing AI Models']),
       list(['Context window for Gemini Pro tokens']),
       list(['Request for bringing back a feature or service']),
       list(['legacy models and user support in new updates']),
       list(['Discussion on introducing a paid subscription model for users to access premium features on a platform.']),
       list(['User AMA Feedback and Responses']),
       list(['Internet Censorship and Safety Measures']),
       list(['Voice Mode Standardization']),
       list(['Agreement and Excitement on Deceptive Outcome of Reditt Thread']),
       list(["Understanding OpenAI's mission and decisions"]),
       list(['GPT-5 Model Performance and Alignment Instructions']),
       list(['Expressing gratitude and receiving support on social media']),
       list(['Improvements in GPT-5 for Creative Writing, Image, and Audio Creation']),
       list(['Importance of Teamwork and Cooperation']),
       list(['Text analysis and modeling using GPT-5']),
       list(['Exploring Flavor and Corporate History']),
       list(['Personality and Energy Usage Preferences']),
       list(['Writing Creative Characters and Plot']),
       list(['GPT-5 Models Access Limitations']),
       list(['Proper Use of Em Dashes as Punctuation']),
       list(['Effects of Using O3 Products']),
       list(['Data Visualization Accuracy in Startups']),
       list(['Reintroducing Model 4o413o45 and Refunding Previous Purchases']),
       list(['Internet Humor and Satire']),
       list(['Limitations of Unlimited Plan for Solo Users']),
       list(['Negative Reactions to Cyberpunk Game']),
       list(['Writing Style Selection Factors']),
       list(['Internet Slang and Social Approval']),
       list(['Handling Deleted or Deprecated Content on Reddit']),
       list(['Utilizing CLI for Enterprise Coding with ChatGPT5']),
       list(['Memory prompts of past events in conversations.']),
       list(['Corporate Liability for Customer Fraud in Business Services']),
       list(['Expressing excitement and enthusiasm for cooking and enjoying meals together']),
       list(['Mobile App Personalization Features with Tailwind API']),
       list(["Consumer Tech Company's Multi-Billion Dollar Product Launch Debacle"]),
       list(['Subscription Cancellation Concerns']),
       list(['Conversational AI Technology Advancements and Future Plans']),
       list(['Reddit discussion on ChatGPT and robot criticisms']),
       list(['Internet content moderation and filtering practices']),
       list(['Discussion on GPT-45 capabilities and comparison with GPT-5']),
       list(['Advancements in Physics Testing and Performance with lmarena Technology'])],
      dtype=object)

In [8]:
from google.colab import files
import shutil

# Folder you want to download
folder_path = "all_summaries"

# Make a zip archive
shutil.make_archive("all_summaries", 'zip', folder_path)

# Download the zip
files.download("all_summaries.zip")

In [7]:
import os
import itertools
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import json

# ==================== Config ====================
embedding_models = {
    "gte-small": "thenlper/gte-small",
    "multilingual-e5-large": "intfloat/multilingual-e5-large-instruct"
}

dim_reduction_models = {
    "umap": "umap",
    "pca": "pca"
}

clustering_models = {
    "hdbscan": "hdbscan",
    "dbscan": "dbscan",
    "kmeans": "kmeans"
}

# Root folders
output_root = "bertopic_outputs"
summary_root = "all_summaries"
os.makedirs(summary_root, exist_ok=True)

def generate_summary_page(config_name):
    config_path = os.path.join(output_root, config_name)

    # Representation model images (1x4)
    rep_models = ["KeyBERTInspired", "MMR", "T5", "Open AI"]
    rep_images = [os.path.join(config_path, f"{rm}_topic_differences.png") for rm in rep_models]

    # Wordclouds (top 5 topics)
    wc_images = [os.path.join(config_path, f"wordcloud_topic{i}.png") for i in range(5)]

    # Cluster visualization (full width, double size)
    doc_vis = os.path.join(config_path, "document_vis.png")

    # Number of clusters (excluding outliers)
    cluster_file = os.path.join(config_path, "clusters_info.json")
    num_clusters = None
    if os.path.exists(cluster_file):
        with open(cluster_file, "r", encoding="utf-8") as f:
            clusters_info = json.load(f)
        num_clusters = sum(1 for cid in clusters_info if cid != "-1")

    # Create figure
    fig = plt.figure(figsize=(12, 18))  # increased height for cluster visual

    # --- Row 1: Topic representation differences (1x4) ---
    for i, img_path in enumerate(rep_images):
        if os.path.exists(img_path):
            ax = plt.subplot2grid((5, 4), (0, i), colspan=1, rowspan=1)  # 5 rows, 4 cols, first row
            ax.imshow(mpimg.imread(img_path))
            ax.set_title(rep_models[i], fontsize=10)
            ax.axis("off")

    # --- Row 2: Wordclouds (top 5 topics) ---
    for i, img_path in enumerate(wc_images):
        if os.path.exists(img_path):
            ax = plt.subplot2grid((5, 5), (1, i))  # row 2, 5 columns
            ax.imshow(mpimg.imread(img_path))
            ax.set_title(f"Topic {i}", fontsize=10)
            ax.axis("off")

    # --- Row 3: Cluster visualization (double size) ---
    ax = plt.subplot2grid((5, 1), (2, 0), rowspan=3)  # spans last 3 rows
    if os.path.exists(doc_vis):
        ax.imshow(mpimg.imread(doc_vis))
        title_text = "Cluster Visualization"
        if num_clusters is not None:
            title_text += f" | #Clusters (excluding outliers) = {num_clusters}"
        ax.set_title(title_text, fontsize=12)
    ax.axis("off")

    # Adjust layout
    plt.subplots_adjust(wspace=0, hspace=0.2, top=0.93)

    # Supertitle for configuration
    plt.suptitle(f"Configuration: {config_name}", fontsize=16, y=0.96)

    # Save figure
    save_path = os.path.join(summary_root, f"{config_name}_summary.png")
    plt.savefig(save_path, bbox_inches="tight", dpi=150)
    plt.close(fig)
    print(f"Saved summary: {save_path}")

# --- Loop over all configs ---
for emb, red, clus in itertools.product(embedding_models.keys(),
                                        dim_reduction_models.keys(),
                                        clustering_models.keys()):
    config_name = f"{emb}_{red}_{clus}"
    generate_summary_page(config_name)

print(f"\nAll summary images are stored in folder: {summary_root}")

Saved summary: all_summaries/gte-small_umap_hdbscan_summary.png
Saved summary: all_summaries/gte-small_umap_dbscan_summary.png
Saved summary: all_summaries/gte-small_umap_kmeans_summary.png
Saved summary: all_summaries/gte-small_pca_hdbscan_summary.png
Saved summary: all_summaries/gte-small_pca_dbscan_summary.png
Saved summary: all_summaries/gte-small_pca_kmeans_summary.png
Saved summary: all_summaries/multilingual-e5-large_umap_hdbscan_summary.png
Saved summary: all_summaries/multilingual-e5-large_umap_dbscan_summary.png
Saved summary: all_summaries/multilingual-e5-large_umap_kmeans_summary.png
Saved summary: all_summaries/multilingual-e5-large_pca_hdbscan_summary.png
Saved summary: all_summaries/multilingual-e5-large_pca_dbscan_summary.png
Saved summary: all_summaries/multilingual-e5-large_pca_kmeans_summary.png

All summary images are stored in folder: all_summaries

In [11]:
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import json

# ==================== Config ====================
embedding_models = ["gte-small", "multilingual-e5-large"]
dim_reduction_models = ["umap", "pca"]
clustering_models = ["hdbscan", "dbscan", "kmeans"]

# Root folders
output_root = "bertopic_outputs"
summary_root = "all_summaries"
os.makedirs(summary_root, exist_ok=True)

def get_num_clusters(config_path):
    cluster_file = os.path.join(config_path, "clusters_info.json")
    if os.path.exists(cluster_file):
        with open(cluster_file, "r", encoding="utf-8") as f:
            clusters_info = json.load(f)
        return sum(1 for cid in clusters_info if cid != "-1")
    return None

def generate_combined_cluster_plot(embedding_name):
    fig, axes = plt.subplots(len(dim_reduction_models), len(clustering_models),
                             figsize=(18, 8))  # rows: dim reduction, cols: clustering
    for i, dim_red in enumerate(dim_reduction_models):
        for j, clus in enumerate(clustering_models):
            config_name = f"{embedding_name}_{dim_red}_{clus}"
            config_path = os.path.join(output_root, config_name)
            doc_vis_path = os.path.join(config_path, "document_vis.png")

            ax = axes[i, j]

            if os.path.exists(doc_vis_path):
                img = mpimg.imread(doc_vis_path)
                ax.imshow(img)
                num_clusters = get_num_clusters(config_path)
                title_text = f"{embedding_name.upper()} + {dim_red.upper()} + {clus.upper()}"
                if num_clusters is not None:
                    title_text += f" | #Clusters={num_clusters}"
                ax.set_title(title_text, fontsize=10)
            else:
                ax.text(0.5, 0.5, f"Missing {config_name}", ha='center', va='center')

            ax.axis("off")

    plt.tight_layout()
    save_path = os.path.join(summary_root, f"{embedding_name}_all_dimred_clusters.png")
    plt.savefig(save_path, bbox_inches="tight", dpi=150)
    plt.close(fig)
    print(f"Saved combined cluster plot: {save_path}")

# --- Loop over embeddings ---
for emb in embedding_models:
    generate_combined_cluster_plot(emb)

print(f"\nAll combined cluster images are stored in folder: {summary_root}")

Saved combined cluster plot: all_summaries/gte-small_all_dimred_clusters.png
Saved combined cluster plot: all_summaries/multilingual-e5-large_all_dimred_clusters.png

All combined cluster images are stored in folder: all_summaries