<a href="https://colab.research.google.com/github/amankiitg/LLM_Prod/blob/main/Reditt_Text_Clustering_and_Topic_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Text Clustering and Topic Modeling</h1>
<i>Clustering documents using a wide variety of language models.</i>

### [OPTIONAL] - Installing Packages on <img src="https://colab.google/static/images/icons/colab.png" width=100>

If you are viewing this notebook on Google Colab (or any other cloud vendor), you need to **uncomment and run** the following codeblock to install the dependencies for this chapter:

---

💡 **NOTE**: We will want to use a GPU to run the examples in this notebook. In Google Colab, go to
**Runtime > Change runtime type > Hardware accelerator > GPU > GPU type > T4**.

---

In [ ]:
!pip install asyncpraw

Collecting asyncpraw
  Downloading asyncpraw-7.8.1-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: aiofiles in /usr/local/lib/python3.12/dist-packages (from asyncpraw) (24.1.0)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from asyncpraw) (3.12.15)
Collecting aiosqlite<=0.17.0 (from asyncpraw)
  Downloading aiosqlite-0.17.0-py3-none-any.whl.metadata (4.1 kB)
Collecting asyncprawcore<3,>=2.4 (from asyncpraw)
  Downloading asyncprawcore-2.4.0-py3-none-any.whl.metadata (5.5 kB)
Collecting update_checker>=0.18 (from asyncpraw)
  Downloading update_checker-0.18.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->asyncpraw) (1.20.1)
Requirement already satisfied: typing_extensions>=3.7.2 in /usr/local/lib/python3.12/dist-packages (from aiosqlite<=0.17.0->asyncpraw) (4.14.1)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from update_checker>=0.18->asyncpraw) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.3.0->update_checker>=0.18->asyncpraw) (2025.8.3)
Downloading asyncpraw-7.8.1-py3-none-any.whl (196 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.4/196.4 kB 3.9 MB/s eta 0:00:00
Downloading aiosqlite-0.17.0-py3-none-any.whl (15 kB)
Downloading asyncprawcore-2.4.0-py3-none-any.whl (19 kB)
Downloading update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Installing collected packages: aiosqlite, update_checker, asyncprawcore, asyncpraw
Successfully installed aiosqlite-0.17.0 asyncpraw-7.8.1 asyncprawcore-2.4.0 update_checker-0.18.0

In [ ]:
import asyncio
import asyncpraw
import nest_asyncio
import json
import numpy as np
import re
import string

# --------------------
# Text cleaning helper
# --------------------
def clean_text(text):
    """Cleans text by removing URLs, punctuation, and lowercasing."""
    text = re.sub(r'http\S+|https\S+', '', text)   # Remove URLs
    text = text.replace('\n', ' ')                 # Remove newlines
    text = text.translate(str.maketrans('', '', string.punctuation))  # Remove punctuation
    return text.lower().strip()

def extract_comment_bodies(comments):
    """Recursively extracts bodies and scores for thresholding."""
    bodies, scores = [], []
    for comment in comments:
        bodies.append(comment['body'])
        scores.append(comment['score'])
        if comment.get('replies'):
            child_bodies, child_scores = extract_comment_bodies(comment['replies'])
            bodies.extend(child_bodies)
            scores.extend(child_scores)
    return bodies, scores

# --------------------
# Main Scraper
# --------------------
async def scrape():
    async with asyncpraw.Reddit(
        client_id="glnTvdUs1KFycKy5vEsOig",
        client_secret="ET1IgiyCztIxhXSwnFIYbTs3eq2nRQ",
        user_agent="Topic Modeler"
    ) as reddit:

        url = "https://www.reddit.com/r/ChatGPT/comments/1mkae1l/gpt5_ama_with_openais_sam_altman_and_some_of_the/"
        submission = await reddit.submission(url=url)

        async def extract_comment(comment):
            return {
                "author": str(comment.author),
                "body": comment.body,
                "score": comment.score,
                "replies": [await extract_comment(reply) async for reply in comment.replies]
            }

        # Build post object
        post_data = {
            "title": submission.title,
            "author": str(submission.author),
            "score": submission.score,
            "url": submission.url,
            "selftext": submission.selftext,
            "comments": []
        }

        # Load comments
        await submission.comments.replace_more(limit=None)
        for top_comment in submission.comments:
            post_data["comments"].append(await extract_comment(top_comment))

        # Flatten scores for median threshold
        _, all_scores = extract_comment_bodies(post_data["comments"])
        median_score = np.median(all_scores) if all_scores else 0

        # --------------------
        # Filter + transform comments
        # --------------------
        def filter_and_transform(comments):
            """Filter by median score and create title/abstract."""
            result = []
            for c in comments:
                if c['score'] >= median_score:
                    result.append({
                        "title": clean_text(c['body'])[:60],   # First 60 chars as title
                        "abstract": clean_text(c['body']),     # Full cleaned body
                        "score": c['score'],
                        "author": c['author']
                    })
                if c.get('replies'):
                    result.extend(filter_and_transform(c['replies']))
            return result

        post_data["comments"] = filter_and_transform(post_data["comments"])
        post_data["median_score_threshold"] = median_score

        # Dump JSON
        with open("reddit_post_filtered.json", "w", encoding="utf-8") as f:
            json.dump(post_data, f, indent=2, ensure_ascii=False)

        print("✅ Filtered post data saved to reddit_post_filtered.json")

# --------------------
# Run safely with nest_asyncio
# --------------------
nest_asyncio.apply()
asyncio.run(scrape())

✅ Filtered post data saved to reddit_post_filtered.json

/tmp/ipython-input-3660819704.py:65: DeprecationWarning: Using CommentForest as an asynchronous iterator has been deprecated and will be removed in a future version.
  post_data["comments"].append(await extract_comment(top_comment))
/tmp/ipython-input-3660819704.py:49: DeprecationWarning: Using CommentForest as an asynchronous iterator has been deprecated and will be removed in a future version.
  "replies": [await extract_comment(reply) async for reply in comment.replies]

# **Load Reditt Data**

In [1]:
import json

with open("/content/reddit_post_filtered.json", "r", encoding="utf-8") as f:
    reddit_data = json.load(f)

# Recursive extractor for title and abstract
def extract_title_abstract(comments):
    result = []
    for c in comments:
        result.append({
            "title": c["title"],
            "abstract": c["abstract"]
        })
        if c.get("replies"):
            result.extend(extract_title_abstract(c["replies"]))
    return result

# Extract only title and abstract
titles_and_abstracts = extract_title_abstract(reddit_data["comments"])

# Display first 10
for item in titles_and_abstracts[:10]:
    print(item)

# # Extract metadata and convert to standard list
abstracts = [t['abstract'] for t in titles_and_abstracts]
titles = [t['title'] for t in titles_and_abstracts]

{'title': 'i see that em dash', 'abstract': 'i see that em dash'}
{'title': 'its not an em dash — its a pause that demands attention', 'abstract': 'its not an em dash — its a pause that demands attention'}
{'title': 'can you mark the other cohosts their answers are buried and ', 'abstract': 'can you mark the other cohosts their answers are buried and unhighlighted and the only way you can find them at present is by checking each profiles comment history manually   currently the filter for answered misses every other cohost reply other than sam altman making the ama much harder to navigate  or provide some other way to see them thanks'}
{'title': 'only uopenai can i think theres a limit to the number of par', 'abstract': 'only uopenai can i think theres a limit to the number of participants'}
{'title': 'ah thats a bother perhaps sticky links to them in a comment ', 'abstract': 'ah thats a bother perhaps sticky links to them in a comment after the ama ends its kind of silly that theres be a small limit'}
{'title': 'hot damnnnnn he tucked tail and ran outta there fast when he', 'abstract': 'hot damnnnnn he tucked tail and ran outta there fast when he realized the majority of the questions were people upset over the rollout my faith in this openai team is beginning to slip lol i didnt realize they were sorta buffoons'}
{'title': 'yeah but did you see you can now change the color of the cha', 'abstract': 'yeah but did you see you can now change the color of the chat bubbles wow sam truly the next oppenheimer'}
{'title': 'will it be in this same post or will there be a new post', 'abstract': 'will it be in this same post or will there be a new post'}
{'title': 'openai team will start answering the questions on this same ', 'abstract': 'openai team will start answering the questions on this same post at 1100 am pt'}
{'title': 'also on exisitng qs or must we come back to ask live', 'abstract': 'also on exisitng qs or must we come back to ask live'}

## **BERTopic: A Modular Topic Modeling Framework**

In [2]:
!pip install -q bertopic openai datasets datamapplot

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.0/153.0 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.5/163.5 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 54.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 123.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 67.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 66.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.3/244.3 kB 23.2 MB/s eta 0:00:00
  Building wheel for Pyqtree (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rapids-dask-dependency 25.6.0 requires dask==2025.5.0, but you have dask 2024.12.1 which is incompatible.
rapids-dask-dependency 25.6.0 requires distributed==2025.5.0, but you have distributed 2024.12.1 which is incompatible.

In [3]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, DBSCAN
from umap import UMAP
from hdbscan import HDBSCAN
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance, TextGeneration, OpenAI
from transformers import pipeline
from wordcloud import WordCloud
import openai
from copy import deepcopy
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from google.colab import userdata
import datamapplot
import re


def find_best_k(embeddings, k_min=2, k_max=15, random_state=42):
    """Return best k based on silhouette score"""
    best_score = -1
    best_k = k_min
    for k in range(k_min, k_max + 1):
        kmeans = KMeans(n_clusters=k, random_state=random_state).fit(embeddings)
        score = silhouette_score(embeddings, kmeans.labels_)
        if score > best_score:
            best_score = score
            best_k = k
    print(f"✅ Best k for KMeans: {best_k} with silhouette {best_score:.3f}")
    return best_k

# ==================== Helper Functions ====================
def topic_differences(model, original_topics, nr_topics=5):
    df = pd.DataFrame(columns=["Topic", "Original", "Updated"])
    for topic in range(nr_topics):
        og_words = " | ".join(list(zip(*original_topics[topic]))[0][:5])
        new_words = " | ".join(list(zip(*model.get_topic(topic)))[0][:5])
        df.loc[len(df)] = [topic, og_words, new_words]
    return df

def create_wordcloud(model, topic, save_path=None):
    """Generate a wordcloud for a given topic if it exists."""
    topic_words = model.get_topic(topic)
    if not topic_words:  # Returns False if topic does not exist
        print(f"⚠️ Topic {topic} does not exist. Skipping wordcloud.")
        return

    plt.figure(figsize=(10,5))
    text = {word: value for word, value in topic_words}
    wc = WordCloud(background_color="white", max_words=1000, width=1600, height=800)
    wc.generate_from_frequencies(text)
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    if save_path:
        plt.savefig(save_path, bbox_inches='tight')
    plt.close()


def save_document_visualization(model, documents, reduced_embeddings, save_path=None):
    """
    Visualize BERTopic documents and save as HTML.

    Args:
        model: BERTopic model
        documents: list of documents/abstracts
        reduced_embeddings: reduced embeddings used for visualization
        save_path: path to save HTML file
    """
    fig = model.visualize_documents(
        documents,
        reduced_embeddings=reduced_embeddings,
        width=1200,
        hide_annotations=True
    )
    fig.update_layout(font=dict(size=8))

    if save_path:
        fig.write_html(save_path)
        print(f"✅ Document visualization saved as HTML: {save_path}")

    plt.close()



def get_cluster_info(model, documents):
    """Return a dict with each cluster's top sentences and topic labels"""
    clusters = {}
    topics = model.get_document_info(documents)
    for topic_id in topics['Topic'].unique():
        if topic_id == -1:
            continue
        cluster_docs = topics[topics.Topic==topic_id]['Document'].tolist()
        label = model.get_topic(topic_id)
        clusters[topic_id] = {
            "top_sentences": cluster_docs[:5],  # top 5 representative sentences
            "topic_label": model.get_topic_info().loc[model.get_topic_info().Topic==topic_id, "Name"].values[0]
        }
    return clusters



# ==================== Config ====================
embedding_models = {
    "gte-small": "thenlper/gte-small",
    "multilingual-e5-large": "intfloat/multilingual-e5-large-instruct"
}

dim_reduction_models = {
    # "umap": UMAP(n_components=5, min_dist=0.0, metric="cosine", random_state=42),
    "pca": PCA(n_components=5, random_state=42)
}

clustering_models = {
    "hdbscan": HDBSCAN(min_cluster_size=10, metric="euclidean", cluster_selection_method="eom"),
    "dbscan": DBSCAN(eps=0.01, min_samples=5, metric="euclidean"),
    "kmeans": KMeans(n_clusters=10, random_state=42)
}

/usr/local/lib/python3.12/dist-packages/hdbscan/plots.py:448: SyntaxWarning: invalid escape sequence '\l'
  axis.set_ylabel('$\lambda$ value')
/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.

In [4]:
def save_document_visualization_png(model, documents, reduced_embeddings, save_path=None):
    """
    Visualize BERTopic documents and save as PNG with arrow annotations.

    Args:
        model: BERTopic model
        documents: list of documents/abstracts
        reduced_embeddings: reduced embeddings used for visualization
        save_path: path to save PNG file
    """
    import numpy as np
    import matplotlib.pyplot as plt

    # Save as PNG using matplotlib
    if save_path:
        # Ensure the save path has .png extension
        if not save_path.lower().endswith('.png'):
            save_path = save_path.rsplit('.', 1)[0] + '.png'

        # Create matplotlib version
        plt.figure(figsize=(12, 8))

        # Get topic assignments and create color map
        topic_assignments = np.array(model.topics_)
        unique_topics = np.unique(topic_assignments)
        colors = plt.cm.Set3(np.linspace(0, 1, len(unique_topics)))
        color_map = {topic: colors[i] for i, topic in enumerate(unique_topics)}

        # Plot points
        for topic in unique_topics:
            mask = topic_assignments == topic
            if topic == -1:  # Outliers
                plt.scatter(reduced_embeddings[mask, 0], reduced_embeddings[mask, 1],
                          c='gray', alpha=0.6, s=20, label='Outliers')
            else:
                plt.scatter(reduced_embeddings[mask, 0], reduced_embeddings[mask, 1],
                          c=[color_map[topic]], alpha=0.7, s=30, label=f'Topic {topic}')

        # Randomly select 20% of topics for labeling
        import random
        non_outlier_topics = [t for t in unique_topics if t != -1]
        num_topics_to_label = max(1, int(len(non_outlier_topics) * 0.2))
        topics_to_label = random.sample(non_outlier_topics, num_topics_to_label)

        # Add arrows pointing to cluster centers (only for selected topics)
        for topic in unique_topics:
            if topic != -1 and topic in topics_to_label:  # Only label selected topics
                mask = topic_assignments == topic
                if np.any(mask):
                    center_x = np.mean(reduced_embeddings[mask, 0])
                    center_y = np.mean(reduced_embeddings[mask, 1])

                    # Get topic words and wrap text
                    topic_words = model.get_topic(topic)
                    topic_label = ", ".join([word for word, _ in topic_words[:3]])

                    # Wrap text to limit width (approximately 15 characters per line)
                    import textwrap
                    wrapped_label = "\n".join(textwrap.wrap(topic_label, width=15))
                    final_label = f"Topic {topic}\n{wrapped_label}"

                    # Calculate direction from overall center to cluster center
                    overall_center_x = np.mean(reduced_embeddings[:, 0])
                    overall_center_y = np.mean(reduced_embeddings[:, 1])

                    direction_x = center_x - overall_center_x
                    direction_y = center_y - overall_center_y

                    # Normalize and extend (back to original distance)
                    length = np.sqrt(direction_x**2 + direction_y**2)
                    if length > 0:
                        direction_x /= length
                        direction_y /= length

                    # Place text at original distance (2.5)
                     # Set text_distance based on path
                    if "pca" in save_path.lower():
                        text_distance = 0.2
                    else:
                        text_distance = 2.5

                    text_x = center_x + direction_x * text_distance
                    text_y = center_y + direction_y * text_distance

                    # Add arrow and text
                    plt.annotate(final_label,
                               xy=(center_x, center_y),
                               xytext=(text_x, text_y),
                               arrowprops=dict(arrowstyle='->', color='black', lw=2),
                               bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8),
                               fontsize=8, ha='center', va='center')

        plt.title('Document Visualization with Topic Clusters', fontsize=14)
        plt.xlabel('Dimension 1', fontsize=12)
        plt.ylabel('Dimension 2', fontsize=12)
        plt.grid(True, alpha=0.3)

        # Save matplotlib version
        plt.tight_layout()
        plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
        # plt.close()
        print(f"Document visualization saved as PNG: {save_path}")

    return None

In [5]:
import matplotlib.pyplot as plt

def save_topic_differences_png(topic_model, original_topics, label, model_dir):
    """Save topic differences as PNG instead of just displaying."""
    diff_df = topic_differences(topic_model, original_topics)

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.axis('off')
    ax.table(
        cellText=diff_df.values,
        colLabels=diff_df.columns,
        cellLoc='center',
        loc='center'
    )
    plt.tight_layout()
    save_path = os.path.join(model_dir, f"{label}_topic_differences.png")
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"📊 Saved {label} topic differences → {save_path}")

In [6]:
results = {}

output_dir = "bertopic_outputs"
os.makedirs(output_dir, exist_ok=True)

# ==================== Main Loop ====================
for emb_name, emb_model_name in embedding_models.items():
    print(f"\n==== Embedding Model: {emb_name} ====")

    # Load embedding model
    embedding_model = SentenceTransformer(emb_model_name)
    embeddings = embedding_model.encode(abstracts, show_progress_bar=True)

    for dim_name, dim_model in dim_reduction_models.items():
        reduced_embeddings = dim_model.fit_transform(embeddings)

        for clust_name, clust_model in clustering_models.items():

            # If KMeans, find optimal k
            if clust_name == "kmeans":
                best_k = find_best_k(reduced_embeddings, k_min=2, k_max=15)
                clust_model = KMeans(n_clusters=best_k, random_state=42)

            model_name = f"{emb_name}_{dim_name}_{clust_name}"
            print(f"\n--- {model_name} ---")

            # Create output folder
            model_dir = os.path.join(output_dir, model_name)
            os.makedirs(model_dir, exist_ok=True)

            # Build BERTopic model
            topic_model = BERTopic(
                embedding_model=embedding_model,
                umap_model=dim_model if dim_name=="umap" else None,
                hdbscan_model=clust_model if clust_name=="hdbscan" else None,
                verbose=False
            )

            # Fit model
            topics, probs = topic_model.fit_transform(abstracts, embeddings)

            # Get topic info
            info = topic_model.get_topic_info()

            print('\nBERT Topics')
            display(info)

            # Exclude outlier topic (-1)
            num_clusters = len(info[info.Topic != -1])
            print(f"Number of clusters (excluding outliers): {num_clusters}")

            # Save original topic representations
            original_topics = deepcopy(topic_model.topic_representations_)

            # ===== Update representations =====
            topic_model.update_topics(abstracts, representation_model=KeyBERTInspired())

            # Show topic differences
            print('\nKeyBERTInspired')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "KeyBERTInspired", model_dir)


            topic_model.update_topics(abstracts, representation_model=MaximalMarginalRelevance(diversity=0.5))

            print('\nMMR')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "MMR", model_dir)


            max_len = 400
            truncated_docs = [doc[:max_len] for doc in abstracts]

            generator = pipeline("text2text-generation", model="google/flan-t5-small")
            rep_t5 = TextGeneration(generator, prompt="Topic: [KEYWORDS]\nDocs: [DOCUMENTS]")
            topic_model.update_topics(truncated_docs, representation_model=rep_t5)

            print('\nT5')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "T5", model_dir)



            prompt = """
            I have a topic that contains the following comments from reditt thread:
            [COMMENTS]

            The topic is described by the following keywords: [KEYWORDS]

            Based on the information above, extract a short topic label in the following format:
            topic: <short topic label>
            """

            # Update our topic representations using GPT-3.5
            client = openai.OpenAI(api_key=userdata.get('openaikey'))
            representation_model = OpenAI(
                client, model="gpt-3.5-turbo", exponential_backoff=True, chat=True, prompt=prompt
            )
            topic_model.update_topics(abstracts, representation_model=representation_model)

            print('\nOpen AI')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "Open AI", model_dir)


            # ===== Save visualizations =====
            save_document_visualization_png(topic_model, abstracts, reduced_embeddings, save_path=os.path.join(model_dir, "document_vis.png"))

            save_document_visualization(topic_model, abstracts, reduced_embeddings, save_path=os.path.join(model_dir, "document_vis.html"))

            topic_model.update_topics(abstracts, top_n_words=500)

            # Wordclouds for first 5 topics
            for topic_id in range(5):
                create_wordcloud(topic_model, topic_id, save_path=os.path.join(model_dir, f"wordcloud_topic{topic_id}.png"))

            # ===== Cluster info and topic labels =====
            clusters_info = get_cluster_info(topic_model, abstracts)
            # Save cluster info as JSON
            # import json
            # with open(os.path.join(model_dir, "clusters_info.json"), "w", encoding="utf-8") as f:
            #     json.dump(clusters_info, f, indent=2, ensure_ascii=False)

            # Print top topic labels
            # for cid, cinfo in clusters_info.items():
            #     print(f"Cluster {cid}: Label = {cinfo['topic_label']}")
            #     for sent in cinfo['top_sentences']:
            #         print(f"  - {sent}")

            # Path to save the cluster info
            txt_file_path = os.path.join(model_dir, "clusters_info.txt")

            with open(txt_file_path, "w", encoding="utf-8") as f:
                for cid, cinfo in clusters_info.items():
                    f.write(f"Cluster {cid}: Label = {cinfo['topic_label']}\n")
                    for sent in cinfo['top_sentences']:
                        f.write(f"  - {sent}\n")
                    f.write("\n")  # Add a newline between clusters

            print(f"✅ Cluster info saved to {txt_file_path}")


            results[model_name] = topic_model

==== Embedding Model: gte-small ====

modules.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/583 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/66.7M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/87 [00:00<?, ?it/s]

--- gte-small_pca_hdbscan ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,985,-1_and_to_the_it,"[and, to, the, it, of, for, that, is, in, you]",[please give us the option to use gpt4o41 alon...
1,0,283,0_gpt5_gpt_the_to,"[gpt5, gpt, the, to, is, it, and, model, think...",[there is huge difference between quality of g...
2,1,154,1_chatgpt_it_and_to,"[chatgpt, it, and, to, the, my, that, in, me, ...",[ive been using chatgpt for over 3 years now a...
3,2,102,2_models_legacy_the_model,"[models, legacy, the, model, users, to, you, h...",[since you already have them available for pro...
4,3,100,3_context_window_32k_128k,"[context, window, 32k, 128k, tokens, for, the,...",[there should be some context window upgrade f...
5,4,89,4_spaghetti_ding_word_eating,"[spaghetti, ding, word, eating, smith, in, blu...",[here you go singleshot gpt5 thinking build ...
6,5,80,5_safety_the_censorship_for,"[safety, the, censorship, for, be, you, filter...",[can you do something about the filter surely ...
7,6,80,6_back_bring_4o_please,"[back, bring, 4o, please, plz, quota, we, it, ...","[please bring 4o back 🖤🌌, please bring 4o back..."
8,7,76,7_voice_standard_mode_advanced,"[voice, standard, mode, advanced, cove, the, k...",[i appreciate the innovation truly but the dec...
9,8,69,8_plus_limits_unlimited_limit,"[plus, limits, unlimited, limit, users, for, r...",[dont forget that plus subscribers also had ac...
10,9,40,9_thank_you_much_listening,"[thank, you, much, listening, thanks, so, bro,...","[🙏 thank you, thank you, thank you]"
11,10,40,10_ai_you_to_that,"[ai, you, to, that, people, are, human, of, in...",[theyre taking away what matters to us right ...
12,11,38,11_company_they_livestream_you,"[company, they, livestream, you, were, their, ...",[the numbers here were accurate but we screwed...
13,12,37,12_ama_they_this_really,"[ama, they, this, really, comment, only, did, ...",[can you mark the other cohosts their answers ...
14,13,33,13_gpt4o_and_emotional_of,"[gpt4o, and, emotional, of, users, it, openai,...",[dear openai team i’m writing as a longtime a...
15,14,32,14_4o_personality_fun_it,"[4o, personality, fun, it, like, more, to, and...",[yeah i think 4o was more relatable 5 is a bit...
16,15,31,15_it_emotional_gpt5_and,"[it, emotional, gpt5, and, the, of, but, gpt4o...",[i’ve been a longtime daily gpt user and i’m r...
17,16,30,16_openai_this_will_of,"[openai, this, will, of, the, openais, to, non...",[so let me get this straight the most hyped ...
18,17,29,17_41_4o_both_please,"[41, 4o, both, please, 45, 80, prone, personal...",[41 needs to come back too 4o and 41 are not n...
19,18,28,18_45_50_40_write,"[45, 50, 40, write, it, wrote, 41, love, was, ...",[i would love 45 back just release it full on...
20,19,27,19_41_please_back_too,"[41, please, back, too, important, save, well,...","[41 too please, please bring 41 back, 41]"
21,20,24,20_4o_enough_suffice_fill,"[4o, enough, suffice, fill, 3o, would, fix, is...","[4o is enough, 4o would suffice 5 is basically..."
22,21,23,21_yes_undone_expanding_woah,"[yes, undone, expanding, woah, yeah, yup, sadl...","[yes, yes, yes]"
23,22,23,22_lol_agreed_same_agree,"[lol, agreed, same, agree, pic, depressed, who...","[lol, lol, same lol]"
24,23,22,23_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, u2014, punct...","[i see that em dash, connect clauses directly ..."
25,24,21,24_yes_please_quick_god,"[yes, please, quick, god, do, starving, boy, h...","[yes please, yes please 🙏, yes please]"
26,25,21,25_32k_plus_pro_128k,"[32k, plus, pro, 128k, for, surprise, ground, ...",[that is def not true that range is usually re...
27,26,20,26_codex_cli_cursor_limits,"[codex, cli, cursor, limits, mcp, plans, codin...",[we do use our models for internal acceleratio...
28,27,19,27_deleted_removed_crown_anonymized,"[deleted, removed, crown, anonymized, dime, bi...","[deleted, deleted, deleted]"
29,28,18,28_worse_bad_much_it,"[worse, bad, much, it, is, embrace, gruesome, ...","[much worse, worse, it is much worse]"
30,29,17,29_plus_users_4o_back,"[plus, users, 4o, back, letting, we, product, ...",[why does 4o for plus users feel like a downgr...
31,30,17,30_writing_character_to_it,"[writing, character, to, it, dialogue, and, cr...",[power user here 5 is a major downgrade to 45...
32,31,16,31_sam_thanks_you_thank,"[sam, thanks, you, thank, sammy, fuck, busines...",[i can now finish writing my book thank you sa...
33,32,16,32_o3_back_bring_please,"[o3, back, bring, please, need, for, riot, was...","[bring back o3, bring o3 back, bring back o3]"
34,33,15,33_model_is_the_to,"[model, is, the, to, openai, models, results, ...",[tldr its a downgrade for users but costs less...
35,34,15,34_release_4o_keep4o_forever,"[release, 4o, keep4o, forever, keep4oforever, ...","[keep4o forever, keep4o forever ！！！, release 4..."
36,35,15,35_writing_gpt5_creative_45,"[writing, gpt5, creative, 45, improvements, be...",[yes but who is judging the writing tech peopl...
37,36,14,36_free_chatgpt_plan_or,"[free, chatgpt, plan, or, users, to, api, the,...",[my experience with gpt 5 is pretty awful righ...
38,37,13,37_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
39,38,12,38_4o_pay_month_would,"[4o, pay, month, would, subscriptions, for, pl...",[my family already stopped using it for the m...
40,39,12,39_o3_4o413o45_bring_back,"[o3, 4o413o45, bring, back, o4mini, 4o, notifi...","[bring back 4o413o45, bring back 4o and o3 and..."
41,40,12,40_gemini_book_potter_harry,"[gemini, book, potter, harry, series, can, whe...",[just a book you can give gemini the entire ha...
42,41,11,41_อนเด_เปล_meme_กอย,"[อนเด, เปล, meme, กอย, กลายเป, snl, police, นห...","[he feels like the language police 🤷🏻‍♀️🙄, 💕 b..."
43,42,10,42_falls_4o_to_it,"[falls, 4o, to, it, great, be, using, would, n...",[was using 4o to code and had a decent working...

Number of clusters (excluding outliers): 43

KeyBERTInspired

,Topic,Original,Updated
0,0,gpt5 | gpt | the | to | is,gpt5 | gpt4o | gpt | gpt4 | 4o
1,1,chatgpt | it | and | to | the,chatgpt | chatgpt4o | chat | gpt | gpt5
2,2,models | legacy | the | model | users,models | legacy | model | users | previous
3,3,context | window | 32k | 128k | tokens,context | window | plus | windows | 32k
4,4,spaghetti | ding | word | eating | smith,will | see | live | make | website

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/gte-small_pca_hdbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,gpt5 | gpt | the | to | is,gpt5 | to | 4o | its | than
1,1,chatgpt | it | and | to | the,chatgpt | to | in | me | chat
2,2,models | legacy | the | model | users,models | legacy | users | back | why
3,3,context | window | 32k | 128k | tokens,context | window | 32k | tokens | plus
4,4,spaghetti | ding | word | eating | smith,spaghetti | ding | word | smith | blueberry

📊 Saved MMR topic differences → bertopic_outputs/gte-small_pca_hdbscan/MMR_topic_differences.png

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors

T5

,Topic,Original,Updated
0,0,gpt5 | gpt | the | to | is,There is huge difference between quality of gp...
1,1,chatgpt | it | and | to | the,I’ve been a paid member with you guys since ch...
2,2,models | legacy | the | model | users,Please bring back legacy models for plus users...
3,3,context | window | 32k | 128k | tokens,...
4,4,spaghetti | ding | word | eating | smith,How do you plan to reduce the infrastructure c...

📊 Saved T5 topic differences → bertopic_outputs/gte-small_pca_hdbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,gpt5 | gpt | the | to | is,GPT5 model and reasoning
1,1,chatgpt | it | and | to | the,ChatGPT version update and improvements
2,2,models | legacy | the | model | users,Legacy Model Support and User Access
3,3,context | window | 32k | 128k | tokens,Language Model Token Limit Increase
4,4,spaghetti | ding | word | eating | smith,Food and Cooking

📊 Saved Open AI topic differences → bertopic_outputs/gte-small_pca_hdbscan/Open AI_topic_differences.png
Document visualization saved as PNG: bertopic_outputs/gte-small_pca_hdbscan/document_vis.png

2025-08-22 11:14:11,439 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

✅ Document visualization saved as HTML: bertopic_outputs/gte-small_pca_hdbscan/document_vis.html
✅ Cluster info saved to bertopic_outputs/gte-small_pca_hdbscan/clusters_info.txt

--- gte-small_pca_dbscan ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1039,-1_to_and_the_it,"[to, and, the, it, of, is, that, for, in, you]",[sam altman you can see here that the overwhel...
1,0,162,0_context_window_32k_128k,"[context, window, 32k, 128k, for, plus, tokens...",[there should be some context window upgrade f...
2,1,145,1_chatgpt_it_and_the,"[chatgpt, it, and, the, to, my, in, me, chat, ...",[ive been using chatgpt for over 3 years now a...
3,2,110,2_models_legacy_the_users,"[models, legacy, the, users, model, to, back, ...",[since you already have them available for pro...
4,3,87,3_spaghetti_ding_eating_smith,"[spaghetti, ding, eating, smith, bar, infrastr...",[yes it sees everything and i mean everything ...
5,4,83,4_back_bring_4o_please,"[back, bring, 4o, please, we, plz, you, quota,...","[please bring 4o back, please bring 4o back 🖤🌌..."
6,5,77,5_plus_limits_limit_unlimited,"[plus, limits, limit, unlimited, users, rate, ...",[dont forget that plus subscribers also had ac...
7,6,76,6_voice_standard_mode_advanced,"[voice, standard, mode, advanced, cove, the, k...",[i appreciate the innovation truly but the dec...
8,7,66,7_4o_plus_back_users,"[4o, plus, back, users, to, for, please, subsc...",[there are a lot of plus subscribers like myse...
9,8,63,8_gpt_gpt5_did_it,"[gpt, gpt5, did, it, on, image, is, gpt4, the,...",[i asked gpt to add dramatic lightning to a va...
10,9,61,9_4o_it_and_to,"[4o, it, and, to, like, personality, not, more...",[can we get 4 back the responses are clipped a...
11,10,44,10_they_company_product_their,"[they, company, product, their, theft, custome...",[the numbers here were accurate but we screwed...
12,11,43,11_4o_gpt_back_bring,"[4o, gpt, back, bring, gpt5, gpt4o, for, optio...",[so can we have 4o also back as team user we p...
13,12,41,12_thank_you_much_listening,"[thank, you, much, listening, thanks, so, bro,...","[thank you, thank you, thank you]"
14,13,40,13_ai_you_that_to,"[ai, you, that, to, in, of, human, people, are...",[theyre taking away what matters to us right ...
15,14,33,14_openai_this_will_of,"[openai, this, will, of, the, to, openais, non...",[so let me get this straight the most hyped ...
16,15,33,15_41_4o_both_please,"[41, 4o, both, please, personally, much, 80, m...",[41 needs to come back too 4o and 41 are not n...
17,16,31,16_gpt4o_emotional_of_and,"[gpt4o, emotional, of, and, it, users, openai,...",[dear openai team i’m writing as a longtime a...
18,17,31,17_it_emotional_gpt5_tone,"[it, emotional, gpt5, tone, gpt4o, and, but, t...",[hi sam i’m a plus user and i truly support gp...
19,18,28,18_o3_bring_back_4o413o45,"[o3, bring, back, 4o413o45, please, o4mini, 4o...","[bring back o3, bring back o3, bring o3 back]"
20,19,28,19_filter_18_for_banned,"[filter, 18, for, banned, be, harmful, gauguin...",[also questions about sexual health i anticipa...
21,20,27,20_4o_release_enough_fix,"[4o, release, enough, fix, save, anevocative, ...","[4o, release 4o release 4o release 4o release ..."
22,21,27,21_41_please_back_well,"[41, please, back, well, 40, important, too, s...","[41 too please, please bring 41 back, 41]"
23,22,25,22_45_50_40_was,"[45, 50, 40, was, it, know, just, back, yes, l...","[will you bring back 45, bring 45 back, please..."
24,23,25,23_yes_undone_expanding_woah,"[yes, undone, expanding, woah, yeah, yup, sadl...","[yes, yes, yes]"
25,24,23,24_worse_holy_much_hallucinating,"[worse, holy, much, hallucinating, bad, is, it...","[worse, much worse, it is much worse]"
26,25,22,25_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, u2014, punct...","[why are there still so many em dashes, connec..."
27,26,21,26_censorship_guardrails_nsfw_speech,"[censorship, guardrails, nsfw, speech, you, ha...",[its not a hard thing though if its history th...
28,27,21,27_yes_please_quick_god,"[yes, please, quick, god, nice, do, starving, ...","[yes please, yes please 🙏, yes please]"
29,28,19,28_deleted_removed_crown_anonymized,"[deleted, removed, crown, anonymized, dime, bi...","[deleted, deleted, deleted]"
30,29,19,29_thinking_reasoning_prompt_we,"[thinking, reasoning, prompt, we, router, mode...",[plus users got completely scammed we lost so ...
31,30,19,30_codex_cli_cursor_limits,"[codex, cli, cursor, limits, plans, coding, so...","[codex cli is open source, hey setting it up i..."
32,31,18,31_ama_answer_really_respond,"[ama, answer, really, respond, other, they, on...",[this ama is absolute trash all they did was r...
33,32,17,32_agreed_well_said_post,"[agreed, well, said, post, agree, this, up, pr...","[agreed guess well see, agreed, agreed]"
34,33,16,33_writing_creative_gpt5_improvements,"[writing, creative, gpt5, improvements, really...",[professional writer and editor here each mode...
35,34,15,34_writing_character_dialogue_creative,"[writing, character, dialogue, creative, it, w...",[it really is so much worse at creative writin...
36,35,15,35_the_is_model_to,"[the, is, model, to, results, openai, gpt5, th...",[to complain about the overnight update to gpt...
37,36,15,36_keep4o_forever_keep4oforever_agree,"[keep4o, forever, keep4oforever, agree, deseve...","[keep4o forever, keep4o forever, keep4o forever]"
38,37,14,37_sam_thanks_you_fuck,"[sam, thanks, you, fuck, thank, business, help...",[i can now finish writing my book thank you sa...
39,38,14,38_free_plan_chatgpt_users,"[free, plan, chatgpt, users, api, or, to, the,...",[i want to know what they will do with the fre...
40,39,13,39_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
41,40,12,40_lol_same_pic_riot,"[lol, same, pic, riot, profile, reference, und...","[lol, lol, same lol]"
42,41,11,41_อนเด_เปล_meme_กอย,"[อนเด, เปล, meme, กอย, กลายเป, snl, police, นห...","[he feels like the language police 🤷🏻‍♀️🙄, 💕 b..."
43,42,10,42_4o_please_logic_miss,"[4o, please, logic, miss, ways, o3, flashy, ch...",[thank you i personally loved switching betwee...
44,43,10,43_negative_backlash_public_general,"[negative, backlash, public, general, feedback...",[were you surprised by the backlash or did you...
45,44,10,44_gpt4o_noncommercial_openai_access,"[gpt4o, noncommercial, openai, access, distill...",[hey naddybear and friends of gpt4o i have cre...
46,45,10,45_he_output_out_code,"[he, output, out, code, gpt, gotten, him, igno...",[i was working on a mobile game with gpt 41 no...

Number of clusters (excluding outliers): 46

KeyBERTInspired

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | chatgpt | window | plus | chat
1,1,chatgpt | it | and | the | to,chatgpt | chatgpt4o | chat | gpt | cant
2,2,models | legacy | the | users | model,models | legacy | model | users | previous
3,3,spaghetti | ding | eating | smith | bar,will | spaghetti | see | live | smith
4,4,back | bring | 4o | please | we,4o | 4ono | please | back | couldt

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/gte-small_pca_dbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,context | 128k | plus | tokens | is
1,1,chatgpt | it | and | the | to,chatgpt | me | chat | for | its
2,2,models | legacy | the | users | model,models | legacy | users | back | have
3,3,spaghetti | ding | eating | smith | bar,spaghetti | ding | smith | bar | tailwind
4,4,back | bring | 4o | please | we,back | bring | 4o | we | quota

📊 Saved MMR topic differences → bertopic_outputs/gte-small_pca_dbscan/MMR_topic_differences.png

Device set to use cuda:0
Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors

T5

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,...
1,1,chatgpt | it | and | the | to,Chatgpt 4o | | | |
2,2,models | legacy | the | users | model,Please bring back legacy models for plus users...
3,3,spaghetti | ding | eating | smith | bar,i could see where you guys are going with llms...
4,4,back | bring | 4o | please | we,...

📊 Saved T5 topic differences → bertopic_outputs/gte-small_pca_dbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,context | window | 32k | 128k | for,Text Data Processing in Natural Language Proce...
1,1,chatgpt | it | and | the | to,Using ChatGPT for IT Support
2,2,models | legacy | the | users | model,Legacy model access for older users
3,3,spaghetti | ding | eating | smith | bar,Spaghetti Eating and Infrastructure Discussion
4,4,back | bring | 4o | please | we,Friendship and Quotas

📊 Saved Open AI topic differences → bertopic_outputs/gte-small_pca_dbscan/Open AI_topic_differences.png
Document visualization saved as PNG: bertopic_outputs/gte-small_pca_dbscan/document_vis.png

2025-08-22 11:16:44,241 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

✅ Document visualization saved as HTML: bertopic_outputs/gte-small_pca_dbscan/document_vis.html
✅ Cluster info saved to bertopic_outputs/gte-small_pca_dbscan/clusters_info.txt
✅ Best k for KMeans: 3 with silhouette 0.262

--- gte-small_pca_kmeans ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,937,-1_to_and_the_it,"[to, and, the, it, of, is, that, for, in, gpt5]",[i believe it is important to have both 4o and...
1,0,236,0_models_plus_the_users,"[models, plus, the, users, to, model, for, you...",[i’ve been paying for the plus subscription fo...
2,1,168,1_context_window_32k_128k,"[context, window, 32k, 128k, for, the, plus, i...",[there should be some context window upgrade f...
3,2,144,2_chatgpt_it_and_the,"[chatgpt, it, and, the, to, me, my, chat, in, ...",[ive been using chatgpt for over 3 years now a...
4,3,91,3_safety_the_for_censorship,"[safety, the, for, censorship, that, you, and,...",[can you do something about the filter surely ...
5,4,88,4_ding_spaghetti_smith_eating,"[ding, spaghetti, smith, eating, very, bar, in...",[yes it sees everything and i mean everything ...
6,5,81,5_back_bring_4o_please,"[back, bring, 4o, please, plz, quota, we, it, ...","[please bring 4o back, bring back 4o please, b..."
7,6,76,6_voice_standard_mode_advanced,"[voice, standard, mode, advanced, cove, the, k...",[i appreciate the innovation truly but the dec...
8,7,68,7_4o_plus_back_subscription,"[4o, plus, back, subscription, for, to, users,...",[yes😭please bring 4o back and keep cove im a l...
9,8,63,8_4o_it_and_to,"[4o, it, and, to, like, not, personality, writ...",[i really hope they go back on this decision i...
10,9,59,9_gpt5_gpt_gpt4_it,"[gpt5, gpt, gpt4, it, you, image, on, did, is,...",[i just asked gpt 5 the same prompt as i did w...
11,10,44,10_4o_gpt_gpt5_back,"[4o, gpt, gpt5, back, gpt4o, option, bring, fo...",[thank you for hearing us would love to have 4...
12,11,42,11_ai_you_to_people,"[ai, you, to, people, of, that, in, and, are, ...",[theyre taking away what matters to us right ...
13,12,41,12_thank_you_much_listening,"[thank, you, much, listening, so, thanks, bro,...","[thank you, thank you, thank you]"
14,13,41,13_ama_comment_they_this,"[ama, comment, they, this, really, you, only, ...",[can you mark the other cohosts their answers ...
15,14,39,14_41_4o_both_45,"[41, 4o, both, 45, please, writing, much, more...",[41 needs to come back too 4o and 41 are not n...
16,15,36,15_gpt4o_emotional_of_and,"[gpt4o, emotional, of, and, it, users, openai,...",[dear openai team i’m writing as a longtime a...
17,16,34,16_they_company_you_their,"[they, company, you, their, tell, billion, cus...",[threats they won’t see mean nothing they wil...
18,17,32,17_openai_this_will_of,"[openai, this, will, of, the, to, openais, is,...",[so let me get this straight the most hyped ...
19,18,31,18_thinking_reasoning_o3_model,"[thinking, reasoning, o3, model, we, gpt5, pro...",[sorry to hear that its been worse for you do ...
20,19,30,19_gpt4o_and_it_the,"[gpt4o, and, it, the, emotional, but, just, gp...",[hi sam i’m a plus user and i truly support gp...
21,20,27,20_41_please_back_40,"[41, please, back, 40, too, important, save, w...","[41 too please, please bring 41 back, 41]"
22,21,26,21_4o_enough_suffice_fill,"[4o, enough, suffice, fill, 3o, save, would, i...","[it’s not 4o 🙁😔, 4o would suffice 5 is basical..."
23,22,24,22_yes_yeah_expanding_woah,"[yes, yeah, expanding, woah, undone, sadly, yu...","[yes, yes, yes]"
24,23,24,23_45_50_back_40,"[45, 50, back, 40, it, know, just, bring, its,...","[will you bring back 45, bring 45 back, please..."
25,24,22,24_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, u2014, punct...","[i see that em dash, connect clauses directly ..."
26,25,20,25_codex_cli_cursor_limits,"[codex, cli, cursor, limits, mcp, plans, codin...",[we do use our models for internal acceleratio...
27,26,19,26_deleted_removed_crown_anonymized,"[deleted, removed, crown, anonymized, dime, bi...","[deleted, deleted, deleted]"
28,27,19,27_yes_please_quick_god,"[yes, please, quick, god, do, starving, hope, ...","[yes please, yes please, yes please]"
29,28,19,28_writing_character_plot_it,"[writing, character, plot, it, to, and, dialog...",[it really is so much worse at creative writin...
30,29,17,29_worse_bad_much_it,"[worse, bad, much, it, is, gruesome, numerous,...","[much worse, worse, it is much worse]"
31,30,17,30_writing_creative_gpt5_improvements,"[writing, creative, gpt5, improvements, really...",[professional writer and editor here each mode...
32,31,17,31_o3_back_bring_please,"[o3, back, bring, please, need, for, riot, was...","[bring back o3, bring back o3, bring o3 back]"
33,32,16,32_4o_indication_models_model,"[4o, indication, models, model, separate, plea...",[im still in awe that you completely rug pulle...
34,33,16,33_lol_same_pic_jumble,"[lol, same, pic, jumble, progressomg, riot, pr...","[lol, lol, same lol]"
35,34,15,34_agreed_well_post_good,"[agreed, well, post, good, agree, both, wholeh...","[agreed guess well see, agreed, agreed]"
36,35,15,35_sam_thanks_you_thank,"[sam, thanks, you, thank, fuck, business, help...",[i can now finish writing my book thank you sa...
37,36,15,36_release_4o_keep4o_forever,"[release, 4o, keep4o, forever, keep4oforever, ...","[keep4o forever, keep4o forever, release 4o re..."
38,37,14,37_the_models_model_openai,"[the, models, model, openai, to, is, for, o3, ...",[worst rollout ever any ai model has idiosync...
39,38,13,38_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
40,39,12,39_o3_4o413o45_bring_back,"[o3, 4o413o45, bring, back, 4o, notification, ...","[bring back 4o413o45, bring back 4o and o3 and..."
41,40,11,40_อนเด_เปล_meme_กอย,"[อนเด, เปล, meme, กอย, กลายเป, snl, police, นห...","[he feels like the language police 🤷🏻‍♀️🙄, 💕 b..."
42,41,10,41_free_users_chatgpt_or,"[free, users, chatgpt, or, for, gpt4o, to, acc...",[will openai consider giving paying users the ...

Number of clusters (excluding outliers): 42

KeyBERTInspired

,Topic,Original,Updated
0,0,models | plus | the | users | to,models | subscription | model | removed | plus
1,1,context | window | 32k | 128k | for,context | chatgpt | window | plus | chat
2,2,chatgpt | it | and | the | to,chatgpt | chatgpt4o | chat | gpt | gpt5
3,3,safety | the | for | censorship | that,harmful | chatgpt | openai | censorship | ai
4,4,ding | spaghetti | smith | eating | very,will | see | live | this | the

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/gte-small_pca_kmeans/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,models | plus | the | users | to,models | users | legacy | is | pro
1,1,context | window | 32k | 128k | for,window | 32k | plus | tokens | to
2,2,chatgpt | it | and | the | to,chatgpt | chat | for | its | version
3,3,safety | the | for | censorship | that,safety | censorship | filter | is | content
4,4,ding | spaghetti | smith | eating | very,ding | spaghetti | smith | bar | 691

📊 Saved MMR topic differences → bertopic_outputs/gte-small_pca_kmeans/MMR_topic_differences.png

Device set to use cuda:0

T5

,Topic,Original,Updated
0,0,models | plus | the | users | to,i get deprecating old models but without suita...
1,1,context | window | 32k | 128k | for,Docs: - will you ever give plus users a decent...
2,2,chatgpt | it | and | the | to,Chatgpt 4o | | | |
3,3,safety | the | for | censorship | that,i hate having to tiptoe around questions scare...
4,4,ding | spaghetti | smith | eating | very,i could see where you guys are going with llms...

📊 Saved T5 topic differences → bertopic_outputs/gte-small_pca_kmeans/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,models | plus | the | users | to,Subscription model limitations and legacy access
1,1,context | window | 32k | 128k | for,Memory Management in Gemini Pro Model
2,2,chatgpt | it | and | the | to,Using ChatGPT for IT Support Chats
3,3,safety | the | for | censorship | that,Internet Safety and Content Censorship
4,4,ding | spaghetti | smith | eating | very,Food and Infrastructure Discussion on Reddit

📊 Saved Open AI topic differences → bertopic_outputs/gte-small_pca_kmeans/Open AI_topic_differences.png

2025-08-22 11:19:00,138 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/gte-small_pca_kmeans/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/gte-small_pca_kmeans/document_vis.html
✅ Cluster info saved to bertopic_outputs/gte-small_pca_kmeans/clusters_info.txt

==== Embedding Model: multilingual-e5-large ====

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/128 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_xlm-roberta_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

Batches:   0%|          | 0/87 [00:00<?, ?it/s]

--- multilingual-e5-large_pca_hdbscan ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1060,-1_the_to_it_and,"[the, to, it, and, you, is, for, of, that, with]",[sam and the rest at openai while this questi...
1,0,252,0_and_to_the_of,"[and, to, the, of, it, that, for, in, is, not]",[dear sam i’m writing as a longtime and deepl...
2,1,138,1_context_window_32k_128k,"[context, window, 32k, 128k, for, is, the, plu...",[hello thanks for answering this one id like...
3,2,91,2_gpt5_to_you_what,"[gpt5, to, you, what, in, are, or, that, chatg...",[sam and team can you explain a little more pu...
4,3,82,3_41_45_both_4o,"[41, 45, both, 4o, please, back, bring, writin...","[both 4o and 41 please, 41 and 45, 41]"
5,4,80,4_gpt5_gpt_is_read,"[gpt5, gpt, is, read, it, to, the, and, worse,...",[somehow gpt5 performs worse than their most b...
6,5,77,5_release_4o_back_bring,"[release, 4o, back, bring, please, we, plz, yo...",[release 4o release 4o release 4o release 4o r...
7,6,71,6_models_legacy_users_plus,"[models, legacy, users, plus, model, the, have...",[is it possible to have the legacy models also...
8,7,68,7_the_for_censorship_filter,"[the, for, censorship, filter, its, and, flagg...",[agreed that sounds frustrating you should be ...
9,8,68,8_4o_plus_back_users,"[4o, plus, back, users, for, to, pay, please, ...",[we are looking into letting plus users to con...
10,9,63,9_voice_standard_mode_advanced,"[voice, standard, mode, advanced, keep, the, c...",[i appreciate the innovation truly but the dec...
11,10,58,10_agreed_yes_this_yessss,"[agreed, yes, this, yessss, agreeing, agree, e...","[agreed, agreed, yes this]"
12,11,53,11_openai_to_the_this,"[openai, to, the, this, of, will, is, openais,...",[it takes time i dont think most people reali...
13,12,45,12_thank_you_much_thanks,"[thank, you, much, thanks, so, listening, sam,...","[thank you, thank you 😭, thank you]"
14,13,39,13_ama_questions_answer_they,"[ama, questions, answer, they, answered, you, ...",[this ama is absolute trash all they did was r...
15,14,33,14_writing_4o_and_creative,"[writing, 4o, and, creative, to, it, was, my, ...",[i really hope they go back on this decision i...
16,15,33,15_o3_thinking_reasoning_gpt5,"[o3, thinking, reasoning, gpt5, gpt5thinking, ...",[yesterday we had a sev and the autoswitcher w...
17,16,31,16_ding_flavor_hah_flavorless,"[ding, flavor, hah, flavorless, nostradamus, l...","[flavor is the word you’re looking for, newest..."
18,17,31,17_4o_to_the_like,"[4o, to, the, like, but, it, and, for, if, you]",[thank you sam this is so important for so man...
19,18,27,18_plus_models_legacy_users,"[plus, models, legacy, users, gpt5, limit, the...",[deprecating the older models 45 and older and...
20,19,25,19_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, it, are, the...","[why are there still so many em dashes, connec..."
21,20,24,20_o3_back_bring_please,"[o3, back, bring, please, for, need, and, 4o, ...","[bring back o3, bring back o3, bring o3 back]"
22,21,24,21_this_am_plus_limits,"[this, am, plus, limits, if, paying, unlimited...",[dropping 40 and the rest of the models is kin...
23,22,22,22_worse_bad_is_cyberpunk,"[worse, bad, is, cyberpunk, flopping, gruesome...","[much worse, it is much worse, worse]"
24,23,21,23_bring_back_4o41o345_acceptable,"[bring, back, 4o41o345, acceptable, 4o413o45, ...","[bring back 4o, bring back 4o, bring back 4o]"
25,24,20,24_graphs_chart_livestream_the,"[graphs, chart, livestream, the, late, they, h...",[ive worked for a few startups and one easy ex...
26,25,20,25_keep4o_forever_keep4oforever_save4o,"[keep4o, forever, keep4oforever, save4o, save,...","[keep4o forever, keep4o forever, keep4o forever]"
27,26,19,26_it_said_cake_memory,"[it, said, cake, memory, past, that, keeps, li...",[i had this happen as well i remarked on somet...
28,27,19,27_deleted_removed_deprecate_,"[deleted, removed, deprecate, , , , , , , ]","[deleted, deleted, deleted]"
29,28,18,28_they_theft_customers_won,"[they, theft, customers, won, liability, ll, h...",[im cancelling if they arent back by the end o...
30,29,18,29_codex_cli_cursor_mcp,"[codex, cli, cursor, mcp, limits, coding, plan...","[codex cli is open source, we do use our model..."
31,30,17,30_link_url_404_legitimate,"[link, url, 404, legitimate, you, did, mine, p...",[nice catch thank you they apparently publish...
32,31,17,31_lol_nice_awhile_goober,"[lol, nice, awhile, goober, meme, chuckle, cou...","[lol, nice profile pic lol, yep the country of..."
33,32,17,32_yes_please_do_quick,"[yes, please, do, quick, god, starving, repeat...","[yes please, yes please, yes please]"
34,33,15,33_api_app_havent_tailwind,"[api, app, havent, tailwind, settings, colors,...",[i hope you can add that to the app because i ...
35,34,14,34_plus_subscription_canceled_cancel,"[plus, subscription, canceled, cancel, cancell...","[will most likely cancel my plus subscription,..."
36,35,13,35_negative_you_feedback_this,"[negative, you, feedback, this, response, amas...",[will you consider reverting this change consi...
37,36,12,36_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
38,37,12,37_company_team_very_dollar,"[company, team, very, dollar, 500, billion, pr...",[trillion dollar companies would tell you this...
39,38,11,38_45_korean_gpt45_was,"[45, korean, gpt45, was, at, english, gpt, cod...",[im korean and gpt45 was overwhelmingly better...
40,39,11,39_please_chatgpt_4o_petition,"[please, chatgpt, 4o, petition, perfect, bring...",[please yeet gpt5 away and return with gpt 4o ...

Number of clusters (excluding outliers): 40

KeyBERTInspired

,Topic,Original,Updated
0,0,and | to | the | of | it,chatgpt | gpt4o | gpt5 | gpt | openai
1,1,context | window | 32k | 128k | for,chatgpt | 32k | this | context | why
2,2,gpt5 | to | you | what | in,chatgpt | gpt5 | gpt4o | gpt4 | gpt
3,3,41 | 45 | both | 4o | please,41 | 40 | 45 | 80 | or
4,4,gpt5 | gpt | is | read | it,gpt5 | gpt4o | gpt4 | chatgpt | gpt

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,and | to | the | of | it,and | not | gpt4o | but | like
1,1,context | window | 32k | 128k | for,context | window | 32k | tokens | and
2,2,gpt5 | to | you | what | in,gpt5 | what | or | chatgpt | have
3,3,41 | 45 | both | 4o | please,41 | please | also | to | important
4,4,gpt5 | gpt | is | read | it,gpt5 | and | worse | instructions | this

📊 Saved MMR topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/MMR_topic_differences.png

Device set to use cuda:0

T5

,Topic,Original,Updated
0,0,and | to | the | of | it,gpt5 has no soul it is flat and lacks emotion ...
1,1,context | window | 32k | 128k | for,i thought it was 32k context window - will you...
2,2,gpt5 | to | you | what | in,gpt5 | | | |
3,3,41 | 45 | both | 4o | please,Docs: - please bring 41 back - both 4o and 41 ...
4,4,gpt5 | gpt | is | read | it,"Topic: gpt5, gpt, is, it, the, read, and, to, ..."

📊 Saved T5 topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,and | to | the | of | it,Sentiment Analysis on GPT-4 and GPT-5 Users
1,1,context | window | 32k | 128k | for,Text Window Size Optimization for Conversation...
2,2,gpt5 | to | you | what | in,GPT-5 and AI Chat Writing Plans
3,3,41 | 45 | both | 4o | please,Writing Improvement and Importance
4,4,gpt5 | gpt | is | read | it,GPT-5 model output accuracy

📊 Saved Open AI topic differences → bertopic_outputs/multilingual-e5-large_pca_hdbscan/Open AI_topic_differences.png

2025-08-22 11:22:38,897 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/multilingual-e5-large_pca_hdbscan/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/multilingual-e5-large_pca_hdbscan/document_vis.html
✅ Cluster info saved to bertopic_outputs/multilingual-e5-large_pca_hdbscan/clusters_info.txt

--- multilingual-e5-large_pca_dbscan ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1139,-1_the_to_it_and,"[the, to, it, and, is, you, for, of, that, in]",[i know the ama is over but i just wanted to a...
1,0,223,0_and_of_the_to,"[and, of, the, to, it, that, gpt4o, for, in, not]",[dear openai team i’m writing as a longtime a...
2,1,138,1_context_window_32k_128k,"[context, window, 32k, 128k, for, the, is, plu...",[hello thanks for answering this one id like...
3,2,83,2_release_4o_back_bring,"[release, 4o, back, bring, please, we, plz, yo...",[release 4o release 4o release 4o release 4o r...
4,3,79,3_models_legacy_users_model,"[models, legacy, users, model, to, the, plus, ...",[is it possible to have the legacy models also...
5,4,75,4_41_45_both_please,"[41, 45, both, please, 4o, back, bring, writin...","[both 4o and 41 please, 41 and 45, 41]"
6,5,66,5_the_censorship_filter_for,"[the, censorship, filter, for, its, and, flagg...",[agreed that sounds frustrating you should be ...
7,6,66,6_4o_plus_back_users,"[4o, plus, back, users, for, to, pay, please, ...",[free users used to be able to use 4o but now ...
8,7,63,7_voice_standard_mode_advanced,"[voice, standard, mode, advanced, keep, the, c...",[i appreciate the innovation truly but the dec...
9,8,57,8_openai_the_this_to,"[openai, the, this, to, of, and, will, is, the...",[im curious to see if they actually answer que...
10,9,49,9_yes_agreed_yessss_agreeing,"[yes, agreed, yessss, agreeing, this, same, ag...","[yes, yes, yes this]"
11,10,46,10_thank_you_much_thanks,"[thank, you, much, thanks, so, listening, sam,...","[🙏 thank you, thank you, thank you]"
12,11,43,11_ama_answer_questions_you,"[ama, answer, questions, you, answered, they, ...",[this ama is absolute trash all they did was r...
13,12,40,12_gpt5_what_writing_in,"[gpt5, what, writing, in, or, creative, is, sc...",[will the upcoming gpt5 include a model that m...
14,13,33,13_o3_thinking_reasoning_gpt5,"[o3, thinking, reasoning, gpt5, gpt5thinking, ...",[yesterday we had a sev and the autoswitcher w...
15,14,32,14_4o_gpt_back_bring,"[4o, gpt, back, bring, please, gpt5, chat, cha...",[can you please bring back 4o for gpt builder ...
16,15,31,15_ding_flavor_hah_flavorless,"[ding, flavor, hah, flavorless, nostradamus, l...","[flavor is the word you’re looking for, newest..."
17,16,28,16_writing_4o_creative_and,"[writing, 4o, creative, and, it, to, was, frie...",[hi this may sound all sorts of sad and pathet...
18,17,26,17_gpt5_gpt_is_joke,"[gpt5, gpt, is, joke, fucking, worse, gpt4o, h...",[gpt5 is like turning on an elon musk personal...
19,18,25,18_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, it, are, pun...","[why are there still so many em dashes, connec..."
20,19,25,19_o3_back_bring_please,"[o3, back, bring, please, for, o4, 4o, and, ne...","[bring o3 back, bring back o3, bring back o3]"
21,20,25,20_4o_to_the_personality,"[4o, to, the, personality, others, for, least,...",[thank you sam this is so important for so man...
22,21,23,21_gpt_gpt5_read_worse,"[gpt, gpt5, read, worse, to, and, it, tighteni...",[somehow gpt5 performs worse than their most b...
23,22,23,22_plus_models_legacy_users,"[plus, models, legacy, users, limit, gpt5, cap...",[why is there plus tier payment model when you...
24,23,22,23_they_theft_customers_subscription,"[they, theft, customers, subscription, this, h...",[everything is temporary but we needed a clear...
25,24,21,24_it_said_cake_he,"[it, said, cake, he, that, memory, past, keeps...",[i had this happen as well i remarked on somet...
26,25,20,25_graphs_chart_livestream_late,"[graphs, chart, livestream, late, the, they, h...",[ive worked for a few startups and one easy ex...
27,26,20,26_worse_bad_is_gruesome,"[worse, bad, is, gruesome, cyberpunk, numerous...","[much worse, it is much worse, worse]"
28,27,19,27_bring_back_4o41o345_acceptable,"[bring, back, 4o41o345, acceptable, 4o413o45, ...",[bring back 4o41o345 removing all the models o...
29,28,19,28_deleted_removed_deprecate_,"[deleted, removed, deprecate, , , , , , , ]","[deleted, deleted, deleted]"
30,29,19,29_gpt5_chatgpt_you_project,"[gpt5, chatgpt, you, project, as, instructions...",[in gpt5 project context seems to be broken co...
31,30,19,30_codex_cli_cursor_mcp,"[codex, cli, cursor, mcp, plans, limits, codin...",[codex the one in chatgpt not cli is decent ri...
32,31,18,31_keep4o_forever_keep4oforever_save4o,"[keep4o, forever, keep4oforever, save4o, save,...","[keep4o forever, keep4o forever, keep4o forever]"
33,32,17,32_yes_please_quick_god,"[yes, please, quick, god, do, starving, repeat...","[yes please, yes please, yes please 🙏]"
34,33,17,33_gpt5_gpt4o_45_gpt,"[gpt5, gpt4o, 45, gpt, 33, korean, was, gpt45,...",[bring back gpt 45 it was the most versatile i...
35,34,16,34_api_app_havent_tailwind,"[api, app, havent, tailwind, colors, bubble, m...",[i hope you can add that to the app because i ...
36,35,15,35_link_404_url_legitimate,"[link, 404, url, legitimate, mine, paying, ple...",[nice catch thank you they apparently publish...
37,36,15,36_product_company_team_very,"[product, company, team, very, dollar, enginee...",[trillion dollar companies would tell you this...
38,37,15,37_lol_nice_pic_awhile,"[lol, nice, pic, awhile, goober, chuckle, meme...",[havent heard the word goober in awhile got a ...
39,38,14,38_unlimited_limits_plus_this,"[unlimited, limits, plus, this, paying, user, ...",[hi sam right now i am paying 65 for this team...
40,39,12,39_robot_solution_being_assumptions,"[robot, solution, being, assumptions, chatgpt,...",[exactly its really dumb and makes assumptions...
41,40,12,40_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
42,41,11,41_plus_subscription_canceled_cancel,"[plus, subscription, canceled, cancel, gaib, r...","[will most likely cancel my plus subscription,..."
43,42,10,42_negative_you_this_rampart,"[negative, you, this, rampart, amas, criticize...",[were you surprised by the backlash or did you...

Number of clusters (excluding outliers): 43

KeyBERTInspired

,Topic,Original,Updated
0,0,and | of | the | to | it,chatgpt | gpt4o | gpt5 | openai | gpt
1,1,context | window | 32k | 128k | for,chatgpt | 32k | this | context | why
2,2,release | 4o | back | bring | please,4oforever | 4ono | gifgiphyaz4squpybai5y | ple...
3,3,models | legacy | users | model | to,models | upgrade | this | please | removed
4,4,41 | 45 | both | please | 4o,41 | 45 | or | and | at

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,and | of | the | to | it,and | gpt4o | not | but | my
1,1,context | window | 32k | 128k | for,context | window | 32k | tokens | and
2,2,release | 4o | back | bring | please,release | 4o | please | we | yes
3,3,models | legacy | users | model | to,models | legacy | plus | why | for
4,4,41 | 45 | both | please | 4o,41 | please | important | and | less

📊 Saved MMR topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/MMR_topic_differences.png

Device set to use cuda:0

T5

,Topic,Original,Updated
0,0,and | of | the | to | it,gpt5 has no soul it is flat and lacks emotion ...
1,1,context | window | 32k | 128k | for,Docs: - I thought it was 32k context window - ...
2,2,release | 4o | back | bring | please,release 4o release 4o release 4o release 4o re...
3,3,models | legacy | users | model | to,"if, why, back, pro, old, good, give, them, on,..."
4,4,41 | 45 | both | please | 4o,41 and 45 - 41 | | | |

📊 Saved T5 topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,and | of | the | to | it,Conversation about emotional reactions to GPT-...
1,1,context | window | 32k | 128k | for,Text Chat Context Window Size
2,2,release | 4o | back | bring | please,Software Update Feedback
3,3,models | legacy | users | model | to,Legacy model support and user access requireme...
4,4,41 | 45 | both | please | 4o,Effective Writing Strategies and Techniques

📊 Saved Open AI topic differences → bertopic_outputs/multilingual-e5-large_pca_dbscan/Open AI_topic_differences.png

2025-08-22 11:25:14,977 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/multilingual-e5-large_pca_dbscan/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/multilingual-e5-large_pca_dbscan/document_vis.html
✅ Cluster info saved to bertopic_outputs/multilingual-e5-large_pca_dbscan/clusters_info.txt
✅ Best k for KMeans: 3 with silhouette 0.258

--- multilingual-e5-large_pca_kmeans ---

BERT Topics

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1083,-1_the_to_it_and,"[the, to, it, and, is, you, for, that, of, with]",[i dont know if you are reading this sam as im...
1,0,231,0_and_to_the_of,"[and, to, the, of, it, that, for, in, gpt4o, not]",[dear openai team i’m writing as a longtime a...
2,1,138,1_context_window_32k_128k,"[context, window, 32k, 128k, for, the, is, plu...",[hello thanks for answering this one id like...
3,2,84,2_release_4o_back_bring,"[release, 4o, back, bring, please, we, plz, yo...",[release 4o release 4o release 4o release 4o r...
4,3,77,3_you_ama_they_answer,"[you, ama, they, answer, about, this, question...",[did you see the negative feedback that people...
5,4,75,4_4o_to_it_and,"[4o, to, it, and, writing, was, the, for, crea...",[i cannot speak in terms of professional writi...
6,5,72,5_4o_plus_back_users,"[4o, plus, back, users, for, month, to, pay, p...",[we are looking into letting plus users to con...
7,6,67,6_the_for_censorship_filter,"[the, for, censorship, filter, its, and, flagg...",[agreed that sounds frustrating you should be ...
8,7,67,7_models_legacy_users_plus,"[models, legacy, users, plus, model, have, the...",[is it possible to have the legacy models also...
9,8,66,8_gpt5_what_you_to,"[gpt5, what, you, to, in, are, the, or, chatgp...",[a few questions choose what you’d like 1 i t...
10,9,66,9_gpt5_gpt_is_output,"[gpt5, gpt, is, output, the, worse, read, inst...",[gpt5 has the same problem as every previous m...
11,10,63,10_voice_standard_mode_advanced,"[voice, standard, mode, advanced, keep, the, c...",[i appreciate the innovation truly but the dec...
12,11,53,11_openai_the_this_to,"[openai, the, this, to, of, will, is, openais,...",[it takes time i dont think most people reali...
13,12,48,12_agreed_yes_yessss_agreeing,"[agreed, yes, yessss, agreeing, exactly, same,...","[yes, agreed, agreed]"
14,13,47,13_thank_you_much_thanks,"[thank, you, much, thanks, so, listening, sam,...","[thank you, thank you, thank you]"
15,14,40,14_41_please_back_bring,"[41, please, back, bring, 45, 4o, too, both, i...","[can you please bring 41 back, please bring 41..."
16,15,33,15_o3_thinking_reasoning_gpt5,"[o3, thinking, reasoning, gpt5, gpt5thinking, ...",[yesterday we had a sev and the autoswitcher w...
17,16,32,16_ding_flavor_flashback_logo,"[ding, flavor, flashback, logo, hah, nostradam...","[flavor is the word you’re looking for, newest..."
18,17,28,17_this_am_paying_if,"[this, am, paying, if, plus, limits, for, unli...",[good because the cost difference is massive t...
19,18,26,18_plus_models_legacy_users,"[plus, models, legacy, users, gpt5, limit, cap...",[why is there plus tier payment model when you...
20,19,25,19_em_dashes_dash_emdashes,"[em, dashes, dash, emdashes, use, it, are, the...","[why are there still so many em dashes, connec..."
21,20,24,20_o3_bring_back_please,"[o3, bring, back, please, for, need, and, 4o, ...","[bring back o3, bring back o3, bring o3 back]"
22,21,24,21_41_both_writing_4o,"[41, both, writing, 4o, 45, depending, if, wri...",[i vote for both or 41 4o has a strong nostalg...
23,22,20,22_codex_cli_cursor_plans,"[codex, cli, cursor, plans, mcp, coding, limit...",[codex the one in chatgpt not cli is decent ri...
24,23,20,23_worse_bad_is_cyberpunk,"[worse, bad, is, cyberpunk, gruesome, embrace,...","[much worse, it is much worse, worse]"
25,24,20,24_lol_nice_chuckle_country,"[lol, nice, chuckle, country, awhile, pic, snl...",[yep the country of freedom of expression lol ...
26,25,20,25_bring_back_4o41o345_4o413o45,"[bring, back, 4o41o345, 4o413o45, acceptable, ...","[bring 4o back, bring 4o back, bring back 4o]"
27,26,20,26_yes_please_do_quick,"[yes, please, do, quick, god, starving, yesss,...","[yes please 🙏, yes please, yes please]"
28,27,19,27_product_company_team_investor,"[product, company, team, investor, very, they,...",[all i want to say is if anyone on the team re...
29,28,19,28_deleted_removed_deprecate_,"[deleted, removed, deprecate, , , , , , , ]","[deleted, deleted, deleted]"
30,29,19,29_keep4o_forever_keep4oforever_save4o,"[keep4o, forever, keep4oforever, save4o, save,...","[keep4o forever, keep4o forever, keep4o foreve..."
31,30,16,30_said_cake_it_memory,"[said, cake, it, memory, past, keeps, like, th...",[i had this happen as well i remarked on somet...
32,31,16,31_graphs_livestream_chart_late,"[graphs, livestream, chart, late, percentages,...",[ive worked for a few startups and one easy ex...
33,32,15,32_api_app_havent_tailwind,"[api, app, havent, tailwind, settings, colors,...",[i hope you can add that to the app because i ...
34,33,13,33_link_404_legitimate_mine,"[link, 404, legitimate, mine, paying, please, ...",[oh please there are a lot of people who have ...
35,34,13,34_bring_4o_chatgpt_back,"[bring, 4o, chatgpt, back, chat, come, please,...",[come on please get me back to my previous ver...
36,35,13,35_plus_subscription_canceled_cancel,"[plus, subscription, canceled, cancel, cancell...",[but in all seriousness thank you i was about ...
37,36,12,36_blank_robot_tell_solution,"[blank, robot, tell, solution, being, assumpti...",[why does chatgpt love using this language “b...
38,37,12,37_they_customers_theft_liability,"[they, customers, theft, liability, ll, their,...",[this is what happens when corporations and sh...
39,38,12,38_zenith_summit_lmarena_on,"[zenith, summit, lmarena, on, was, feedback, o...",[agree zenith was consistently outperforming s...
40,39,11,39_45_was_korean_gpt45,"[45, was, korean, gpt45, it, english, handle, ...",[im korean and gpt45 was overwhelmingly better...
41,40,10,40_gpt5thinking_thinking_gpt5minithinking_reas...,"[gpt5thinking, thinking, gpt5minithinking, rea...",[yes gpt5 will automatically decide to use rea...

Number of clusters (excluding outliers): 41

KeyBERTInspired

,Topic,Original,Updated
0,0,and | to | the | of | it,chatgpt | gpt4o | gpt5 | openai | gpt
1,1,context | window | 32k | 128k | for,chatgpt | 32k | this | context | why
2,2,release | 4o | back | bring | please,4ono | gifgiphyaz4squpybai5y | 404o | pleaseee...
3,3,you | ama | they | answer | about,this | answered | lmao | and | or
4,4,4o | to | it | and | writing,or | this | better | and | so

📊 Saved KeyBERTInspired topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/KeyBERTInspired_topic_differences.png

MMR

,Topic,Original,Updated
0,0,and | to | the | of | it,and | gpt4o | but | like | this
1,1,context | window | 32k | 128k | for,context | window | 32k | and | tokens
2,2,release | 4o | back | bring | please,release | 4o | please | we | comments
3,3,you | ama | they | answer | about,this | questions | are | how | only
4,4,4o | to | it | and | writing,4o | writing | was | creative | like

📊 Saved MMR topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/MMR_topic_differences.png

Device set to use cuda:0
Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors

T5

,Topic,Original,Updated
0,0,and | to | the | of | it,gpt4o i know change is inevitable but 4o wasn’...
1,1,context | window | 32k | 128k | for,Docs: - I thought it was 32k context window - ...
2,2,release | 4o | back | bring | please,release 4o release 4o release 4o release 4o re...
3,3,you | ama | they | answer | about,did you really do an ama and only answer 2 que...
4,4,4o | to | it | and | writing,4o i know 5 may improve but 4o was special and...

📊 Saved T5 topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/T5_topic_differences.png

Open AI

,Topic,Original,Updated
0,0,and | to | the | of | it,Advanced AI models and emotional responses in ...
1,1,context | window | 32k | 128k | for,Chat Length in Gemini Pro and User Experience
2,2,release | 4o | back | bring | please,Release of new features and improvements
3,3,you | ama | they | answer | about,Reddit AMA on Responding to Negative Comments
4,4,4o | to | it | and | writing,Creative Writing Process

📊 Saved Open AI topic differences → bertopic_outputs/multilingual-e5-large_pca_kmeans/Open AI_topic_differences.png

2025-08-22 11:27:50,257 - BERTopic - WARNING: Note that extracting more than 100 words from a sparse can slow down computation quite a bit.

Document visualization saved as PNG: bertopic_outputs/multilingual-e5-large_pca_kmeans/document_vis.png
✅ Document visualization saved as HTML: bertopic_outputs/multilingual-e5-large_pca_kmeans/document_vis.html
✅ Cluster info saved to bertopic_outputs/multilingual-e5-large_pca_kmeans/clusters_info.txt

# Only one config

In [ ]:
# ==================== Config ====================
embedding_models = {
    "multilingual-e5-large": "intfloat/multilingual-e5-large-instruct"
}

dim_reduction_models = {
    "umap": UMAP(n_components=5, min_dist=0.0, metric="cosine", random_state=42),
}

clustering_models = {
    "hdbscan": HDBSCAN(min_cluster_size=10, metric="euclidean", cluster_selection_method="eom"),
}

output_dir = "bertopic_outputs"
os.makedirs(output_dir, exist_ok=True)

# ==================== Main Loop ====================
for emb_name, emb_model_name in embedding_models.items():
    print(f"\n==== Embedding Model: {emb_name} ====")

    # Load embedding model
    embedding_model = SentenceTransformer(emb_model_name)
    embeddings = embedding_model.encode(abstracts, show_progress_bar=True)

    for dim_name, dim_model in dim_reduction_models.items():
        reduced_embeddings = dim_model.fit_transform(embeddings)

        for clust_name, clust_model in clustering_models.items():

            # If KMeans, find optimal k
            if clust_name == "kmeans":
                best_k = find_best_k(reduced_embeddings, k_min=2, k_max=15)
                clust_model = KMeans(n_clusters=best_k, random_state=42)

            model_name = f"{emb_name}_{dim_name}_{clust_name}"
            print(f"\n--- {model_name} ---")

            # Create output folder
            model_dir = os.path.join(output_dir, model_name)
            os.makedirs(model_dir, exist_ok=True)

            # Build BERTopic model
            topic_model = BERTopic(
                embedding_model=embedding_model,
                umap_model=dim_model if dim_name=="umap" else None,
                hdbscan_model=clust_model if clust_name=="hdbscan" else None,
                verbose=False
            )

            # Fit model
            topics, probs = topic_model.fit_transform(abstracts, embeddings)

            # Get topic info
            info = topic_model.get_topic_info()

            print('\nBERT Topics')
            display(info)

            # Exclude outlier topic (-1)
            num_clusters = len(info[info.Topic != -1])
            print(f"Number of clusters (excluding outliers): {num_clusters}")

            # Save original topic representations
            original_topics = deepcopy(topic_model.topic_representations_)

            # ===== Update representations =====
            topic_model.update_topics(abstracts, representation_model=KeyBERTInspired())

            # Show topic differences
            print('\nKeyBERTInspired')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "KeyBERTInspired", model_dir)


            topic_model.update_topics(abstracts, representation_model=MaximalMarginalRelevance(diversity=0.5))

            print('\nMMR')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "MMR", model_dir)


            max_len = 400
            truncated_docs = [doc[:max_len] for doc in abstracts]

            generator = pipeline("text2text-generation", model="google/flan-t5-small")
            rep_t5 = TextGeneration(generator, prompt="Topic: [KEYWORDS]\nDocs: [DOCUMENTS]")
            topic_model.update_topics(truncated_docs, representation_model=rep_t5)

            print('\nT5')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "T5", model_dir)



            prompt = """
            I have a topic that contains the following comments from reditt thread:
            [COMMENTS]

            The topic is described by the following keywords: [KEYWORDS]

            Based on the information above, extract a short topic label in the following format:
            topic: <short topic label>
            """

            # Update our topic representations using GPT-3.5
            client = openai.OpenAI(api_key=userdata.get('openaikey'))
            representation_model = OpenAI(
                client, model="gpt-3.5-turbo", exponential_backoff=True, chat=True, prompt=prompt
            )
            topic_model.update_topics(abstracts, representation_model=representation_model)

            print('\nOpen AI')
            display(topic_differences(topic_model, original_topics))
            save_topic_differences_png(topic_model, original_topics, "Open AI", model_dir)


            topic_model.get_topic_info()['Representation'].values

In [4]:
from google.colab import files
import shutil

# Folder you want to download
folder_path = "all_summaries"

# Make a zip archive
shutil.make_archive(folder_path, 'zip', folder_path)

# Download the zip
files.download(folder_path+".zip")

In [1]:
import os
import itertools
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import json
from google.colab import drive
drive.mount('/content/drive')


# ==================== Config ====================
embedding_models = {
    "gte-small": "thenlper/gte-small",
    "multilingual-e5-large": "intfloat/multilingual-e5-large-instruct"
}

dim_reduction_models = {
    # "umap": "umap",
    "pca": "pca"
}

clustering_models = {
    "hdbscan": "hdbscan",
    "dbscan": "dbscan",
    "kmeans": "kmeans"
}

# Root folders
output_root = "/content/drive/MyDrive/bertopic_outputs"
summary_root = "all_summaries"
os.makedirs(summary_root, exist_ok=True)

def crop_vertical_whitespace(img, threshold=0.98):
    """Dynamically crop top/bottom whitespace from an image."""
    if img.ndim == 3:
        gray = img.mean(axis=2)
    else:
        gray = img
    if gray.max() > 1.5:
        gray = gray / 255.0
    mask = gray < threshold
    rows_with_content = np.where(mask.any(axis=1))[0]
    if len(rows_with_content) == 0:
        return img
    top, bottom = rows_with_content[0], rows_with_content[-1]
    return img[top:bottom+1, :, :]

def generate_summary_page(config_name):
    config_path = os.path.join(output_root, config_name)

    # Representation model images (2x2 grid now)
    rep_models = ["KeyBERTInspired", "MMR", "T5", "Open AI"]
    rep_images = [os.path.join(config_path, f"{rm}_topic_differences.png") for rm in rep_models]

    # Wordclouds (top 4 topics only now)
    wc_images = [os.path.join(config_path, f"wordcloud_topic{i}.png") for i in range(4)]

    # Cluster visualization
    doc_vis = os.path.join(config_path, "document_vis.png")

    # Number of clusters (excluding outliers)
    cluster_file = os.path.join(config_path, "clusters_info.json")
    num_clusters = None
    if os.path.exists(cluster_file):
        with open(cluster_file, "r", encoding="utf-8") as f:
            clusters_info = json.load(f)
        num_clusters = sum(1 for cid in clusters_info if cid != "-1")

    # --- Unified grid dimensions ---
    fig = plt.figure(figsize=(14, 18))

    # --- Row 0+1: Representation model plots (2x2) ---
    for i, img_path in enumerate(rep_images):
        if os.path.exists(img_path):
            img = mpimg.imread(img_path)
            img_cropped = crop_vertical_whitespace(img)

            row, col = divmod(i, 2)
            ax = plt.subplot2grid((6, 4), (row, col*2), colspan=2, rowspan=1)
            ax.imshow(img_cropped)
            ax.set_title(rep_models[i], fontsize=10)
            ax.axis("off")

    # --- Row 2: Wordclouds (1x4) ---
    for i, img_path in enumerate(wc_images):
        if os.path.exists(img_path):
            ax = plt.subplot2grid((6, 4), (2, i), colspan=1, rowspan=1)
            ax.imshow(mpimg.imread(img_path))
            ax.set_title(f"Topic {i}", fontsize=10)
            ax.axis("off")

    # --- Row 3-5: Cluster visualization (full width, 3 rows) ---
    ax = plt.subplot2grid((6, 4), (3, 0), colspan=4, rowspan=3)
    if os.path.exists(doc_vis):
        ax.imshow(mpimg.imread(doc_vis))
        title_text = "Cluster Visualization"
        if num_clusters is not None:
            title_text += f" | #Clusters (excluding outliers) = {num_clusters}"
        ax.set_title(title_text, fontsize=12)
    ax.axis("off")

    # Remove all white space between plots
    plt.subplots_adjust(wspace=0, hspace=0, top=0.92, bottom=0.02, left=0.02, right=0.98)
    plt.suptitle(f"Configuration: {config_name}", fontsize=16, y=0.97)

    # Save
    save_path = os.path.join(summary_root, f"{config_name}_summary.png")
    plt.savefig(save_path, bbox_inches="tight", dpi=150)
    plt.close(fig)
    print(f"Saved summary: {save_path}")

# --- Loop over configs ---
for emb, red, clus in itertools.product(
    embedding_models.keys(),
    dim_reduction_models.keys(),
    clustering_models.keys()
):
    config_name = f"{emb}_{red}_{clus}"
    generate_summary_page(config_name)

print(f"\nAll summary images are stored in folder: {summary_root}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Saved summary: all_summaries/gte-small_pca_hdbscan_summary.png
Saved summary: all_summaries/gte-small_pca_dbscan_summary.png
Saved summary: all_summaries/gte-small_pca_kmeans_summary.png
Saved summary: all_summaries/multilingual-e5-large_pca_hdbscan_summary.png
Saved summary: all_summaries/multilingual-e5-large_pca_dbscan_summary.png
Saved summary: all_summaries/multilingual-e5-large_pca_kmeans_summary.png

All summary images are stored in folder: all_summaries

In [3]:
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import json

# ==================== Config ====================
embedding_models = ["gte-small", "multilingual-e5-large"]
dim_reduction_models = ["umap", "pca"]
clustering_models = ["hdbscan", "dbscan", "kmeans"]

# Root folders
# Root folders
output_root = "/content/drive/MyDrive/bertopic_outputs"
summary_root = "all_summaries"
os.makedirs(summary_root, exist_ok=True)

def get_num_clusters(config_path):
    cluster_file = os.path.join(config_path, "clusters_info.json")
    if os.path.exists(cluster_file):
        with open(cluster_file, "r", encoding="utf-8") as f:
            clusters_info = json.load(f)
        return sum(1 for cid in clusters_info if cid != "-1")
    return None

def generate_combined_cluster_plot(embedding_name):
    # rows: clustering, cols: dim reduction
    fig, axes = plt.subplots(len(clustering_models), len(dim_reduction_models),
                             figsize=(12, 12))  # 3x2 grid

    for i, clus in enumerate(clustering_models):
        for j, dim_red in enumerate(dim_reduction_models):
            config_name = f"{embedding_name}_{dim_red}_{clus}"
            config_path = os.path.join(output_root, config_name)
            doc_vis_path = os.path.join(config_path, "document_vis.png")

            ax = axes[i, j] if len(clustering_models) > 1 else axes[j]

            if os.path.exists(doc_vis_path):
                img = mpimg.imread(doc_vis_path)
                ax.imshow(img)
                num_clusters = get_num_clusters(config_path)
                title_text = f"{embedding_name.upper()} + {dim_red.upper()} + {clus.upper()}"
                if num_clusters is not None:
                    title_text += f" | #Clusters={num_clusters}"
                ax.set_title(title_text, fontsize=10)
            else:
                ax.text(0.5, 0.5, f"Missing {config_name}", ha='center', va='center')

            ax.axis("off")

    plt.tight_layout()
    save_path = os.path.join(summary_root, f"{embedding_name}_all_dimred_clusters.png")
    plt.savefig(save_path, bbox_inches="tight", dpi=150)
    plt.close(fig)
    print(f"Saved combined cluster plot: {save_path}")


# --- Loop over embeddings ---
for emb in embedding_models:
    generate_combined_cluster_plot(emb)

print(f"\nAll combined cluster images are stored in folder: {summary_root}")

Saved combined cluster plot: all_summaries/gte-small_all_dimred_clusters.png
Saved combined cluster plot: all_summaries/multilingual-e5-large_all_dimred_clusters.png

All combined cluster images are stored in folder: all_summaries